hertzbeat-for-dockercompose/Readme.md
hertzbeat-for-dockercompose/conf/application.yml
hertzbeat-for-dockercompose/conf/sql/schema.sql
hertzbeat-for-dockercompose/conf/sureness.yml
hertzbeat-for-dockercompose/dbdata/mysqldata/.gitignore
hertzbeat-for-dockercompose/dbdata/taosdata/.gitignore
hertzbeat-for-dockercompose/docker-compose.yaml

原有docker部署方案过于复杂，需要手动初始化数据等一系列操作，
故提供一种新部署方法：
采用docker-compose进行容器编排使部署更加简单只需要docker-compose up -d 一键启动mysql 、tdengine、hearzbeat等容器（已验证）
后期也可以通过commpos2k8s小工具 将docker-compos.yaml 转化为deployment 在k8s中部署（缺乏k8s 环境，待验证）

添加docker-compose部署方案

---

collector/src/main/java/com/usthe/collector/dispatch/CommonDispatcher.java
common/src/main/java/com/usthe/common/entity/job/Job.java
warehouse/src/main/java/com/usthe/warehouse/store/TdEngineDataStorage.java

采集任务超时监测线程处理异常
导致频繁出现日志： [metrics-task-monitor] ERROR com.usthe.common.entity.job.Job Line:169 - Job 6429019850145792 appId 6429019847000064 app linux metrics memory remove empty error in priorMetrics.  
原因：超时任务监测KEY在不同地方PUT的格式不一样，导致某些已经完成的任务被误认为未完成超时，出现此问题。
解决：fix key格式不一致问题，将采集任务超时时间由120秒跳高到240秒。

[collector]fix 采集任务超时监测线程处理异常

---

manager/src/main/java/com/usthe/manager/service/impl/MonitorServiceImpl.java

feature:only collect available metrics when detect.  
Before, we collect all metrics when detect, this may speed too much waiting time.

[manager]feature:only collect available metrics when detect

---

manager/src/main/resources/define/app/linux.yml
web-app/src/app/routes/monitor/monitor-edit/monitor-edit.component.less
web-app/src/app/routes/monitor/monitor-edit/monitor-edit.component.ts

fix linux interface metrics no instance. 
Before, the linux interface may have some instance, but not config, it cause metrics value combine 
like this: same timesamp has two value point 
Now, config the interface_name as instance.

[manager]bugfix:fix linux interface metrics no instance

---

collector/pom.xml
manager/src/main/java/com/usthe/manager/service/impl/MonitorServiceImpl.java

non-supported character set when monitor GBK oracle
need orai18n.jar to support GBK.

[collector]bugfix: non-supported character set when monitor GBK oracle

---

manager/src/main/resources/define/app/centos.yml
manager/src/main/resources/define/app/linux.yml
manager/src/main/resources/define/app/ubuntu.yml

fix illegal value collect metrics: linux.cpu.interrupt
shell: 
```vmstat 1 1 | awk 'NR==3{print $11}'```

[manager]bugfix: linux.cpu.interrupt metric value is illegal

---

web-app/src/styles/theme.less

fix side menu invisible when theme is dark, see issue #130

[web-app]bugfix:fix side menu invisible when theme is dark

---

common/src/main/java/com/usthe/common/entity/alerter/JsonMapAttributeConverter.java
common/src/main/java/com/usthe/common/entity/manager/JsonByteListAttributeConverter.java
common/src/main/java/com/usthe/common/entity/manager/JsonOptionListAttributeConverter.java
common/src/main/java/com/usthe/common/entity/manager/JsonTagListAttributeConverter.java
common/src/main/java/com/usthe/common/entity/manager/NoticeRule.java
common/src/main/java/com/usthe/common/util/GsonUtil.java
manager/src/main/java/com/usthe/manager/service/impl/NoticeConfigServiceImpl.java
web-app/src/app/layout/basic/basic.component.ts
web-app/src/app/layout/passport/passport.component.html
web-app/src/app/pojo/NoticeRule.ts
web-app/src/app/routes/alert/alert-notice/alert-notice.component.ts

bugfix: fix only one filter label can be set, and multiple filter labels cannot be set when alarm notification policy

[monitor]bugfix: fix only one filter label can be set when notification

---

alerter/src/main/java/com/usthe/alert/AlerterProperties.java
alerter/src/main/java/com/usthe/alert/calculate/CalculateAlarm.java
collector/src/main/java/com/usthe/collector/collect/icmp/IcmpCollectImpl.java
manager/src/main/resources/application.yml
script/application.yml

feature: support system alert trigger time configuration 
application.yml.  
```
alerter:
console-url: https://console.tancloud.cn
alert-eval-interval-base: 600000
max-alert-eval-interval: 86400000
system-alert-trigger-times: 1
```

[alerter]bugfix: support system alert trigger time

---

web-app/src/app/routes/alert/alert-notice/alert-notice.component.html
web-app/src/app/routes/alert/alert-setting/alert-setting.component.html
web-app/src/app/routes/monitor/monitor-detail/monitor-detail.component.html
web-app/src/app/routes/monitor/monitor-edit/monitor-edit.component.html
web-app/src/app/routes/monitor/monitor-new/monitor-new.component.html
web-app/src/app/routes/setting/tags/tags.component.html
web-app/src/assets/app-data.json

update help domain from tancloud.cn to hertzbeat.com

[web-app]feature:update help domain from tancloud.cn to hertzbeat.com

---

collector/src/main/java/com/usthe/collector/collect/http/HttpCollectImpl.java
collector/src/main/java/com/usthe/collector/dispatch/DispatchConstants.java

use basic auth with raw HTTP headers instead of preemptive mode.   
refer https://www.baeldung.com/httpclient-basic-authentication

[collector] use basic auth with raw HTTP headers instead of preemptive

---

common/src/main/java/com/usthe/common/util/IpDomainUtil.java
common/src/main/java/com/usthe/common/util/SnowFlakeIdGenerator.java
common/src/main/java/com/usthe/common/util/SnowFlakeIdWorker.java
common/src/test/java/com/usthe/common/util/SnowFlakeIdGeneratorTest.java

Note that due to the front-end JS TS parsing large numbers in json, precision will be lost. 
SnowFlakeId cannot exceed hexadecimal 0x1FFFFFFFFFFFFFF.

[common] bugfix SnowFlakeId cannot exceed hexadecimal 0x1FFFFFFFFFFFFFF

---

warehouse/src/main/java/com/usthe/warehouse/store/TdEngineDataStorage.java

[warehouse] bugfix exception when tdengine create table SQL containing special character value. 
Solve with escape characters ``` `field` ```
eg:  [tdengine-data]: create mysql_basic_super use sql: 
```
CREATE STABLE IF NOT EXISTS `mysql_basic_super` (ts TIMESTAMP, instance NCHAR(200), `version` NCHAR(200), `port` NCHAR(200), `datadir` NCHAR(200), `max_connections` DOUBLE) TAGS (monitor BIGINT).
```

[warehouse] bugfix exception when tdengine create table SQL contain special char

---

manager/pom.xml

Upgrade snakeyaml 1.26 to 1.31 for vulnerability fix:
- [CVE-2022-38752](https://www.oscs1024.com/hd/MPS-2022-56041)
- [CVE-2022-25857](https://www.oscs1024.com/hd/MPS-2022-5144)
- [CVE-2022-38751](https://www.oscs1024.com/hd/MPS-2022-56040)

fix(sec): upgrade snakeyaml to 1.31

---

manager/pom.xml

Upgrade snakeyaml 1.26 to 1.31 for vulnerability fix:
- [CVE-2022-25857](https://www.oscs1024.com/hd/MPS-2022-5144)
- [CVE-2022-25857](https://www.oscs1024.com/hd/MPS-2022-5144)
- [CVE-2022-38751](https://www.oscs1024.com/hd/MPS-2022-56040)

[manager] upgrade snakeyaml to 1.31 (#313)

---

web-app/src/app/routes/monitor/monitor-data-chart/monitor-data-chart.component.html
web-app/src/app/routes/monitor/monitor-data-chart/monitor-data-chart.component.ts

[web-app] fix echarts y-axis value tip overflow

---

collector/pom.xml

There are 1 security vulnerabilities found in org.postgresql:postgresql 42.3.3
- [CVE-2022-31197](https://www.oscs1024.com/hd/CVE-2022-31197)
Upgrade org.postgresql:postgresql from 42.3.3 to 42.4.1 for vulnerability fix

fix(sec): upgrade org.postgresql:postgresql to 42.4.1

---

collector/pom.xml
manager/pom.xml

There are 1 security vulnerabilities found in mysql:mysql-connector-java 8.0.27
- [CVE-2022-21363](https://www.oscs1024.com/hd/CVE-2022-21363)
Upgrade mysql:mysql-connector-java from 8.0.27 to 8.0.28 for vulnerability fix

fix(sec): upgrade mysql:mysql-connector-java to 8.0.28

---

web-app/src/app/routes/monitor/monitor-data-chart/monitor-data-chart.component.ts

[web-app] fix history echarts chart tooltip only show one instance

---

manager/src/test/java/com/usthe/manager/controller/NoticeConfigControllerTest.java

The test class is written and the test is completed

NoticeConfigController Test class writing completed

---

collector/src/main/java/com/usthe/collector/dispatch/MetricsCollect.java

calculate计算中使用了A | B的表达式，如果A和B都为null会打印错误日志，虽然不会影响功能的正常使用，仍然修复
经过测试，不会影响其他监控的使用

bugfix: Fixed expression:(A | B), A and B are null, print the error log

---

home/i18n/en/docusaurus-plugin-content-docs/current/advanced/extend-jdbc.md

Typo repair

---

manager/src/test/java/com/usthe/manager/controller/AccountControllerTest.java

```
Error:  Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.349 s <<< FAILURE! - in com.usthe.manager.controller.AccountControllerTest
Error:  authGetToken  Time elapsed: 0.22 s  <<< ERROR!
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is com.usthe.sureness.processor.exception.ExtSurenessException: Please config your custom jwt secret. JsonWebTokenUtil.setDefaultSecretKey | sureness.jwt.secret
at com.usthe.manager.controller.AccountControllerTest.authGetToken(AccountControllerTest.java:41)
Caused by: com.usthe.sureness.processor.exception.ExtSurenessException: Please config your custom jwt secret. JsonWebTokenUtil.setDefaultSecretKey | sureness.jwt.secret
at com.usthe.manager.controller.AccountControllerTest.authGetToken( …
```

[manager] bugfix authGetToken unit test case error

---

home/docs/others/contributing.md

本地启动不再需要部署启动依赖服务MYSQL和TDengine数据库

[doc] note: startup via source code not required mysql and tdengine env

---

web-app/src/app/routes/alert/alert-center/alert-center.component.html
web-app/src/app/routes/dashboard/dashboard.component.html
web-app/src/app/routes/dashboard/dashboard.component.less

1. category card background color 
2. click the card to jump to the monitors
After voting, we used the theme color instead of pink.

[web-app] update dashboard category card ui

---

script/docker-compose/hertzbeat-mysql-tdengine/README.md

docker exec -it tdengine /bin/bash
进入tdengine容器这里容器名称写错误了，最新版的容器默认名称是：compose-tdengine

[doc] fix compose doc `exec -it container name` error 

---

script/docker-compose/hertzbeat-mysql-tdengine/README.md

docker exec -it tdengine /bin/bash
进入tdengine容器这里容器名称写错误了，最新版的容器默认名称是：compose-tdengine

[doc] fix compose doc exec -it container name error

---

script/docker-compose/hertzbeat-mysql-iotdb/docker-compose.yaml
script/docker-compose/hertzbeat-mysql-tdengine/docker-compose.yaml

There is no need to mapping `mysql` and `tdengine` service ports to host. If there is a host `mysql` deamon, the port will be conflict.

remove unused host bind ports

---

alerter/src/test/java/com/usthe/alert/AlerterWorkerPoolTest.java

alerterWorkerPool simple test, pls check it

[alerter] add AlerterWorkerPoolTest (#443)

---

collector/pom.xml
common/pom.xml

There are 1 security vulnerabilities found in com.google.code.gson:gson 2.8.8
- [CVE-2022-25647](https://www.oscs1024.com/hd/CVE-2022-25647)
Upgrade com.google.code.gson:gson from 2.8.8 to 2.8.9 for vulnerability fix

fix(sec): upgrade com.google.code.gson:gson to 2.8.9

---

collector/pom.xml

There are 1 security vulnerabilities found in org.postgresql:postgresql 42.4.1
- [CVE-2022-41946](https://www.oscs1024.com/hd/CVE-2022-41946)
Upgrade org.postgresql:postgresql from 42.4.1 to  for vulnerability fix

fix(sec): upgrade org.postgresql:postgresql to 

---

collector/src/main/java/com/usthe/collector/collect/database/JdbcCommonCollect.java

Oracle will report an error after monitoring for a long time: the maximum number of open cursors has been exceeded.
`ORA-01000`

[collector] bugfix oracle query error: ORA-01000 happen

---

warehouse/src/test/java/com/usthe/warehouse/WarehouseWorkerPoolTest.java

The test has been already provided by @TherChenYang. This PR is a minor refactoring on the test class.

A minor refactoring of the class WarehouseWorkerPoolTest

---

collector/pom.xml

当使用如下自定义配置时，Collector日志报出 EdDSA provider not supporte 错误，导致采集失败。
metrics:
- name: storage
priority: 0
fields:
- field: "total_storage"
type: 0
unit: 'MB'
- field: "data_used"
type: 0
unit: 'MB'
- field: "log_uesd"
type: 0
unit: 'MB'
- field: "usage"
type: 0
unit: '%'
aliasFields:
- total
- used
- pgdata
- pglog
calculates:
- total_storage=total
- data_used=pgdata-pglog
- log_uesd=pglog
- usage=(used / total) * 100
protocol: ssh
ssh:
host: ^_^host^_^
port: ^_^port^_^
username: ^_^username^_^
password: ^_^password^_^
timeout: ^_^timeout^_^
script: kubectl --token='^_^token^_^' --server="https://10.96.0.1" --insecure-skip-tls-verify exec -it deploy/^_^deployment^_^ -n ^_^namespace^_^ -- df -Tm | grep overlay | awk '{print $3}';kubectl --token='^_^token^_^' --server="https://10.96.0.1" …

Bugfix: EdDSA provider not supported

---

pom.xml

- Jupiter dependency is explicitly declared in the main pom file
- Set version of dependencies in the properties section
This PR is associated with this issue: https://github.com/dromara/hertzbeat/issues/666

Jupiter dependency is explicitly declared in the main pom file

---

collector/src/main/java/com/usthe/collector/collect/snmp/SnmpCollectImpl.java
manager/src/main/resources/define/app/app-windows.yml

[task]support more window metrics

---

collector/src/main/java/com/usthe/collector/collect/redis/RedisClusterCollectImpl.java
collector/src/main/java/com/usthe/collector/collect/redis/RedisCommonCollectImpl.java
common/src/main/java/com/usthe/common/util/MapCapUtil.java
common/src/main/java/com/usthe/common/util/SignConstants.java
manager/src/main/resources/application.yml
manager/src/main/resources/define/app-redis_cluster.yml

Each node information in the Redis cluster is displayed

[collect]Add redis cluster auto-discovery display metrics information

---

alerter/pom.xml
collector/pom.xml
warehouse/pom.xml

There are 1 security vulnerabilities found in org.apache.kafka:kafka-clients 3.0.0
- [CVE-2023-25194](https://www.oscs1024.com/hd/CVE-2023-25194)
Upgrade org.apache.kafka:kafka-clients from 3.0.0 to 3.4.0 for vulnerability fix

fix(sec): upgrade org.apache.kafka:kafka-clients to 3.4.0

---

collector/src/main/java/com/usthe/collector/collect/http/HttpCollectImpl.java
common/src/main/java/com/usthe/common/queue/impl/InMemoryCommonDataQueue.java
manager/src/main/java/com/usthe/manager/cache/CacheFactory.java
manager/src/main/java/com/usthe/manager/cache/CaffeineCacheServiceImpl.java
manager/src/main/java/com/usthe/manager/cache/ICacheService.java
manager/src/main/java/com/usthe/manager/component/alerter/impl/AbstractAlertNotifyHandlerImpl.java
manager/src/main/java/com/usthe/manager/component/alerter/impl/CommonRobotNotifyResp.java
manager/src/main/java/com/usthe/manager/component/alerter/impl/SlackAlertNotifyHandlerImpl.java
manager/src/main/java/com/usthe/manager/component/alerter/impl/TelegramBotAlertNotifyHandlerImpl.java
manager/src/main/java/com/usthe/manager/config/ThymeleafConfig.java
manager/src/main/java/com/usthe/manager/controller/MetricsController.java
manager/src/main/java/com/usthe/manager/support/exception/MonitorMetricsException.java
manager/src/main/resources/application.yml
manager/src/main/resources/define/app-hertzbeat.yml
manager/src/main/resources/define/app-hertzbeat_token.yml
manager/src/main/resources/define/app-springboot2.yml
manager/src/main/resources/sureness.yml
script/application.yml
script/docker-compose/hertzbeat-mysql-iotdb/conf/application.yml
script/docker-compose/hertzbeat-mysql-tdengine/conf/application.yml
warehouse/pom.xml
warehouse/src/main/java/com/usthe/warehouse/config/IotDbVersion.java
warehouse/src/main/java/com/usthe/warehouse/dao/HistoryDao.java
warehouse/src/main/java/com/usthe/warehouse/store/AbstractHistoryDataStorage.java
warehouse/src/main/java/com/usthe/warehouse/store/DataStorageDispatch.java
warehouse/src/main/java/com/usthe/warehouse/store/HistoryIotDbDataStorage.java
warehouse/src/main/java/com/usthe/warehouse/store/HistoryJpaDatabaseDataStorage.java
warehouse/src/main/java/com/usthe/warehouse/store/HistoryTdEngineDataStorage.java

add apache2 license on class

---

manager/src/main/resources/application.yml
warehouse/src/main/java/com/usthe/warehouse/config/WarehouseProperties.java
warehouse/src/main/java/com/usthe/warehouse/store/RealTimeRedisDataStorage.java

Modifying warehouse.store.redis.db in applicationyml can specify which database Redis should use.

[code]feature: Customize Redis DB

---

manager/src/main/resources/define/app-nacos.yml

add several monitors for nacos. #747

enhance nacos.yml

---

manager/src/main/resources/define/app-oracle.yml

更新修正表空间使用比例相关参数：原来的sql查sys.sm$ts_avail , sys.sm$ts_used , sys.sm$ts_free不能查出表空间used_max值，DBA_TABLESPACE_USAGE_METRICS才可以查出表空间used_max值，它的大小计算单位是block，1kb=8block，为了美观把block*8/1024转化为以MB单位。

update app-oracle.yml tablespace metrics

---

manager/src/main/java/com/usthe/manager/service/impl/AppServiceImpl.java
web-app/src/app/routes/monitor/monitor-data-chart/monitor-data-chart.component.ts

[模块：监控历史图表详情，bug修复，时间表达式格式： 小时h 天D 周W 月M 例如：7D表示7天，3M表示3个月](https://github.com/dromara/hertzbeat/commit/3cf8362db2b5bb78e0bd09cdf73760002b790c97)
[模块：manager，路径拼接多出“文件分隔符”](https://github.com/dromara/hertzbeat/commit/71a22f9f36cfa84fb0f1a793a66fb9e644206bb8)

bugfix historical chart time expression format error

---

manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/AppServiceImpl.java

Processing i18nName as null
Handling warning for idea

[refactor] avoid i18nName null

---

manager/src/main/java/org/dromara/hertzbeat/manager/controller/MonitorsController.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/MonitorServiceImpl.java

Improve MonitorServiceImpl.java related logic
change String Param verification in MonitorsController.java

Monitor service

---

manager/src/main/java/org/dromara/hertzbeat/manager/controller/MonitorsController.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/AppServiceImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/MonitorServiceImpl.java

use StringUtils.hasText() to judge String

[style] use StringUtils.hasText()

---

alerter/src/main/java/org/dromara/hertzbeat/alert/dao/AlertDao.java
home/i18n/zh-cn/docusaurus-plugin-content-docs/current/start/postgresql-change.md
home/sidebars.json

add postgresql-change zh-cn doc

[docs] add postgresql-change zh-cn doc

---

common/src/main/java/org/dromara/hertzbeat/common/entity/alerter/Alert.java
common/src/main/java/org/dromara/hertzbeat/common/entity/alerter/AlertDefine.java
common/src/main/java/org/dromara/hertzbeat/common/entity/manager/NoticeReceiver.java
common/src/main/java/org/dromara/hertzbeat/common/entity/manager/NoticeRule.java
common/src/main/java/org/dromara/hertzbeat/common/entity/manager/Param.java
common/src/main/java/org/dromara/hertzbeat/common/entity/manager/ParamDefine.java
common/src/main/java/org/dromara/hertzbeat/common/entity/manager/Tag.java

Issue : #870 set the special field string length when jpa auto ddl.
Changes Made:
1. Looked for all files in the repo containing @Table annotation and added @Column(length=2048) where applicable.
2. Observed `common/src/main/java/org/dromara/hertzbeat/common/entity/manager/NoticeReceiver.java` has many columns with @Length annotations with a max of 300, hence added the @Column annotation there as well with length of 300.

Added the @Column(length=2048) for special fields

---

manager/src/main/java/org/dromara/hertzbeat/manager/config/YamlMapperConfig.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/MonitorServiceImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/YamlImExportServiceImpl.java

tips:. The request parameter needs to use type:=YAML. todo:The front-end doesn't have an YAML version, and I hope someone can make it.
[manager]import and export by YAML via YamlImExportServiceImpl.java
tips:. The request parameter needs to use type:=YAML.
todo:The front-end doesn't have an YAML version, and I hope someone can make it.

[manager]import and export by YAML via YamlImExportServiceImpl.java

---

alerter/src/main/java/org/dromara/hertzbeat/alert/dao/AlertDefineBindDao.java
common/src/main/java/org/dromara/hertzbeat/common/entity/manager/Monitor.java
manager/src/main/java/org/dromara/hertzbeat/manager/dao/TagMonitorBindDao.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/MonitorServiceImpl.java
manager/src/test/java/org/dromara/hertzbeat/manager/service/MonitorServiceTest.java

bugfix associated label was incorrectly deleted when deleting a monitor

bugfix associated label was incorrectly deleted when deleting a monitor

---

manager/src/main/java/org/dromara/hertzbeat/manager/config/YamlMapperConfig.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/YamlImExportServiceImpl.java

[manager]use `snakeyaml` instead of `jakson` to export monitors.

[manager]use `snakeyaml` instead of `jackson` to export monitors.

---

manager/src/main/java/org/dromara/hertzbeat/manager/controller/MonitorsController.java
web-app/src/app/routes/monitor/monitor-edit/monitor-edit.component.html
web-app/src/app/routes/monitor/monitor-edit/monitor-edit.component.ts
web-app/src/app/routes/monitor/monitor-new/monitor-new.component.html
web-app/src/app/routes/monitor/monitor-new/monitor-new.component.ts

- bugfix monitoring host field can not custom define in ui
- change query monitoring list default sort field to `gmtCreate`

bugfix monitoring host field can not custom define in ui

---

alerter/src/main/java/org/dromara/hertzbeat/alert/calculate/CalculateAlarm.java
common/src/main/java/org/dromara/hertzbeat/common/util/JsonUtil.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/MonitorServiceImpl.java
script/sql/schema.sql

fix the textarea value judgment
change text value judgment

fix the textarea value judgment error

---

manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/DiscordBotAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/FlyBookAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/HuaweiCloudSmnAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/SlackAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/TelegramBotAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/WeChatAppAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/WeWorkRobotAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/WebHookAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/config/HeaderRequestInterceptor.java
manager/src/test/java/org/dromara/hertzbeat/manager/component/alerter/impl/HuaweiCloudSmnAlertNotifyHandlerImplTest.java

bugfix restTemplate change default content type application/json

bugfix restTemplate change default content type application/json

---

alerter/src/main/java/org/dromara/hertzbeat/alert/service/impl/AlertDefineServiceImpl.java
collector/src/main/java/org/dromara/hertzbeat/collector/util/CollectUtil.java
common/src/main/java/org/dromara/hertzbeat/common/entity/alerter/JsonMapAttributeConverter.java
common/src/main/java/org/dromara/hertzbeat/common/entity/manager/JsonByteListAttributeConverter.java
common/src/main/java/org/dromara/hertzbeat/common/entity/manager/JsonOptionListAttributeConverter.java
common/src/main/java/org/dromara/hertzbeat/common/entity/manager/JsonTagListAttributeConverter.java
common/src/main/java/org/dromara/hertzbeat/common/util/JsonUtil.java
home/docs/others/images-deploy.md
home/i18n/zh-cn/docusaurus-plugin-content-docs/current/others/images-deploy.md
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/MonitorServiceImpl.java
warehouse/pom.xml

fix JsonUtil TypeReference not config class type

fix JsonUtil TypeReference not config class type

---

web-app/src/app/core/i18n/i18n.service.spec.ts
web-app/src/app/core/i18n/i18n.service.ts
web-app/src/app/core/startup/startup.service.ts

bugfix can not auto change web i18n data when update app define template

[webapp] bugfix can not auto change i18n data

---

common/src/main/java/org/dromara/hertzbeat/common/entity/job/Job.java

org.dromara.hertzbeat.collector.dispatch.CommonDispatcher 244行
`metricsSet.forEach(metricItem -> {});`
和
org.dromara.hertzbeat.common.entity.job.Jon 211 行
` if (!metricsSet.remove(metrics)) {`
会出现并发错误。
迭代时出现异常，导致监控轮训任务终止。
`
java.util.ConcurrentModificationException: null
at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1510)
at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1533)
at java.base/java.lang.Iterable.forEach(Iterable.java:74)
at com.usthe.collector.dispatch.CommonDispatcher.dispatchCollectData(CommonDispatcher.java:244)
`
在Job的getNextCollectMetrics返回一个新的HashSet，避免出现这个问题。
该问题在监控Mysql服务的时候能稳定重现出现。

[collector] fix dispatch concurrency bug

---

common/src/main/java/org/dromara/hertzbeat/common/util/IpDomainUtil.java
common/src/test/java/org/dromara/hertzbeat/common/util/IpDomainUtilTest.java

The domain name validation tool has been improved to accommodate non-standard domain names within the intranet, allowing the use of underscore characters.

[common]bugfix: improve domain verification tools.

---

warehouse/src/main/java/org/dromara/hertzbeat/warehouse/store/HistoryTdEngineDataStorage.java

修复TDengine缺失第一个TS参数
Fix TDengine missing first TS parameter

bugfix TDengine missing first TS parameter

---

common/pom.xml
common/src/main/java/org/dromara/hertzbeat/common/queue/impl/KafkaCommonDataQueue.java
common/src/main/java/org/dromara/hertzbeat/common/serialize/AlertDeserializer.java
common/src/main/java/org/dromara/hertzbeat/common/serialize/AlertSerializer.java
common/src/main/java/org/dromara/hertzbeat/common/serialize/KafkaMetricsDataDeserializer.java
common/src/main/java/org/dromara/hertzbeat/common/serialize/KafkaMetricsDataSerializer.java
manager/src/main/resources/application-test.yml
manager/src/main/resources/application.yml

Added KafkaCommonQueue.java implements the CommonQueue interface;
Added serialization and deserialization classes required for Kafka transport

[common]feature:add kafka common queue

---

home/i18n/en/code.json
home/src/pages/components/DiaLog.js
home/src/pages/components/DiaLog.module.css
home/src/pages/components/LogoCarousel.js
home/src/pages/components/LogoCarousel.module.css
home/src/pages/components/Sponsor.module.css
home/src/pages/index.js

Fixed overflow issues, alignment issues and typos in : 
- Sponors Section 
- Dialog (Support HertzBeat)
- Friends Links
##Before the PR 
##After the PR is merged
Also Fixed some typos and spell errors here and there, as I found them.

Fixed overflow and alignment issues on homepage 

---

home/src/pages/components/LogoCarousel.js

The Logo and Dromara Friends Carousel was breaking for mobile and tablet devices. check https://hertzbeat.com/
I made the nesccessary changes to make the carousel responsive. 
[Screencast from 21-05-23 02:08:48 PM IST.webm](https://github.com/dromara/hertzbeat/assets/100678386/f1814fbf-f190-4d32-a157-ad0d54838bdb)

Fixed Carousel Overflow on homepage and made it responsive

---

script/docker/server/Dockerfile

I added he sshd server when building the hertzbeat docker image. For issue "#982"

add sshd server when build hertzbeat docker image

---

manager/src/main/java/org/dromara/hertzbeat/manager/pojo/dto/WeWorkWebHookDto.java

解决企业微信机器人消息类型仅支持小写，大写企微会报错，返回    "errcode": 40008

Failed to fix the WeWork Robot sending messages

---

manager/src/main/resources/application.yml
warehouse/src/main/java/org/dromara/hertzbeat/warehouse/config/WarehouseProperties.java
warehouse/src/main/java/org/dromara/hertzbeat/warehouse/dao/HistoryDao.java
warehouse/src/main/java/org/dromara/hertzbeat/warehouse/store/HistoryJpaDatabaseDataStorage.java

support configuring the maximum retention count of history records for JPA. 
#980

[manager]feature: support configuring the maximum retention count of history records for JPA

---

manager/src/main/resources/define/app-api.yml

[manager] feature: modify app-api.yml

---

alerter/src/main/java/org/dromara/hertzbeat/alert/calculate/CalculateAlarm.java
alerter/src/main/java/org/dromara/hertzbeat/alert/calculate/SilenceAlarm.java
alerter/src/main/java/org/dromara/hertzbeat/alert/service/impl/AlertServiceImpl.java
common/src/main/java/org/dromara/hertzbeat/common/config/CommonProperties.java
common/src/main/java/org/dromara/hertzbeat/common/queue/CommonDataQueue.java
common/src/main/java/org/dromara/hertzbeat/common/queue/impl/InMemoryCommonDataQueue.java
common/src/main/java/org/dromara/hertzbeat/common/queue/impl/KafkaCommonDataQueue.java
common/src/main/java/org/dromara/hertzbeat/common/serialize/AlertDeserializer.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/DispatcherAlarm.java
manager/src/main/resources/application-test.yml
manager/src/main/resources/application.yml
script/application.yml
warehouse/src/main/java/org/dromara/hertzbeat/warehouse/store/DataStorageDispatch.java

refactor common kafka data queue

refactor common kafka data queue 

---

.github/workflows/build-pdf.yml
.github/workflows/doc-pdf-builder.yml
home/docs/help/hadoop.md
home/sidebars.json

add github action that auto build hertzbeat docs pdf

add github action that auto build hertzbeat docs pdf 

---

README.md
README_CN.md
home/docs/start/docker-deploy.md
home/docs/start/quickstart.md
home/i18n/zh-cn/docusaurus-plugin-content-docs/current/start/docker-deploy.md
home/i18n/zh-cn/docusaurus-plugin-content-docs/current/start/quickstart.md
script/docker-compose/hertzbeat-mysql-iotdb/conf/sureness.yml
script/docker-compose/hertzbeat-mysql-tdengine/conf/sureness.yml
script/docker-compose/hertzbeat-postgresql-iotdb/conf/sureness.yml

support quay.io as hertzbeat docker images repository
due dockerhub network timeout 
https://quay.io/repository/tancloud/hertzbeat?tab=info

support quay.io as hertzbeat docker images repository

---

home/i18n/zh-cn/docusaurus-plugin-content-docs/current/start/mysql-change.md

```yml
spring:
jpa:
hibernate:
ddl-auto: update 
properties:
dialect: org.hibernate.dialect.MySQL5InnoDBDialect 
```
改为
```yml
jpa:
hibernate:
ddl-auto: update
properties:
hibernate:
dialect: org.hibernate.dialect.MySQL5InnoDBDialect
```

修改mysql连接，HibernateException异常解决方法

---

collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/MetricsCollect.java

replace "\#" by "#" when extract expression to support Aviator calculates

 replace "\#" by "#"

---

manager/src/main/resources/define/app-linux.yml

bugfix linux shell echo field value is too long and causes a line break

---

collector/src/main/java/org/dromara/hertzbeat/collector/collect/http/HttpCollectImpl.java

【移除 requestBuilder在添加params的时候使用的replaceUriSpecialChar功能，因为replaceUriSpecialChar导致params错误】

remove auto replace uri special char in http request params

---

manager/src/main/resources/define/app-elasticsearch.yml

remove elasticsearch unused param index

---

web-app/src/app/routes/dashboard/dashboard.component.html

bugfix update dashboard alerts cards height not consist

bugfix update dashboard alerts cards height not consist

---

web-app/src/app/routes/alert/alert-setting/alert-setting.component.html

update alert rule operator display "<=" to ">="

---

alerter/src/test/java/org/dromara/hertzbeat/alert/service/AlertDefineServiceTest.java
common/src/main/java/org/dromara/hertzbeat/common/config/AviatorConfiguration.java
common/src/test/java/org/dromara/hertzbeat/common/config/AviatorConfigurationTest.java

Implemented custom functions to support alert threshold computation:
- `contains(str1,str2)`
- `exists("keyName")`
- `matches(str,"regex")`

feat: aviator fn for str contains, exists & matches

---

alerter/src/main/java/org/dromara/hertzbeat/alert/reduce/AlarmCommonReduce.java

bugfix common alarm do not need monitorId tag existed

bugfix common alarm do not need monitorId tag existed

---

home/docs/help/spark.md
manager/src/main/resources/define/app-spark.yml

feature: support apache spark metrics monitoring

---

manager/src/main/java/org/dromara/hertzbeat/manager/controller/MonitorsController.java

Fix bugs that cannot query minotrs when tagValue is null

[manager] fix: can query by tags when tagValue is null

---

collector/src/main/java/org/dromara/hertzbeat/collector/collect/http/HttpCollectImpl.java

feature:monitor brearer token api, ignore letter case to comparison
change: Monitor the configured interface to determine whether to write the bearer token value in the header, where app hertzbeat is required_ Compare the type configuration value in the HTTP authorization in token. yml with the default value of backend dispatchConstants. This modification is to ignore case in this comparison to avoid typing in the yml file that does not conform to the initial uppercase format and cannot match

feature:monitor brearer token api, ignore letter case to comparison

---

collector/pom.xml
collector/src/main/java/org/dromara/hertzbeat/collector/collect/database/JdbcCommonCollect.java
common/src/main/java/org/dromara/hertzbeat/common/entity/job/protocol/JdbcProtocol.java

support run sql script file in jdbc protocol config
```
queryType: runScript
sql: /opt/xxx/demo.sql
```
in
```
jdbc:
host: ^_^host^_^
port: ^_^port^_^
platform: mysql
username: ^_^username^_^
password: ^_^password^_^
database: ^_^database^_^
timeout: ^_^timeout^_^
queryType: runScript
sql: /opt/xxx/demo.sql
url: ^_^url^_^
```

support run sql script file in jdbc protocol config

---

manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/AppServiceImpl.java

bugfix can not startup when error monitoring template yml file
Ignore parse error monitoring template yml file

bugfix can not startup when error monitoring template yml file

---

manager/src/main/java/org/dromara/hertzbeat/manager/service/TagService.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/MonitorServiceImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/TagServiceImpl.java
manager/src/test/java/org/dromara/hertzbeat/manager/service/MonitorServiceTest.java

tags also deleted when the monitor is deleted

---

manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/AbstractImExportServiceImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/ExcelImExportServiceImpl.java

What's changed?
#1174
When importing and exporting monitoring, support export collectors, configure collectors when importing

[bug fixed]When importing and exporting monitoring, support export collectors, configure collectors when importing

---

CONTRIBUTING.md

replace obsolete `registry.npm.taobao.org` to`registry.npmmirror.com`

replace obsolete `registry.npm.taobao.org` to`registry.npmmirror.com`

---

web-app/src/app/shared/components/help-massage-show/help-massage-show.component.html
web-app/src/app/shared/components/help-massage-show/help-massage-show.component.ts
web-app/src/assets/i18n/en-US.json
web-app/src/assets/i18n/zh-CN.json

Bugfix: added i18n to expand-collapse button

Help component update

---

manager/src/main/resources/define/app-ping.yml

add app-ping i18n

---

alerter/src/main/java/org/dromara/hertzbeat/alert/calculate/CalculateAlarm.java
collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/CommonDispatcher.java
collector/src/main/java/org/dromara/hertzbeat/collector/util/CollectUtil.java
common/pom.xml
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/WeChatAppAlertNotifyHandlerImpl.java
pom.xml

  some codes opt

---

manager/src/main/resources/define/app-api.yml

https://github.com/dromara/hertzbeat/issues/1212

add app-api i18n

---

alerter/src/main/java/org/dromara/hertzbeat/alert/controller/AlertDefinesController.java
web-app/src/app/routes/alert/alert-setting/alert-setting.component.html
web-app/src/app/routes/alert/alert-setting/alert-setting.component.ts
web-app/src/app/service/alert-define.service.ts

Add `getAlertDefinesByName`.
#1230

[feature]Add `getAlertDefinesByName`.

---

common/src/main/java/org/dromara/hertzbeat/common/config/AviatorConfiguration.java
common/src/test/java/org/dromara/hertzbeat/common/config/AviatorConfigurationTest.java

Fixed AviatorScript expression injection RCE issues:
- Disabled Feature.Module
- Disabled Feature.NewInstance
- Minimized feature set

fix: expression injection RCE

---

alerter/src/main/java/org/dromara/hertzbeat/alert/controller/AlertConvergeController.java
alerter/src/main/java/org/dromara/hertzbeat/alert/controller/AlertConvergesController.java
alerter/src/main/java/org/dromara/hertzbeat/alert/controller/AlertDefineController.java
alerter/src/main/java/org/dromara/hertzbeat/alert/controller/AlertDefinesController.java
alerter/src/main/java/org/dromara/hertzbeat/alert/controller/AlertReportController.java
alerter/src/main/java/org/dromara/hertzbeat/alert/controller/AlertSilenceController.java
alerter/src/main/java/org/dromara/hertzbeat/alert/controller/AlertSilencesController.java
alerter/src/main/java/org/dromara/hertzbeat/alert/controller/AlertsController.java
common/src/main/java/org/dromara/hertzbeat/common/entity/dto/Message.java
manager/src/main/java/org/dromara/hertzbeat/manager/controller/AccountController.java
manager/src/main/java/org/dromara/hertzbeat/manager/controller/AppController.java
manager/src/main/java/org/dromara/hertzbeat/manager/controller/CollectorController.java
manager/src/main/java/org/dromara/hertzbeat/manager/controller/GeneralConfigController.java
manager/src/main/java/org/dromara/hertzbeat/manager/controller/I18nController.java
manager/src/main/java/org/dromara/hertzbeat/manager/controller/MetricsController.java
manager/src/main/java/org/dromara/hertzbeat/manager/controller/MonitorController.java
manager/src/main/java/org/dromara/hertzbeat/manager/controller/MonitorsController.java
manager/src/main/java/org/dromara/hertzbeat/manager/controller/NoticeConfigController.java
manager/src/main/java/org/dromara/hertzbeat/manager/controller/SummaryController.java
manager/src/main/java/org/dromara/hertzbeat/manager/controller/TagController.java
manager/src/main/java/org/dromara/hertzbeat/manager/pojo/dto/WeWorkWebHookDto.java
manager/src/main/java/org/dromara/hertzbeat/manager/support/GlobalExceptionHandler.java
warehouse/src/main/java/org/dromara/hertzbeat/warehouse/controller/MetricsDataController.java

- Use static methods instead of constructors for `Message.java`
- Use `A.isEmpty()` instead of `"".equals(A)`

[Refactor] Use static methods instead of constructors for Message.java

---

manager/src/main/java/org/dromara/hertzbeat/manager/controller/AppController.java
pom.xml

bugfix snake yaml decode rce - malicious remote script

bugfix snake yaml decode rce

---

collector/src/main/java/org/dromara/hertzbeat/collector/collect/mongodb/MongodbSingleCollectImpl.java

bugfix mongodb collect extra metrics npe
see https://gitee.com/dromara/hertzbeat/issues/I82OMS

bugfix mongodb collect extra metrics npe

---

collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/entrance/processor/GoCloseProcessor.java
collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/entrance/processor/GoOfflineProcessor.java
common/src/main/java/org/dromara/hertzbeat/common/constants/CommonConstants.java

bugfix fix collector run cyclic when connect auth failed

---

collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/entrance/CollectServer.java
manager/src/main/java/org/dromara/hertzbeat/manager/scheduler/SchedulerProperties.java
manager/src/main/java/org/dromara/hertzbeat/manager/scheduler/netty/ManageServer.java
manager/src/main/java/org/dromara/hertzbeat/manager/scheduler/netty/process/CollectorOnlineProcessor.java
manager/src/main/java/org/dromara/hertzbeat/manager/scheduler/netty/process/HeartbeatProcessor.java
remoting/src/main/java/org/dromara/hertzbeat/remoting/netty/NettyRemotingServer.java
remoting/src/main/java/org/dromara/hertzbeat/remoting/netty/NettyServerConfig.java

bugfix collector can not auto reconnect when channel idle

bugfix collector can not auto reconnect when channel idle

---

common/src/main/java/org/dromara/hertzbeat/common/queue/impl/KafkaCommonDataQueue.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/WeWorkAppAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/pojo/dto/WeChatAppDTO.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/MonitorServiceImpl.java
manager/src/main/resources/templates/alertNotifyWeWorkApp.txt
manager/src/test/java/org/dromara/hertzbeat/manager/component/alerter/impl/WeChatAppAlertNotifyHandlerImplTest.java

update alarm notice wework app send content ui

update alarm notice wework app send content ui

---

manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/DbAlertStoreHandlerImpl.java

bugfix old version monitor alert has no monitor name
fix https://gitee.com/dromara/hertzbeat/issues/I7ZDSM#note_21831511

bugfix old version monitor alert has no monitor name

---

alerter/src/main/java/org/dromara/hertzbeat/alert/calculate/CalculateAlarm.java
alerter/src/main/java/org/dromara/hertzbeat/alert/reduce/AlarmConvergeReduce.java
common/src/main/java/org/dromara/hertzbeat/common/constants/CommonConstants.java

reset alert converge reduce cache when restored alert trigger
fix https://github.com/dromara/hertzbeat/issues/1277

reset alert converge reduce cache when restored alert trigger

---

alerter/src/main/java/org/dromara/hertzbeat/alert/dao/AlertDefineDao.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/DispatcherAlarm.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/AbstractAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/AvailableAlertDefineInit.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/NoticeConfigService.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/NoticeConfigServiceImpl.java
manager/src/test/java/org/dromara/hertzbeat/manager/service/NoticeConfigServiceTest.java

bugfix AvailableAlertDefineInit - query did not return a unique result

---

home/docs/help/issue.md
home/docs/help/ping.md
home/docs/start/upgrade.md
home/docusaurus.config.js
home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/issue.md
home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/ping.md
home/i18n/zh-cn/docusaurus-plugin-content-docs/current/start/upgrade.md
web-app/src/app/layout/basic/widgets/user.component.ts
web-app/src/assets/i18n/en-US.json
web-app/src/assets/i18n/zh-CN.json
web-app/src/assets/i18n/zh-TW.json

- update hertzbeat upgrade help doc
- add upgrade guide icon in webui

update hertzbeat upgrade help doc

---

remoting/src/main/java/org/dromara/hertzbeat/remoting/RemotingService.java
remoting/src/main/java/org/dromara/hertzbeat/remoting/netty/NettyRemotingClient.java
remoting/src/main/java/org/dromara/hertzbeat/remoting/netty/NettyRemotingServer.java
remoting/src/test/java/org/dromara/hertzbeat/remoting/RemotingServiceTest.java

update the test waiting for server and client start 

---

web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html
web-app/src/assets/i18n/en-US.json
web-app/src/assets/i18n/zh-CN.json
web-app/src/assets/i18n/zh-TW.json

add an explicit tag filter. 
This may help users notice the tag filter feature more easily.
from issue #776 which I forgot about half a year ago.

add an explicit tag filter

---

home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/kafka.md

[doc] update kafka help doc

---

warehouse/pom.xml
warehouse/src/main/java/org/dromara/hertzbeat/warehouse/store/HistoryGrepTimeDbDataStorage.java

upgrade greptimedb to v0.4

---

alerter/src/main/java/org/dromara/hertzbeat/alert/reduce/AlarmSilenceReduce.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/AppServiceImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/NoticeConfigServiceImpl.java

bugfix alarm time span match in silence and notice

bugfix alarm time span match in silence and notice

---

alerter/src/main/java/org/dromara/hertzbeat/alert/calculate/CalculateAlarm.java
collector/src/test/java/org/dromara/hertzbeat/collector/collect/telnet/TelnetCollectImplTest.java
common/src/main/java/org/dromara/hertzbeat/common/entity/manager/NoticeTemplate.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/WebHookAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/MonitorServiceImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/NoticeConfigServiceImpl.java

- bugfix webhook post body error
- bugfix unhealth monitors's alarm recover exception when restart

bugfix webhook post body error and alarm recover exception

---

home/blog/2022-07-10-hertzbeat-v1.1.1.md
home/blog/2023-11-12-hertzbeat-v1.4.2.md
home/docs/advanced/extend-http-example-hertzbeat.md
home/docs/advanced/extend-http-example-token.md
home/docs/advanced/extend-tutorial.md
home/docusaurus.config.js
home/i18n/en/code.json
home/i18n/en/docusaurus-plugin-content-docs/version-v1.1.x/advanced/extend-http-example-hertzbeat.md
home/i18n/en/docusaurus-plugin-content-docs/version-v1.1.x/advanced/extend-http-example-token.md
home/i18n/en/docusaurus-plugin-content-docs/version-v1.1.x/advanced/extend-tutorial.md
home/i18n/zh-cn/code.json
home/i18n/zh-cn/docusaurus-plugin-content-blog/2023-11-12-hertzbeat-v1.4.2.md
home/src/pages/components/DiaLog.js
home/src/pages/index.js
home/versioned_docs/version-v1.3.x/advanced/extend-http-example-hertzbeat.md
home/versioned_docs/version-v1.3.x/advanced/extend-http-example-token.md
home/versioned_docs/version-v1.3.x/advanced/extend-tutorial.md
manager/src/main/java/org/dromara/hertzbeat/manager/dao/CollectorMonitorBindDao.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/MonitorServiceImpl.java
script/docker/collector/build.sh

bugfix duplicate collect job when update monitor templates
fixes #1269 #1134 
add 1.4.2 release doc

bugfix duplicate collect job when update monitor templates

---

script/docker-compose/hertzbeat-mysql-tdengine/README.md
script/docker-compose/hertzbeat-mysql-tdengine/README_CN.md

update hertzbeat-mysql-tdengine readme

[doc] update hertzbeat-mysql-tdengine readme

---

warehouse/src/main/java/org/dromara/hertzbeat/warehouse/store/HistoryTdEngineDataStorage.java

bugfix tdengine query interval history metrics data with instance error
close https://github.com/dromara/hertzbeat/issues/1331

bugfix tdengine query interval history metrics data with instance error

---

common/src/main/java/org/dromara/hertzbeat/common/entity/alerter/Alert.java

delete  violation of column content
org.dromara.hertzbeat.common.entity.alerter.Alert[content]

unlimit Alert.java content field length

---

web-app/src/app/routes/monitor/monitor-data-chart/monitor-data-chart.component.html
web-app/src/app/routes/monitor/monitor-data-table/monitor-data-table.component.html
web-app/src/app/routes/monitor/monitor-detail/monitor-detail.component.html
web-app/src/assets/i18n/en-US.json
web-app/src/assets/i18n/zh-CN.json
web-app/src/assets/i18n/zh-TW.json

update monitor detail table ui layout

update monitor detail table ui layout

---

CONTRIBUTING.md

I tried to install yarn, but it seems required node.js version >= 18
Therefore I modify `Getting HertzBeat up and running` in CONTRIBUTING.md

Error occured when I followed running steps to start Front-web

---

collector/src/test/java/org/dromara/hertzbeat/collector/util/CollectUtilTest.java

Use JSON_MAPPER.readTree() to compare two JSON strings instead of direct assertion to fix a flaky test
**Flaky test case:**  ```org.dromara.hertzbeat.collector.util.CollectUtilTest.replaceCryPlaceholder```
https://github.com/dromara/hertzbeat/blob/ce75254b8ec18422c48c40fe61354135d08b200d/collector/src/test/java/org/dromara/hertzbeat/collector/util/CollectUtilTest.java#L82
Test ```replaceCryPlaceholder``` in ```CollectUtilTest``` is detected as flaky with the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool. The test failed with the following error:
```
[ERROR] Failures: 
[ERROR]   CollectUtilTest.replaceCryPlaceholder:98 expected: <{"visible":false,"name":"张三"}> but was: <{"name":"张三","visible":false}>
[ERROR] Failures: 
[ERROR]   CollectUtilTest.replaceCryPlaceholder:111 …
```

Fix flaky test in CollectUtilTest

---

collector/src/test/java/org/dromara/hertzbeat/collector/util/CollectUtilTest.java

Use JSON_MAPPER.readTree() to compare two JSON strings instead of direct assertion to fix a flaky test
**Flaky test case:**  ```org.dromara.hertzbeat.collector.util.CollectUtilTest.replaceSmilingPlaceholder```
https://github.com/dromara/hertzbeat/blob/7f131a179089a3a7fdd530913826c0c28e0cb5fb/collector/src/test/java/org/dromara/hertzbeat/collector/util/CollectUtilTest.java#L114
Test ```replaceSmilingPlaceholder``` in ```CollectUtilTest``` is detected as flaky with the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool. The test failed with the following error:
```
[ERROR] Failures: 
[ERROR]   CollectUtilTest.replaceSmilingPlaceholder:123 expected: <{"visible":false,"name":"张三"}> but was: <{"name":"张三","visible":false}>
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, …
```

Fix flaky test replaceSmilingPlaceholder

---

alerter/src/main/java/org/dromara/hertzbeat/alert/util/AlertTemplateUtil.java
alerter/src/test/java/org/dromara/hertzbeat/alert/util/AlertTemplateUtilTest.java

1. fix (https://github.com/dromara/hertzbeat/issues/1355)
2. `Matcher.quoteReplacement(value)`会返回所有的$字符和\字符转义后的字符串，原本的`matcher.appendReplacement(buffer, value);` 将value字符串直接作为替换文本，蛋value中包含了正则表达式的引用符号（比如$1, $2等表示捕获组的内容），或者有反斜线\（用于转义的），它们将被Matcher类处理为特殊的元字符。这可能导致Illegal group reference错误
3. 此外并且没有高并发情况把StringBuffer修改为StringBuilder。
4. 增加测试用例，并且测试用例已经通过。

fix exception when sending email has special chars

---

collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/entrance/processor/GoCloseProcessor.java
collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/entrance/processor/GoOfflineProcessor.java
manager/src/main/java/org/dromara/hertzbeat/manager/scheduler/SchedulerInit.java
manager/src/main/resources/define/app-api_code.yml
manager/src/main/resources/define/app-windows.yml
web-app/src/app/routes/monitor/monitor-edit/monitor-edit.component.html
web-app/src/app/routes/monitor/monitor-new/monitor-new.component.html
web-app/src/app/routes/monitor/monitor-new/monitor-new.component.ts
web-app/src/app/shared/components/help-massage-show/help-massage-show.component.less

- bugfix auto generate monitor name error when add monitor
- update api-code monitor metrics name
- update help-message-ui

bugfix auto generate monitor name error when add monitor

---

e2e/data/monitor-ftp.json
e2e/data/monitor-ping.json
e2e/data/monitor-port.json
e2e/data/monitor-sitemap.json
e2e/data/monitor-ssl.json
e2e/data/monitor-udp.json
e2e/data/monitor-website.json
e2e/testsuite.yaml

test: add more monitor related e2e testing case

---

.github/workflows/backend-build-test.yml
.github/workflows/doc-pdf-builder.yml
.github/workflows/frontend-build-test.yml
.github/workflows/issues-translator.yml
script/assembly/collector/assembly.xml
script/assembly/server/assembly.xml
script/docker/collector/build.sh
script/docker/server/Dockerfile
script/helm/hertzbeat/Chart.yaml
web-app/src/app/routes/monitor/monitor-edit/monitor-edit.component.html
web-app/src/app/routes/monitor/monitor-new/monitor-new.component.html
web-app/src/app/shared/constants.ts

[hertzbeat] release hertzbeat version v1.4.3

---

collector/src/main/java/org/dromara/hertzbeat/collector/collect/ssh/SshCollectImpl.java

support new parse type 'log' in ssh collect protocol
how to use 
```
- name: log
priority: 6
fields:
- field: error_log
type: 1
protocol: ssh
ssh:
host: ^_^host^_^
port: ^_^port^_^
username: ^_^username^_^
password: ^_^password^_^
privateKey: ^_^privateKey^_^
timeout: ^_^timeout^_^
reuseConnection: ^_^reuseConnection^_^
script: tail -f -n 10 xxx.log
parseType: log
```

support new parse type 'log' in ssh collect protocol

---

web-app/src/app/pojo/Tag.ts

Whenever we add a new tag from a the Tag Management, a random color will be given by default to that Tag

[Task-1386] When adding tags in tag management, random colors are given by default.

---

collector/src/main/java/org/dromara/hertzbeat/collector/collect/nginx/NginxCollectImpl.java
collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/DispatchConstants.java
collector/src/main/resources/META-INF/services/org.dromara.hertzbeat.collector.collect.AbstractCollect
collector/src/test/java/org/dromara/hertzbeat/collector/collect/nginx/NginxCollectImplTest.java
common/src/main/java/org/dromara/hertzbeat/common/entity/job/Metrics.java
common/src/main/java/org/dromara/hertzbeat/common/entity/job/protocol/NginxProtocol.java
home/docs/help/nginx.md
manager/src/main/resources/define/app-nginx.yml

[support monitoring nginx metrics](https://github.com/dromara/hertzbeat/issues/1360)
- [✅]  I hereby agree to the terms of the [HertzBeat CLA](https://gist.github.com/tomsun28/511c04e7643901cb550bb6ecc75a661b)
- [✅]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [✅]  I have written the necessary doc or comment.
- [✅]  I have added the necessary unit tests and all cases have passed.
- [✅] I have added the necessary [e2e tests](../e2e) and all cases have passed.

feature: support monitoring nginx metrics and add a help doc

---

collector/src/main/java/org/dromara/hertzbeat/collector/collect/http/HttpCollectImpl.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/prometheus/PrometheusAutoCollectImpl.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/prometheus/parser/MetricFamily.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/prometheus/parser/TextParser.java

update parser to parse from prometheus txt metrics data

---

collector/src/main/java/org/dromara/hertzbeat/collector/collect/common/ssh/CommonSshClient.java

support all ssh connect key exchange
fix: Unable to negotiate key exchange for KEX algorithms (client: ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256,diffie-hellman-group18-sha512,diffie-hellman-group17-sha512,diffie-hellman-group16-sha512,diffie-hellman-group15-sha512,diffie-hellman-group14-sha256 / server: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1)
/close https://github.com/dromara/hertzbeat/issues/1375

support all ssh connect key exchange

---

collector/src/main/java/org/dromara/hertzbeat/collector/collect/pop3/Pop3CollectImpl.java
collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/DispatchConstants.java
collector/src/main/resources/META-INF/services/org.dromara.hertzbeat.collector.collect.AbstractCollect
common/src/main/java/org/dromara/hertzbeat/common/entity/job/Metrics.java
common/src/main/java/org/dromara/hertzbeat/common/entity/job/protocol/Pop3Protocol.java
home/docs/help/nginx.md
home/docs/help/pop3.md
manager/src/main/resources/define/app-pop3.yml

[support pop3](https://github.com/dromara/hertzbeat/issues/1394)
- [✅]  I hereby agree to the terms of the [HertzBeat CLA](https://gist.github.com/tomsun28/511c04e7643901cb550bb6ecc75a661b)
- [✅]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [✅]  I have written the necessary doc or comment.
- [✅]  I have added the necessary unit tests and all cases have passed.
- [✅] I have added the necessary [e2e tests](../e2e) and all cases have passed.

feature: support monitoring pop3 metrics and add help doc

---

manager/src/main/resources/define/app-rabbitmq.yml

app-rabbitmq.yml support for international name aliases

---

collector/src/main/java/org/dromara/hertzbeat/collector/collect/common/cache/CommonCache.java

error create lru-cache-timeout-cleaner thread

fix(*): error create lru-cache-timeout-cleaner thread

---

collector/src/main/java/org/dromara/hertzbeat/collector/collect/nginx/NginxCollectImpl.java

Fix Nginx Collect validateParams function NPE

Fix Nginx Collect validateParams function NPE

---

manager/src/main/resources/define/app-docker.yml
manager/src/main/resources/define/app-springboot3.yml

feat: add metrics i18n for app-docker.yml

feat: add metrics i18n for app-docker.yml

---

manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/MonitorServiceImpl.java

取消监控cancelManageMonitors方法：删除设置jobId为空。否则取消监控后，无法删除该监控项。
jobId保留可以等待下次开启监控时复用该jobId，不影响其他功能。

bugfix delete monitor error after monitor canceled

---

warehouse/src/main/java/org/dromara/hertzbeat/warehouse/store/HistoryVictoriaMetricsDataStorage.java

bugfix history range query not work when victoria-metrics store

---

web-app/src/app/routes/alert/alert-notice/alert-notice.component.html

bugfix telegram-notice can not input bot-token

---

alerter/src/main/java/org/dromara/hertzbeat/alert/calculate/CalculateAlarm.java
web-app/src/assets/i18n/zh-CN.json
web-app/src/assets/i18n/zh-TW.json

bugfix alarm trigger-times not work when alarm and recovered trigger cyclically

bugfix alarm trigger-times not work when alarm and recovered trigger cyclically

---

README.md
collector/src/main/java/org/dromara/hertzbeat/collector/collect/snmp/SnmpCollectImpl.java
common/src/main/java/org/dromara/hertzbeat/common/entity/job/protocol/SnmpProtocol.java
home/blog/2023-12-11-hertzbeat-v1.4.3.md
home/docs/introduce.md

Added contextname judgment method and removed the default value of contextName field
fixed: snmpv3 contextName bug

fixed: snmpv3 contextName bug

---

collector/src/main/java/org/dromara/hertzbeat/collector/collect/http/HttpCollectImpl.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/nginx/NginxCollectImpl.java

due not close the http response or `request.abort()` to returen the connection to http pool, http client pool may casue the dead lock
[stack.log](https://github.com/dromara/hertzbeat/files/13863191/stack.log)

bugfix nginx collect http deadlock error

---

alerter/src/main/java/org/dromara/hertzbeat/alert/calculate/CalculateAlarm.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/udp/UdpCollectImpl.java
collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/timer/TimerDispatcher.java
common/src/main/java/org/dromara/hertzbeat/common/constants/CommonConstants.java
warehouse/src/main/java/org/dromara/hertzbeat/warehouse/store/RealTimeRedisDataStorage.java

alarm calculate ignore metrics collect code - TIMEOUT

---

web-app/src/app/routes/monitor/monitor-list/monitor-list.component.ts
web-app/src/app/service/monitor.service.ts

I've added a new function, changeMonitorTable, so that it can be paginated after search and still carry parameters.

bugfix: search monitors error when pageable #1470

---

collector/src/main/java/org/dromara/hertzbeat/collector/collect/mongodb/MongodbSingleCollectImpl.java
collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/CommonDispatcher.java
collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/WorkerPool.java
collector/src/main/resources/application.yml

bugfix mongodb collect cause system thread oom
[stack.txt](https://github.com/dromara/hertzbeat/files/13936115/stack.txt)

bugfix mongodb collect cause system thread oom

---

alerter/src/main/java/org/dromara/hertzbeat/alert/calculate/CalculateAlarm.java

bugfix prometheus type metrics threshold alarm not work

bugfix prometheus type metrics threshold alarm not work

---

manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/AbstractImExportServiceImpl.java

bugfix exportMonitor.monitor.tags npe 

---

manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/AbstractAlertNotifyHandlerImpl.java
manager/src/main/resources/templates/2-WebhookTemplate.txt
manager/src/test/java/org/dromara/hertzbeat/manager/service/NoticeConfigServiceTest.java

fixes #1503
* 具体做法是在2-WebhookTemplate中如果属性为null直接不展示
* 并且其他两个类只是多删除了回撤换行

bugfix webhook notice error

---

alerter/src/main/java/org/dromara/hertzbeat/alert/service/impl/AlertDefineExcelImExportServiceImpl.java
common/src/test/java/org/dromara/hertzbeat/common/util/JsonUtilTest.java

Alert define export tags combine

Alert define export tags combine

---

alerter/src/main/resources/alerter_en_US.properties
alerter/src/main/resources/alerter_zh_CN.properties
common/src/main/java/org/dromara/hertzbeat/common/constants/CommonConstants.java
common/src/main/java/org/dromara/hertzbeat/common/entity/manager/NoticeTemplate.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/AbstractAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/DbAlertStoreHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/MailServiceImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/NoticeConfigServiceImpl.java
manager/src/main/resources/templates/1-EmailTemplate.html
manager/src/main/resources/templates/10-WeWorkAppTemplate.txt
manager/src/main/resources/templates/11-HuaweiCloudSmnTemplate.txt
manager/src/main/resources/templates/12-ServerChanTemplate.txt
manager/src/main/resources/templates/4-WeWorkRobotTemplate.txt
manager/src/main/resources/templates/5-DingTalkRobotTemplate.txt
manager/src/main/resources/templates/6-FlyBookRobotTemplate.txt
manager/src/main/resources/templates/7-TelegramBotTemplate.txt
manager/src/main/resources/templates/8-SlackTemplate.txt
manager/src/main/resources/templates/9-DiscordBotTemplate.txt
manager/src/test/java/org/dromara/hertzbeat/manager/component/alerter/impl/DingTalkRobotAlertNotifyHandlerImplTest.java
manager/src/test/java/org/dromara/hertzbeat/manager/component/alerter/impl/DiscordBotAlertNotifyHandlerImplTest.java
manager/src/test/java/org/dromara/hertzbeat/manager/component/alerter/impl/FlyBookAlertNotifyHandlerImplTest.java
manager/src/test/java/org/dromara/hertzbeat/manager/component/alerter/impl/HuaweiCloudSmnAlertNotifyHandlerImplTest.java
manager/src/test/java/org/dromara/hertzbeat/manager/component/alerter/impl/SlackAlertNotifyHandlerImplTest.java
manager/src/test/java/org/dromara/hertzbeat/manager/component/alerter/impl/TelegramBotAlertNotifyHandlerImplTest.java
manager/src/test/java/org/dromara/hertzbeat/manager/component/alerter/impl/WeChatAppAlertNotifyHandlerImplTest.java
manager/src/test/java/org/dromara/hertzbeat/manager/component/alerter/impl/WeWorkRobotAlertNotifyHandlerImplTest.java

alert notice add monitor host

---

common/src/main/java/org/dromara/hertzbeat/common/entity/alerter/Alert.java
common/src/main/java/org/dromara/hertzbeat/common/entity/warehouse/History.java
common/src/main/java/org/dromara/hertzbeat/common/util/SnowFlakeIdGenerator.java

if id assigned,use it, otherwise use a snowflake id.

snowflake id

---

home/CNAME
home/docs/help/nginx.md
home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/nginx.md
web-app/src/app/routes/status-public/status-public.component.ts

update nginx monitoring help doc

---

script/checkstyle/checkstyle.xml
warehouse/src/main/java/org/dromara/hertzbeat/warehouse/config/WarehouseProperties.java
warehouse/src/main/java/org/dromara/hertzbeat/warehouse/store/HistoryGrepTimeDbDataStorage.java
warehouse/src/main/java/org/dromara/hertzbeat/warehouse/store/HistoryJpaDatabaseDataStorage.java
warehouse/src/main/java/org/dromara/hertzbeat/warehouse/store/HistoryVictoriaMetricsDataStorage.java
warehouse/src/main/java/org/dromara/hertzbeat/warehouse/store/RealTimeRedisDataStorage.java

[fix]Fix and pass the checkstyle error in warehouse module code

---

alerter/src/main/java/org/dromara/hertzbeat/alert/AlerterProperties.java
alerter/src/main/java/org/dromara/hertzbeat/alert/calculate/CalculateAlarm.java
alerter/src/main/java/org/dromara/hertzbeat/alert/controller/AlertSilencesController.java
alerter/src/main/java/org/dromara/hertzbeat/alert/dto/TenCloudAlertReport.java
alerter/src/main/java/org/dromara/hertzbeat/alert/service/impl/AlertDefineAbstractImExportServiceImpl.java
alerter/src/main/java/org/dromara/hertzbeat/alert/service/impl/AlertDefineServiceImpl.java
alerter/src/main/java/org/dromara/hertzbeat/alert/service/impl/AlertServiceImpl.java

Related issues: [https://github.com/dromara/hertzbeat/issues/1576](https://github.com/dromara/hertzbeat/issues/1576)

fix and pass the checkstyle error in alerter module code

---

collector/src/main/java/org/dromara/hertzbeat/collector/collect/jmx/JmxCollectImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/controller/AppController.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/AppServiceImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/YamlImExportServiceImpl.java
web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html

fix jmx custom url cause deserialization vulnerability

---

collector/pom.xml
collector/src/main/java/org/dromara/hertzbeat/collector/collect/httpsd/HttpsdImpl.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/httpsd/constant/DiscoveryClientInstance.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/httpsd/discovery/ConnectConfig.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/httpsd/discovery/DiscoveryClient.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/httpsd/discovery/DiscoveryClientManagement.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/httpsd/discovery/ServerInfo.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/httpsd/discovery/ServiceInstance.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/httpsd/discovery/impl/ConsulDiscoveryClient.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/httpsd/discovery/impl/NacosDiscoveryClient.java
collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/DispatchConstants.java
collector/src/main/resources/META-INF/services/org.dromara.hertzbeat.collector.collect.AbstractCollect
common/src/main/java/org/dromara/hertzbeat/common/entity/job/Metrics.java
common/src/main/java/org/dromara/hertzbeat/common/entity/job/protocol/HttpsdProtocol.java
home/docs/help/http_sd.md
manager/src/main/resources/define/app-http_sd.yml

#1526 
支持Http sd监控。
因使用Spring Cloud提供的统一接口DiscoveryClient对代码改动较大，目前采用了各个注册中心原生的SDK进行监控。
> 目前只添加了最常见的两种注册中心：Consul和Nacos，如果后期需要接入更多注册中心，我开放了一个接口org.dromara.hertzbeat.collector.collect.httpsd.discovery.DiscoveryClient，直接实现该接口即可。
代码位置：
本地调试结果：

Feature: http_sd monitor

---

collector/src/main/java/org/dromara/hertzbeat/collector/Collector.java

- bugfix collector can not startup alone
- support bean scan in collector module

bugfix collector can not startup alone

---

home/blog/2022-04-08-hertzbeat-v1.0-beta.7.md
home/blog/2022-05-17-hertzbeat-v1.0-beta.8.md
home/blog/2022-06-19-hertzbeat-v1.1.0.md
home/blog/2022-06-22-one-step-up.md

translate some hertzbeat blog

---

home/blog/2022-06-01-hertzbeat-v1.0.md

translate blog 20220601 to English.

translate blog 20220601 to English

---

manager/src/main/resources/define/app-airflow.yml

support monitor metrics name i18n: Airflow

support monitor metrics name i18n: Airflow

---

manager/src/main/resources/define/app-iotdb.yml

support monitor metrics name i18n: IoTDB

support monitor metrics name i18n: IoTDB

---

home/blog/2022-02-11-hertzbeat.md

Translate 2022-02-11-hertzbeat document

---

push/src/main/java/org/dromara/hertzbeat/push/dao/PushMetricsDao.java

bugfix The annotation @Transactional specifies rollbackFor.

bugfix The annotation @Transactional specifies rollbackFor.

---

manager/src/main/resources/define/app-rocketmq.yml

support monitor metrics name i18n: rocketmq

support monitor metrics name i18n: rocketmq

---

collector/src/main/java/org/dromara/hertzbeat/collector/collect/httpsd/HttpsdImpl.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/httpsd/discovery/DiscoveryClient.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/httpsd/discovery/DiscoveryClientManagement.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/httpsd/discovery/impl/ConsulDiscoveryClient.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/httpsd/discovery/impl/NacosDiscoveryClient.java

fixed the issue in http_sd where services were incorrectly reported as available when they were actually unavailable
When the service is actually unavailable, it still indicates as available:
After fixing the bug:

[bugfix] fixed the issue in http_sd where services were incorrectly reported as available when they were actually unavailable

---

collector/pom.xml
collector/src/main/java/org/dromara/hertzbeat/collector/collect/database/JdbcSpiLoader.java
manager/pom.xml

remove mysql-oracle dependency jar from release package lib
if user want to use it, please download it yourself and put it in the lib directory for use. 
`mysql-connector-java` `ojdbc8` `orai18n`

remove mysql-oracle dependency jar from release package lib

---

alerter/src/main/java/org/dromara/hertzbeat/alert/AlerterProperties.java
common/src/main/java/org/dromara/hertzbeat/common/config/CommonConfig.java
common/src/main/java/org/dromara/hertzbeat/common/config/CommonProperties.java
common/src/main/java/org/dromara/hertzbeat/common/util/AesUtil.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/DingTalkRobotAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/DiscordBotAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/FlyBookAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/GotifyAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/ServerChanAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/TelegramBotAlertNotifyHandlerImpl.java
manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/WeWorkRobotAlertNotifyHandlerImpl.java
manager/src/main/resources/application.yml

support config common aes secret

support config common aes secret

---

collector/src/main/java/org/dromara/hertzbeat/collector/collect/common/cache/CacheIdentifier.java
collector/src/main/java/org/dromara/hertzbeat/collector/collect/redis/RedisCommonCollectImpl.java

[bugfix]fix the issue of add redis cluster node test error report(#1601)

---

collector/src/main/java/org/dromara/hertzbeat/collector/collect/mongodb/MongodbSingleCollectImpl.java
common/src/main/java/org/dromara/hertzbeat/common/entity/job/protocol/MongodbProtocol.java
manager/src/main/resources/define/app-mongodb.yml

mongodb monitoring support custom connection timeout param
https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/connection/mongoclientsettings/#mongoclient-settings

mongodb monitoring support custom connection timeout param

---

web-app/src/app/routes/alert/alert-setting/alert-setting.component.ts

fix bug where reopening pop-up window still retained previously edited data after closing.
[#1653](https://github.com/dromara/hertzbeat/issues/1653)
This may be due to the failure to reset data objects when the page is closed, such as cascadeValues:
And alertRules:
Reset it when closing the page, which seems to have resolved the issue for now:
```angular
onManageModalCancel() {
this.cascadeValues = [];
this.alertRules = [{}];
this.isExpr = false;
this.isManageModalVisible = false;
}
```
Edit page:
After closing/canceling the page:

[bugfix] fix bug where reopening pop-up window still retained previously edited data after closing.

---

web-app/src/app/service/collector.service.ts

When you click the collection cluster menu to perform offline and online operations on the collector, a window will pop up to prompt interface 404, because there is an “/” in front of the calling interface/online/and/offline/interface in the collector.service.ts code, and these two interfaces are removed here “/”

[fixed] fixed click collector online offline button error

---

script/docker-compose/hertzbeat-mysql-iotdb/docker-compose.yaml
script/docker-compose/hertzbeat-mysql-tdengine/docker-compose.yaml
script/docker-compose/hertzbeat-mysql-victoria-metrics/docker-compose.yaml
script/docker-compose/hertzbeat-postgresql-iotdb/conf/application.yml
script/docker-compose/hertzbeat-postgresql-iotdb/docker-compose.yaml

- fix hertzbeat-postgresql-iotdb docker compose start error bug
- run hertzbeat in docker compose support dependen service  #1675

[Improve] run hertzbeat in docker compose support dependen service condition

---

manager/src/main/java/org/apache/hertzbeat/manager/service/impl/StatusPageServiceImpl.java

Fix this issue: https://github.com/apache/hertzbeat/issues/1702
Return a default empty  StatusPageHistory when statusPageHistories size is 0

[bugfix] fix statuspage index exception

---

material/licenses/frontend/LICENSE
web-app/package.json
web-app/src/styles.less
web-app/yarn.lock

- Removed the unused @delon/chart package which was using unlicensed `wolfy87-eventemitter` dependency.
- Removed unused import of @delon/chart/index from style.less
- Update LICENSE

remove unlicensed dependency 'wolfy87 eventemitter'

---

.asf.yaml
.github/workflows/license-checker.yml

- update asf config set required status checks context
```
required_status_checks:
strict: true
contexts:
- check-license-header
```
It is to set `Require branches to be up to date before merging` button true.      
This ensures pull requests targeting a matching branch have been tested with the latest code. This setting will not take effect unless at least one status check is enabled (see below).

[improve] update asf config set required status checks context

---

.github/PULL_REQUEST_TEMPLATE.md

In a specific PR, the e2e page cannot be accessed using a relative path.

[doc] Change e2e path

---

script/helm/hertzbeat/templates/manager/ingress.yaml
script/helm/hertzbeat/values.yaml

1. repair default value.yaml ingress tls secretName path error.
2. add ingress class name property
none

fix : ingress tls inoperative

---

collector/src/main/java/org/apache/hertzbeat/collector/util/CollectUtil.java

The improved method below utilizes the StringUtils.isAnyEmpty() method from the Apache Commons Lang library to enhance readability and maintainability. This change improves code conciseness and clarity while reducing repetitive null and empty string checks. Moreover, using these utility methods makes the code's intent clearer and decreases the likelihood of errors.

[refactor] method improvement rationale

---

collector/src/main/java/org/apache/hertzbeat/collector/util/CollectUtil.java

Removing unnecessary if-else statements
- Additional Note: Upon examining the code flow, I noticed that the parameters could be null, but I confirmed that null checks are already performed earlier in the code. Therefore, additional null checks are not necessary.

Remove unnecessary if-else statement.

---

warehouse/pom.xml
warehouse/src/main/java/org/apache/hertzbeat/warehouse/WarehouseWorkerPool.java
warehouse/src/main/java/org/apache/hertzbeat/warehouse/config/WarehouseProperties.java
warehouse/src/main/java/org/apache/hertzbeat/warehouse/controller/MetricsDataController.java
warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/AbstractRealTimeDataStorage.java
warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/HistoryGrepTimeDbDataStorage.java
warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/HistoryInfluxdbDataStorage.java
warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/HistoryIotDbDataStorage.java
warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/MetricsDataRedisCodec.java
warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/RealTimeMemoryDataStorage.java
warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/RealTimeRedisDataStorage.java

Complete the  'remove and translate chinese to english in warehous' task in https://github.com/apache/hertzbeat/issues/1759

[doc] remove and translate chinese to english in warehous

---

collector/src/main/java/org/apache/hertzbeat/collector/collect/http/promethus/PrometheusLastParser.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/redis/RedisCommonCollectImpl.java
collector/src/main/java/org/apache/hertzbeat/collector/util/JsonPathParser.java

- Replaced the deprecated methods in RedisCommonCollectImpl with the builder pattern for RedisURI creation. This enhancement improves the maintainability and extensibility of the code.
- Eliminated unnecessary string object allocations and enhanced readability using forEach and lambda expressions. This leads to code simplification and improved comprehension.
- Improved readability by using StringUtils.isAnyEmpty() method. This helps clarify the intent of the code and prevents potential bugs.
These three changes enhance the quality of the code, allowing for better maintainability and extensibility.

Replace deprecated methods with builder pattern for RedisURI construction

---

home/docs/introduce.md

Fix display error of "ipmi protocol" in introduce.md, thanks for your review

'[docs]bugfix: display syntax error of ipmi protocol'

---

script/checkstyle/checkstyle.xml

refer to: https://github.com/apache/hertzbeat/issues/1781
add module to checkstyle.xml
```xml
<module name="RegexpSinglelineJava">
<property name="format" 
value="^.*(@author|@date).*" />
<property name="message" 
value="Java file header cannot contain @author or @date" />
</module>
```

[feature:update-checkstyle] Limit the java file header 

---

alerter/src/main/java/org/apache/hertzbeat/alert/calculate/CalculateAlarm.java

When multiple lines are returned, each alarm is triggered instead of only the first alarm

[Improve]When multiple lines are returned, each alarm is triggered instead of only the first alarm

---

collector/src/main/java/org/apache/hertzbeat/collector/collect/redis/RedisCommonCollectImpl.java

If you want to compare N objects for null and throw an IllegalArgumentException, you can easily handle it with `Assert.noNullElements()`.

Comparing N objects for null with Assert.noNullElements().

---

collector/src/main/java/org/apache/hertzbeat/collector/collect/ntp/NtpCollectImpl.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/prometheus/PrometheusAutoCollectImpl.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/prometheus/parser/TextParser.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/push/PushCollectImpl.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/smtp/SmtpCollectImpl.java

This pull request translates Chinese to English.
It looks like many methods are recording the start time and measuring the response time. Could I get your thoughts on using AOP to store the start time in ThreadLocal when entering the method, then using that to handle response time calculations? I'm still learning, so I'd appreciate your advice.
If it's okay, I'd like to give it a try.

[doc] translates chinese comment to english.

---

collector/src/main/java/org/apache/hertzbeat/collector/collect/common/cache/AbstractConnection.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/common/cache/ConnectionCommonCache.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/common/cache/JdbcConnect.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/common/cache/JmxConnect.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/common/cache/MongodbConnect.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/common/cache/RedfishConnect.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/common/cache/RedisConnect.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/database/JdbcCommonCollect.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/jmx/JmxCollectImpl.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/mongodb/MongodbSingleCollectImpl.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/redfish/RedfishCollectImpl.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/redis/RedisCommonCollectImpl.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/ssh/SshCollectImpl.java

The current version does not use generics, resulting in the need for forced type casting.
Because each collector is a singleton, member variables can be used to save its own cache.
In addition, `ConnectionCommonCache` can also be used as a basic component for other businesses to use.
- Both of `ConnectionCommonCache`'s  key and value use generics.
- Using the constructor instead of the static method.

[improve] Refactor common cache code

---

.all-contributorsrc
README.md
README_CN.md
collector/src/main/java/org/apache/hertzbeat/collector/dispatch/timer/HashedWheelTimer.java
collector/src/main/java/org/apache/hertzbeat/collector/dispatch/timer/Timeout.java
collector/src/main/java/org/apache/hertzbeat/collector/dispatch/timer/Timer.java
collector/src/main/java/org/apache/hertzbeat/collector/dispatch/timer/TimerTask.java
home/src/pages/team/index.jsx
manager/src/main/java/org/apache/hertzbeat/manager/config/CommonCommandLineRunner.java
manager/src/main/java/org/apache/hertzbeat/manager/pojo/dto/SystemSecret.java
manager/src/main/java/org/apache/hertzbeat/manager/service/impl/SystemSecretServiceImpl.java
remoting/README.md
remoting/src/main/java/org/apache/hertzbeat/remoting/RemotingClient.java
remoting/src/main/java/org/apache/hertzbeat/remoting/RemotingServer.java
remoting/src/main/java/org/apache/hertzbeat/remoting/RemotingService.java
remoting/src/main/java/org/apache/hertzbeat/remoting/netty/NettyRemotingAbstract.java
remoting/src/main/java/org/apache/hertzbeat/remoting/netty/NettyRemotingClient.java
remoting/src/main/java/org/apache/hertzbeat/remoting/netty/NettyRemotingServer.java

support random jwt secret when not custom

[feature] support random jwt secret when not custom

---

collector/src/main/java/org/apache/hertzbeat/collector/collect/websocket/WebsocketCollectImpl.java
collector/src/test/java/org/apache/hertzbeat/collector/collect/websocket/WebsocketCollectImplTest.java

- Add test for WebsocketCollectImpl.
- Remove static modifier.

[test] Add test for WebsocketCollectImpl

---

hip/README.md
hip/TEMPLATE.md

This is a document regarding significant functional changes to HertzBeat, which includes specific processes and template documents.
Most of the content is referenced from [Pulsar](https://github.com/apache/pulsar/blob/master/pip/README.md), and we can discuss the specific details in detail.

[doc] Add HIP document and template

---

.github/labeler.yml
CONTRIBUTING.md
home/docs/others/contributing.md

Improve the Contribution Documentation.

[doc] Improve the Contribution Documentation.

---

collector/pom.xml
collector/src/main/resources/application.yml
common/src/main/java/org/apache/hertzbeat/common/config/EclipseLinkJpaConfiguration.java

bugfix collector startup error can not find JdbcClient
```
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-05-07 14:00:38.497 [main] ERROR org.springframework.boot.SpringApplication Line:851 - Application run failed
java.lang.IllegalArgumentException: Could not find class [org.springframework.jdbc.core.simple.JdbcClient]
at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:355)
at org.springframework.core.annotation.TypeMappedAnnotation.adapt(TypeMappedAnnotation.java:465)
at org.springframework.core.annotation.TypeMappedAnnotation.getValue(TypeMappedAnnotation.java:390)
```

bugfix collector startup error can not find JdbcClient

---

collector/src/main/java/org/apache/hertzbeat/collector/collect/nebulagraph/NgqlCollectImpl.java
manager/src/main/resources/define/app-nebula_graph_cluster.yml

…ate cannot be edited
1. fixed the problem that the NebulaGraph cluster monitoring template cannot be edited
2. add return statement when nebulaGraph connect error

[fix] fixed name error in monitoring template and improve NGQL protocol

---

warehouse/src/main/java/org/apache/hertzbeat/warehouse/controller/MetricsDataController.java
warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/DataStorageDispatch.java
warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/realtime/RealTimeDataReader.java
warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/realtime/RealTimeDataWriter.java
warehouse/src/test/java/org/apache/hertzbeat/warehouse/controller/MetricsDataControllerTest.java

Added two interfaces RealTimeDataReader and RealTimeDataWriter, replacing AbstractRealTimeDataStorage

[refactoring] Split AbstractRealTimeDataStorage class

---

collector/src/main/java/org/apache/hertzbeat/collector/collect/common/cache/ConnectionCommonCache.java

The value may be null when `addCache -> removeCache`.
It can be reproduced in this unit test.
https://github.com/apache/hertzbeat/blob/78ca5aebf3423324050b58ac661dad4b8c567c6f/collector/src/test/java/org/apache/hertzbeat/collector/collect/redis/RedisClusterCollectImplTest.java#L70
Previously, because there was type checking, it did not trigger a npe.

[bugfix] fix ConnectionCommonCache possible npe

---

home/docs/help/influxdb_promql.md
home/docs/help/kafka_promql.md
home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/influxdb_promql.md
home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/kafka_promql.md
home/sidebars.json
manager/src/main/resources/define/app-influxdb_promql.yml
manager/src/main/resources/define/app-kafka_promql.yml

1. ddd default values to kafka_promql and influxdb_promql monitoring template.
2. add help document for influxdb-promql and kafka-promql monitoring.

[doc] add  help doc for influxdb-promql and kafka-promql monitoring

---

home/i18n/zh-cn/docusaurus-plugin-content-docs/current/community/development.md

As titile and as I discussed in issue #1795 .

[doc] Translate part of documentation development.md under `zh-cn` directory from `en` to `zh-cn`

---

script/assembly/collector/bin/startup.sh

fix collector startup error classpath
```
java.lang.ClassNotFoundException: /Users/tom/code/opensource/hertzbeat/dist/apache-hertzbeat-collector-1/6/0-incubating-bin/apache-hertzbeat-collector-1/6/0/jar:/Users/tom/code/opensource/hertzbeat/dist/apache-hertzbeat-collector-1/6/0-incubating-bin/ext-lib/*
```

[bugfix] fix collector startup error classpath

---

collector/src/main/java/org/apache/hertzbeat/collector/collect/common/cache/ConnectionCommonCache.java
collector/src/test/java/org/apache/hertzbeat/collector/collect/common/cache/CommonCacheTest.java
manager/src/main/java/org/apache/hertzbeat/manager/scheduler/ConcurrentTreeMap.java
manager/src/main/java/org/apache/hertzbeat/manager/scheduler/ConsistentHash.java

Refactored some code to ensure thread safety. And I think `addNode()` and `removeNode()` in `ConsistentHash` class may cause thread unsafe issues.  Please give some suggestions.

[fix] Fix possible potential thread safe bugs

---

.github/workflows/doc-build-test.yml

[improve] add ci for home

---

manager/src/main/java/org/apache/hertzbeat/manager/service/impl/TagServiceImpl.java

Fix [the issue](https://github.com/apache/hertzbeat/issues/2023)
When I set Tag's  name to 'TEST' and value to ''，I expect to get `TEST` Tag, but sometime(when tag's value has set a value then delete the value to empty String) I get `TEST:`(with colon)
- If the value is empty String('')，set the value to null

[bugfix]Tag with empty value Shouldn't transform to Tag:

---

alerter/src/main/java/org/apache/hertzbeat/alert/reduce/AlarmConvergeReduce.java
push/src/main/java/org/apache/hertzbeat/push/service/impl/PushServiceImpl.java
warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/history/greptime/GrepTimeDbDataStorage.java
warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/history/jpa/JpaDatabaseDataStorage.java

bugfix: fix overflow of integers

---

collector/src/test/java/org/apache/hertzbeat/collector/collect/common/cache/CommonCacheTest.java
collector/src/test/java/org/apache/hertzbeat/collector/collect/http/promethus/exporter/ExporterParserTest.java
collector/src/test/java/org/apache/hertzbeat/collector/collect/mongodb/MongoCollectImplTest.java
collector/src/test/java/org/apache/hertzbeat/collector/collect/udp/UdpCollectImplTest.java
collector/src/test/java/org/apache/hertzbeat/collector/util/CollectUtilTest.java
collector/src/test/java/org/apache/hertzbeat/collector/util/JsonPathParserTest.java
collector/src/test/java/org/apache/hertzbeat/collector/util/TimeExpressionUtilTest.java

Fix the code style of the collect test class。

[improve] fix code style

---

home/docs/start/mysql-change.md
home/i18n/zh-cn/docusaurus-plugin-content-docs/current/start/mysql-change.md

Add the missing parts of docs, fix layout, sync the English version with the Chinese version

---

.github/workflows/doc-build-test.yml
home/docs/community/document.md
home/i18n/zh-cn/docusaurus-plugin-content-docs/current/community/document.md

1. add filename check in home ci
2. modify the contribution guide for the  document

[improve]  add filename check in home ci 

---

web-app/src/app/routes/setting/define/define.component.less

[bugfix] fix some template menus hidden when too long

---

home/docs/help/mysql.md
home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/mysql.md

1. mysql monitoring help document adds steps for importing drivers (#2084)

[doc] mysql monitoring help document adds steps for importing drivers

---

e2e/data/monitor-http.json
e2e/start.sh
e2e/testsuite.yaml

fix: the e2e failure without broken the ci

---

home/docs/start/greptime-init.md
home/i18n/zh-cn/docusaurus-plugin-content-docs/current/start/greptime-init.md
manager/src/main/resources/application.yml
warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/history/greptime/GreptimeDbDataStorage.java
warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/history/greptime/GreptimeProperties.java

The following PR of #2095. It adds `TTL` for auto-created database, 30 days by default.

feat: supports TTL for greptimedb data storage

---

web-app/src/app/layout/basic/basic.component.ts

Optimize the code by removing unnecessary attribute values from the `asideUserTpl`.
***The module `asideUserTpl` does not have a click event, nor does it have a dropdown box. Therefore, it is necessary to remove irrelevant attribute values and correct the mouse cursor style to the default, rather than setting it to appear clickable.***

Optimize the code by removing unnecessary attribute values

---

web-app/src/app/routes/setting/collector/collector.component.ts
web-app/src/assets/i18n/en-US.json
web-app/src/assets/i18n/zh-CN.json
web-app/src/assets/i18n/zh-TW.json

[bugfix] the prompt information on the Collector Cluster page

---

web-app/src/app/shared/components/help-massage-show/help-massage-show.component.less

Optimize the visual experience of the `level2Message` module, Change the vertically fixed scrollbar to appear automatically and hide when content does not require scrolling.
before:
after:

Optimize the visual experience of the `level2Message` module.

---

web-app/src/app/routes/alert/alert-center/alert-center.component.html
web-app/src/app/routes/alert/alert-converge/alert-converge.component.html
web-app/src/app/routes/alert/alert-notice/alert-notice.component.html
web-app/src/app/routes/alert/alert-setting/alert-setting.component.html
web-app/src/app/routes/alert/alert-silence/alert-silence.component.html
web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html
web-app/src/app/routes/setting/collector/collector.component.html
web-app/src/app/routes/setting/status/status.component.html
web-app/src/app/routes/setting/tags/tags.component.html

This PR is similar to #2111, removing the unnecessary `y: 100%` value within `nzScroll` in `ng-table` and setting it to auto by default.

Optimize the visual experience of the `nz-table` template.

---

web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html
web-app/src/app/shared/components/multi-func-input/multi-func-input.component.html
web-app/src/app/shared/components/multi-func-input/multi-func-input.component.spec.ts
web-app/src/app/shared/components/multi-func-input/multi-func-input.component.ts
web-app/src/app/shared/shared.module.ts

Replace the two `input` components in the monitoring center with `input` components that have a **allowClear** function, so that they are consistent with the `select` components in supporting quick clear of filter values.

Add an input box component with a removal function.

---

web-app/src/app/routes/setting/define/define.component.html
web-app/src/app/routes/setting/define/define.component.less

Fixed the layout styling issue of the left list on the `setting/define`.

---

web-app/src/app/routes/setting/define/define.component.html
web-app/src/app/routes/setting/define/define.component.ts

before:
after:
Add a loading animation to the `/setting/define` page.

Add a loading animation to the `/setting/define` page.

---

manager/src/main/java/org/apache/hertzbeat/manager/config/InternationalizationConfig.java
manager/src/main/java/org/apache/hertzbeat/manager/dao/StatusPageIncidentComponentBindDao.java
manager/src/main/java/org/apache/hertzbeat/manager/service/impl/StatusPageServiceImpl.java
manager/src/main/resources/messages.properties
manager/src/main/resources/messages_en.properties
manager/src/main/resources/messages_zh.properties
manager/src/main/resources/messages_zh_TW.properties

1. fix deleting component error about (#2147)
2. add i18n support to backend services

[bugfix] fix deleting component error

---

web-app/src/app/layout/basic/widgets/notify.component.ts
web-app/src/app/layout/layout.module.ts

before:
after:
Originally, the notification center referenced the `notice-icon` component, which was implemented based on the `nz-tabs` component. However, there was a bug where the **tab-panel** would not show up in **hertzbeat** when there was only one tab. Given the current usage scenario, we can avoid relying on the ·notice-icon· component and implement it ourselves.

Fixed notify module error

---

manager/src/main/java/org/apache/hertzbeat/manager/dao/TagMonitorBindDao.java
manager/src/main/java/org/apache/hertzbeat/manager/service/impl/TagServiceImpl.java
manager/src/test/java/org/apache/hertzbeat/manager/service/TagServiceTest.java

1. modify the prompt information for deleting used tags
**Before:**
**After:**

[bugfix] modify the prompt information for deleting used tags

---

web-app/src/app/routes/alert/alert-setting/alert-setting.component.html

before:
after:
When the [`Metric Target`] is set as [`Monitor Availability`], the [`Threshold Rule`] belongs to an invalid field (it is currently displayed but cannot be edited), so it should not be shown.

Optimize the [Threshold Rule] Form.

---

web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html
web-app/src/app/routes/monitor/monitor-list/monitor-list.component.ts
web-app/src/app/shared/components/multi-func-input/multi-func-input.component.html
web-app/src/app/shared/components/multi-func-input/multi-func-input.component.ts
web-app/src/app/shared/utils/common-util.ts
web-app/src/assets/i18n/en-US.json
web-app/src/assets/i18n/zh-CN.json
web-app/src/assets/i18n/zh-TW.json

Optimize the user experience of monitoring list pages.

---

collector/src/main/java/org/apache/hertzbeat/collector/collect/ftp/FtpCollectImpl.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/mongodb/MongodbSingleCollectImpl.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/mq/RocketmqSingleCollectImpl.java
collector/src/main/java/org/apache/hertzbeat/collector/collect/redis/RedisCommonCollectImpl.java

[Improve] add @Override

---

collector/src/main/java/org/apache/hertzbeat/collector/collect/http/HttpCollectImpl.java

#2298 
Any method can carry a payload
Consistent with front end，Only POST and PUT methods carry payload

[bugfix] Only POST and PUT methods carry payload

---

home/docs/start/postgresql-change.md
home/i18n/zh-cn/docusaurus-plugin-content-docs/current/start/postgresql-change.md

1. Translate some English content in Chinese documents
2. Beautify the format
3. Improve the steps to check whether the database is created successfully

[doc] modify the document that uses PostgreSQL to store metadata

---

web-app/src/app/routes/monitor/monitor-list/monitor-list.component.ts

Correct the setInterval function timing in monitor-list.component.ts to ensure the table refreshes every 2 minutes as intended. The previous code incorrectly specified the interval as12,000 milliseconds instead of the intended 120,000 milliseconds.
[bugfix]: correct setInterval time interval to 2 minutes

[bugfix]: correct setInterval time interval to 2 minutes

---

manager/src/test/java/org/apache/hertzbeat/manager/component/alerter/impl/AliYunAlertNotifyHandlerImplTest.java
manager/src/test/java/org/apache/hertzbeat/manager/component/alerter/impl/DbAlertStoreHandlerImplTest.java
manager/src/test/java/org/apache/hertzbeat/manager/component/alerter/impl/GotifyAlertNotifyHandlerImplTest.java
manager/src/test/java/org/apache/hertzbeat/manager/component/alerter/impl/ServerChanAlertNotifyHandlerImplTest.java
manager/src/test/java/org/apache/hertzbeat/manager/component/alerter/impl/SmsAlertNotifyHandlerImplTest.java
manager/src/test/java/org/apache/hertzbeat/manager/component/alerter/impl/WeComAppAlertNotifyHandlerImplTest.java

- add DbAlertStoreHandlerImpl unit test

[Improve] add DbAlertStoreHandlerImpl unit test

---

web-app/src/app/routes/dashboard/dashboard.component.html
web-app/src/app/routes/dashboard/dashboard.component.less
web-app/src/app/routes/dashboard/dashboard.component.ts

---  
> https://ng.ant.design/components/card/zh#components-card-demo-tabs
```html
<nz-card style="width: 100%;" nzTitle="Card title" [nzExtra]="extraTemplate">
<nz-card-tab>
<nz-tabset nzSize="large" [(nzSelectedIndex)]="index1">
<nz-tab nzTitle="tab1"></nz-tab>
<nz-tab nzTitle="tab2"></nz-tab>
</nz-tabset>
</nz-card-tab>
content{{ index1 }}
</nz-card>
```
From the official examples, it is evident that the `content` of the `tab` should not be placed directly under `nz-card-tab`; this is because `nz-card-tab` is rendered within `nz-card-head`.

Fixed the issue of style anomaly caused by incorrect usage of nz-card-tab

---

.gitpod.Dockerfile
.gitpod.yml

Installing JDK17 based on default container isolation is far more efficient than building a dedicated container separately.

Optimize the execution efficiency of Gitpod tasks

---

manager/src/main/resources/define/app-greenplum.yml

add greenplum template
see https://greenplum.org/

[feature] add greenplum template

---

.github/workflows/backend-build-test.yml
e2e/testsuite.yaml

I realized that the current log upload ci task doesn't upload when the ci fails, so I made the change. You can check the: https://github.com/yuluo-yx/hertzbeat/actions/runs/10235846904?pr=12.
This configuration still uploads logs when ci fails. fix: https://github.com/apache/hertzbeat/actions/runs/10229236498/job/28302645855
@tomsun28 ptal.

feat: fix log upload, when e2e fails it still uploads

---

manager/src/main/resources/define/app-shenyu.yml
manager/src/main/resources/define/app-spring_gateway.yml

add shenyu\spring gateway i18n

[improve] add shenyu\spring gateway i18n

---

alerter/src/main/java/org/apache/hertzbeat/alert/controller/AlertConvergeController.java
alerter/src/main/java/org/apache/hertzbeat/alert/controller/AlertDefineController.java
alerter/src/main/java/org/apache/hertzbeat/alert/controller/AlertSilenceController.java
alerter/src/main/java/org/apache/hertzbeat/alert/service/impl/AlertDefineExcelImExportServiceImpl.java
collector/src/main/java/org/apache/hertzbeat/collector/dispatch/unit/impl/TimeLengthConvert.java
common/src/main/java/org/apache/hertzbeat/common/constants/NetworkConstants.java
manager/src/main/java/org/apache/hertzbeat/manager/component/alerter/impl/AbstractAlertNotifyHandlerImpl.java
manager/src/main/java/org/apache/hertzbeat/manager/config/AiProperties.java
manager/src/main/java/org/apache/hertzbeat/manager/config/RestTemplateConfig.java
warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/history/influxdb/InfluxdbDataStorage.java

[optimize] use okhttpclient connection pool

---

manager/src/main/java/org/apache/hertzbeat/manager/component/alerter/impl/AbstractAlertNotifyHandlerImpl.java
manager/src/main/java/org/apache/hertzbeat/manager/component/alerter/impl/WebHookAlertNotifyHandlerImpl.java

[bugfix] webhook template json escape

---

web-app/src/app/routes/monitor/monitor-list/monitor-list.component.ts

fix monitor search sync error, see #2541

[bugfix] fix monitor search sync error

---

web-app/src/app/routes/alert/alert-setting/alert-setting.component.ts

clear qbdata when cascade change
if u changed the cascade value to 3 length、add some rule and then change it back to 2 length. the rules datas were not cleared

[bugfix] clear qbdata when cascade change

---

script/checkstyle/checkstyle.xml

Fixs #2594
Temporarily disable import sort checkstyle

[Improve]Temporarily disable import sort

---

alerter/src/main/java/org/apache/hertzbeat/alert/reduce/AlarmConvergeReduce.java

When using the hashkey of tags as a match, the order of the hash string must also be kept consistent.

[bugfix] fix alarm recover not match in converge reduce in some condition

---

common/src/main/java/org/apache/hertzbeat/common/entity/manager/Collector.java
common/src/main/java/org/apache/hertzbeat/common/entity/manager/GeneralConfig.java
common/src/main/java/org/apache/hertzbeat/common/entity/manager/NoticeReceiver.java
common/src/main/java/org/apache/hertzbeat/common/entity/manager/NoticeRule.java
common/src/main/java/org/apache/hertzbeat/common/entity/manager/Param.java
common/src/main/java/org/apache/hertzbeat/common/entity/manager/Tag.java
manager/src/main/java/org/apache/hertzbeat/manager/controller/TagController.java
manager/src/main/java/org/apache/hertzbeat/manager/pojo/dto/MonitorDto.java
manager/src/main/java/org/apache/hertzbeat/manager/service/impl/TagServiceImpl.java
manager/src/test/java/org/apache/hertzbeat/manager/controller/TagControllerTest.java
manager/src/test/java/org/apache/hertzbeat/manager/service/TagServiceTest.java

- Modify the vaild parameter
- Modify relevant unit tests
- Simplify the controller

[imporve] Adjustment of parameter verification

---

script/docker-compose/hertzbeat-postgresql-victoria-metrics/docker-compose.yaml

Place ./ext-lib:/opt/hertzbeat/ext-lib in the mount under hertzbeat

fix the mounting issues in script/docker-compose/hertzbeat-postgresql-victoria-metrics/docker-compose.yaml 

---

web-app/src/app/routes/monitor/monitor-detail/monitor-detail.component.html

fix monitor detail display error
when get grafana dashboard info null, this error will occers

[bugfix] fix monitor detail display error

---

manager/src/main/java/org/apache/hertzbeat/manager/service/impl/BulletinServiceImpl.java

filter dashboard metrics
fix this:
create dashboard select one metric, flush to more than one metrics

[bugfix] filter dashboard metrics

---

common/src/main/java/org/apache/hertzbeat/common/entity/manager/bulletin/Bulletin.java

fix custom dashboard show metrics error
use h2 database. 
when create a custom kanban, select some metrics, it shows ok
but after restart server, the fields querys error
h2 database supports json field not good

[bugfix] fix custom dashboard show metrics error

---

web-app/src/app/routes/bulletin/bulletin.component.ts

add kanban auto refresh:
if we create a new kanban, and the metrics data will not auto refresh itself

[improve] add kanban auto refresh

---

web-app/src/app/pojo/StatusPageHistory.ts
web-app/src/app/routes/status-public/status-public.component.html

fix status page unknowing status value
value key mismatch

[bugfix] fix status page unknowing status value

---

web-app/src/app/routes/bulletin/bulletin.component.html
web-app/src/app/routes/bulletin/bulletin.component.ts

support kanban set auto refresh Interval

[improve] support kanban set auto refresh Interval

---

home/blog/2024-08-31-new-committer.md
home/i18n/zh-cn/docusaurus-plugin-content-blog/2024-08-31-new-committer.md

[improve] add new committer blog

---

manager/src/main/java/org/apache/hertzbeat/manager/controller/AccountController.java
manager/src/main/java/org/apache/hertzbeat/manager/pojo/dto/TokenDto.java
manager/src/test/java/org/apache/hertzbeat/manager/controller/AccountControllerTest.java
web-app/src/app/service/auth.service.ts

[improve] use post request refresh token

---

pom.xml
script/release/release-win.ps1
web-app/src/app/shared/constants.ts

Add release windows script and update version

[improve]Add release windows script and update version.

---

manager/src/main/java/org/apache/hertzbeat/manager/config/ConfigInitializer.java

init default theme
fix:
when first start, the theme will be this

[improve] init default theme

---

home/docs/start/package-deploy.md
home/i18n/zh-cn/docusaurus-plugin-content-docs/current/start/package-deploy.md
home/i18n/zh-cn/docusaurus-plugin-content-docs/version-v1.5.x/start/package-deploy.md
home/versioned_docs/version-v1.5.x/start/package-deploy.md

link https://github.com/apache/hertzbeat/issues/2747 and https://github.com/apache/hertzbeat/pull/2752

[doc] fix JDK download mirror link

---

hertzbeat-grafana/src/main/java/org/apache/hertzbeat/grafana/common/GrafanaConstants.java
hertzbeat-grafana/src/main/java/org/apache/hertzbeat/grafana/config/GrafanaProperties.java
hertzbeat-grafana/src/main/java/org/apache/hertzbeat/grafana/service/DashboardService.java
hertzbeat-grafana/src/main/java/org/apache/hertzbeat/grafana/service/ServiceAccountService.java
hertzbeat-manager/src/main/resources/application.yml
hertzbeat-warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/history/vm/VictoriaMetricsClusterDataStorage.java
hertzbeat-warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/history/vm/VictoriaMetricsDataStorage.java

- update api auth method
> for some maybe use xxx@xxx as password, it will work failed when pre auth method. 
- add expose url param
> for some env the inner access grafana server url and extern access url may not same.

[improve] update grafana auth method and add expose url

---

.gitpod.yml

Fixed the omissions in #2805

---

hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/registry/RegistryImpl.java
hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/registry/constant/DiscoveryClientHealthStatus.java
hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/registry/constant/DiscoveryClientInstance.java
hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/registry/discovery/DiscoveryClient.java
hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/registry/discovery/DiscoveryClientManagement.java
hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/registry/discovery/entity/ConnectConfig.java
hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/registry/discovery/entity/ServerInfo.java
hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/registry/discovery/entity/ServiceInstance.java
hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/registry/discovery/impl/ConsulDiscoveryClient.java
hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/registry/discovery/impl/NacosDiscoveryClient.java
hertzbeat-collector/hertzbeat-collector-basic/src/test/java/org/apache/hertzbeat/collector/collect/registry/RegistryImplTest.java
hertzbeat-collector/hertzbeat-collector-collector/src/main/resources/META-INF/services/org.apache.hertzbeat.collector.collect.AbstractCollect
hertzbeat-collector/hertzbeat-collector-common/src/main/java/org/apache/hertzbeat/collector/dispatch/DispatchConstants.java
hertzbeat-common/src/main/java/org/apache/hertzbeat/common/entity/job/Metrics.java
hertzbeat-common/src/main/java/org/apache/hertzbeat/common/entity/job/protocol/RegistryProtocol.java
hertzbeat-manager/src/main/resources/define/app-registry.yml
home/docs/help/registry.md
home/versioned_docs/version-v1.5.x/help/registry.md

The monitor I've changed is to monitor registry so that I monified its name and package.

[refactor] change name from http_sd to registry

---

web-app/src/app/routes/monitor/monitor-data-chart/monitor-data-chart.component.ts

- Removed the 'stack: 'Total'' property from multiple line chart configurations
- This change improves the visual representation of data by removing stacked areas

[improve]Remove stack property from line charts

---

web-app/src/app/routes/monitor/monitor-form/monitor-form.component.ts
web-app/src/assets/i18n/en-US.json
web-app/src/assets/i18n/zh-CN.json
web-app/src/assets/i18n/zh-TW.json

[Issue](https://github.com/apache/hertzbeat/issues/2779)
启用和关闭https导致端口号自动变更时，增加提示
Add notification when port number changes automatically due to HTTPS toggle.

[Improve] add notification when port number changes automatically due to HTTPS toggle.(#2779)

---

hertzbeat-collector/hertzbeat-collector-kafka/src/main/java/org/apache/hertzbeat/collector/collect/kafka/KafkaCollectImpl.java
hertzbeat-collector/hertzbeat-collector-kafka/src/main/java/org/apache/hertzbeat/collector/collect/kafka/constants/InternalTopic.java
hertzbeat-collector/hertzbeat-collector-kafka/src/main/java/org/apache/hertzbeat/collector/collect/kafka/constants/SupportedCommand.java
hertzbeat-common/src/main/java/org/apache/hertzbeat/common/entity/job/protocol/KafkaProtocol.java
hertzbeat-manager/src/main/resources/define/app-kafka_client.yml

Kafka internal topics do not need to be displayed in most cases, as they take up too much space. Because he has 50 partitions.
We use configuration items to set whether to monitor internal topics.

[Imporve] Support Kafka internal topic configuration

---

hertzbeat-manager/src/main/resources/define/app-flink.yml

- Replace direct metric references with get() function for dynamic value retrieval
- Correct calculation logic for slots_used and task_total metrics
- Ensure consistent naming and improve error tolerance in metric calculations

[fix](flink): update calculate metrics definitions

---

web-app/src/app/layout/basic/widgets/notify.component.ts

1. Fix the bug where toggling the mute state did not correctly send a request to the backend to synchronize the state.
2. Add default value initialization for the mute property to fix console errors.

[bugfix] Bug fix for alarm voice.

---

web-app/src/assets/i18n/en-US.json

I noticed the dashboard has 'DashBoard' .. the 'B' should be lower case 'b' .

[bugfix]  Corrected case 'DashBoard' is a lower case 'B'

---

hertzbeat-collector/hertzbeat-collector-collector/src/main/java/org/apache/hertzbeat/collector/dispatch/CommonDispatcher.java

When the worker poll is full and rejects tasks,this represents a potential system performance issue that users should be aware of.
Changing the log level from `INFO` to `WARN` will make this more visible in monitoring.

【Improve】adjust log level from INFO to WARN.

---

home/docs/help/kafka_client.md

Add English version of documentation for recently added Kafka consumer metrics,
which previously only had a Chinese version.

[Doc]:Add English version of documentation for Kafka Consumer Detail

---

web-app/src/app/routes/alert/alert-group/alert-group-converge.component.html
web-app/src/app/routes/alert/alert-group/alert-group-converge.component.ts
web-app/src/app/routes/alert/alert-inhibit/alert-inhibit.component.html
web-app/src/app/routes/alert/alert-inhibit/alert-inhibit.component.ts
web-app/src/app/routes/alert/alert-setting/alert-setting.component.html
web-app/src/app/routes/alert/alert-setting/alert-setting.component.ts
web-app/src/app/routes/alert/alert-silence/alert-silence.component.html
web-app/src/app/routes/alert/alert-silence/alert-silence.component.ts
web-app/src/app/routes/monitor/monitor-list/monitor-list.component.ts

[Issue](https://github.com/apache/hertzbeat/issues/2956)

Fix the search functionality issue.

---

hertzbeat-collector/hertzbeat-collector-kafka/src/test/java/org/apache/hertzbeat/collector/collect/kafka/KafkaCollectTest.java

For `KafkaCollectTest`,in the previous test cases, we did not set the value of the `command`, so it was left `null`. 
This PR aims to add new test cases where `command` is not null.

[Improve] Add more test cases for Kafka junit tests

---

hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/prometheus/PrometheusAutoCollectImpl.java

CloseableHttpResponse should be closed

[MINOR UPDATE] close http response in PrometheusAutoCollectImpl

---

hertzbeat-alerter/src/test/java/org/apache/hertzbeat/alert/service/AlertDefineJsonImExportServiceTest.java
hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/telnet/TelnetCollectImpl.java
hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/websocket/WebsocketCollectImpl.java
hertzbeat-common/src/main/java/org/apache/hertzbeat/common/entity/message/CollectRep.java
hertzbeat-common/src/test/java/org/apache/hertzbeat/common/serialize/KafkaMetricsDataDeserializerTest.java
hertzbeat-common/src/test/java/org/apache/hertzbeat/common/util/FileUtilTest.java
hertzbeat-e2e/hertzbeat-collector-basic-e2e/src/test/java/org/apache/hertzbeat/collector/collect/basic/http/DockerMonitorE2eTest.java
hertzbeat-manager/src/test/java/org/apache/hertzbeat/manager/controller/PluginControllerTest.java
hertzbeat-manager/src/test/java/org/apache/hertzbeat/manager/service/JsonImExportServiceTest.java
hertzbeat-manager/src/test/java/org/apache/hertzbeat/manager/service/PluginServiceTest.java
template-marketplace/hertzbeat-template-hub/src/main/java/org/apache/hertzbeat/templatehub/service/impl/LocalFileStorageServiceImpl.java
template-marketplace/hertzbeat-template-hub/src/test/java/org/apache/hertzbeat/templatehub/controller/VersionControllerTest.java
template-marketplace/hertzbeat-template-hub/src/test/java/org/apache/hertzbeat/templatehub/controller/VersionDOControllerTest.java

* if you don't specify the char encoding, then it is up to the JVM config on the machine
* this means different users can see different results

[MINOR UPDATE] always specify the char encoding in getBytes

---

web-app/src/app/routes/alert/alert-setting/alert-setting.component.html
web-app/src/app/routes/alert/alert-setting/alert-setting.component.ts
web-app/src/app/shared/components/multi-func-input/multi-func-input.component.ts

[Issue](https://github.com/apache/hertzbeat/issues/3033)
1. Fixed the bug where pressing Enter after clicking the ❌ would cause a continuous loading screen.  
2. Now, clicking the ❌ will automatically refresh without the need to press Enter.

[bugfix] Fixed the bug in the threshold rules search box.

---

.github/workflows/backend-build-test.yml
.github/workflows/doc-pdf-builder.yml

Upgrade `actions/upload-artifact` to v4 to fix errors in CI.  
[Reference documentation](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)

[update] upgrade actions/upload-artifact to v4

---

hertzbeat-common/src/main/java/org/apache/hertzbeat/common/entity/message/CollectRep.java
hertzbeat-common/src/test/java/org/apache/hertzbeat/common/entity/message/CollectRepTest.java

#3102
I implemented the equals method in the CollectRep.Field class so that it can be found in the list by name.
For more details, you can check the comments I previously added in issue #3102, where I explained the specific cause of the bug, the possible solutions, and discussions on which approach to take.

[bugfix] Fix exception thrown when searching for CollectRep.Field in the list

---

web-app/src/app/routes/monitor/monitor-list/monitor-list.component.ts

Fixes https://github.com/apache/hertzbeat/issues/3154
Added state variables to track current sorting parameters

[bugfix] retain sorting state after monitor list auto-refresh

---

web-app/src/app/routes/alert/alert-setting/alert-setting.component.ts

#3169 fix bind Labels are not updated when the Alarm Severity switches

[bugfix] fix bind Labels are not updated when the Alarm Severity switches

---

hertzbeat-warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/history/vm/VictoriaMetricsClusterDataStorage.java
hertzbeat-warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/history/vm/VictoriaMetricsDataStorage.java

- reslove #3246
Resolve incorrect display of detailed information in Prometheus task history monitoring charts under VictoriaMetrics.

[bugfix] Resolve incorrect display of detailed information in Prometheus task history monitoring charts under VictoriaMetrics.

---

hertzbeat-alerter/src/main/java/org/apache/hertzbeat/alert/calculate/RealTimeAlertCalculator.java

#3220 
This PR fixes a bug where `RealTimeAlertCalculator` failed to properly filter unbound instances during threshold rule evaluation. The issue was caused by the backend regex not accounting for optional whitespace in alert expressions generated by the frontend.
Log-based verification was used to confirm correctness of the fix:
- Logs before and after filtering were printed.
- Only the bound instance was allowed to pass the filter, while unbound ones were filtered out as expected.
Sample log output:
```txt
filter before expr: equals(__app__,"redis") && equals(__available__,"down") && equals(__instance__, "501045327364864"), instance :501786917278464  
filter before expr: equals(__app__,"redis") && equals(__available__,"down") && equals(__instance__, "501045327364864"), instance …
```

[bugfix] correct instance filtering regex in RealTimeAlertCalculator

---

.gitignore
mvnw
mvnw.cmd

In order to facilitate compilation and running without a Maven environment, I think mvnw should be added to the project. I have referred to many projects, and they all contain the mvnw file.

[feature] add Maven Wrapper scripts 

---

web-app/src/app/layout/basic/widgets/notify.component.ts
web-app/src/assets/i18n/en-US.json
web-app/src/assets/i18n/ja-JP.json
web-app/src/assets/i18n/pt-BR.json
web-app/src/assets/i18n/zh-CN.json
web-app/src/assets/i18n/zh-TW.json

1. new alert supports reminding through system notifications, this is very useful for computers without audio playback devices.
2. optimize duplicate alarm sound reminders.

[feature] new alert supports reminding through system notifications

---

hertzbeat-alerter/src/main/java/org/apache/hertzbeat/alert/calculate/RealTimeAlertCalculator.java
hertzbeat-alerter/src/test/java/org/apache/hertzbeat/alert/calculate/RealTimeAlertCalculatorTest.java

#3220 
This PR fixes a bug in RealTimeAlertCalculator where instance filtering failed when alert expressions contained no whitespace (e.g., `equals(__app__,"redis") && equals(__instance__,"501045327364864")`).
The backend regex has been updated to support such compact expressions. A unit test is also added to ensure proper filtering across different formatting styles.

[bugfix] support no-whitespace alert expressions in instance filtering

---

hertzbeat-e2e/hertzbeat-collector-basic-e2e/src/test/java/org/apache/hertzbeat/collector/collect/basic/redis/RedisCommonCollectE2eTest.java

enable RedisCommonCollect E2E tests via Testcontainers

[improve] Add E2E tests for Redis collector

---

web-app/src/app/routes/routes-routing.module.ts

… type
1. fix page title show  "Not page name" when filter monitor list by type

[bugfix]: page title show  "Not page name" when filter monitor list by type

---

.github/workflows/doc-build-test.yml
script/ci/link_check.json

…action and ignore the 500 code for link check
Remove the possible CVE-2025-30066 security vulnerability action and ignore the 500 code for link check
*tj-actions/changed-files has been found to have [security issues](https://www.wiz.io/blog/github-action-tj-actions-changed-files-supply-chain-attack-cve-2025-30066). Although the latest hash-pinned version is used. ( As of March 15, 2025, all versions of tj-actions/changed-files were found to be affected, as the attacker managed to modify existing version tags to make them all point to their malicious code. Customers who were using a hash-pinned version of tj-actions/changed-files would not be impacted, unless they had updated to an impacted hash during the exploitation timeframe. ), At present, it may still not permitted for use in GitHub …

[refactor] Remove the possible CVE-2025-30066 security vulnerability action and ignore the 500 code for link check

---

web-app/src/assets/doc/alert-integration/tencent.en-US.md
web-app/src/assets/doc/alert-integration/tencent.ja-JP.md
web-app/src/assets/doc/alert-integration/tencent.zh-CN.md
web-app/src/assets/doc/alert-integration/tencent.zh-TW.md
web-app/src/assets/doc/alert-integration/uptime-kuma.en-US.md
web-app/src/assets/doc/alert-integration/uptime-kuma.zh-CN.md
web-app/src/assets/doc/alert-integration/uptime-kuma.zh-TW.md
web-app/src/assets/doc/alert-integration/zabbix.en-US.md
web-app/src/assets/doc/alert-integration/zabbix.zh-CN.md
web-app/src/assets/doc/alert-integration/zabbix.zh-TW.md

#3350 
Corrected webhook endpoint examples in integration guide.

[bugfix] Fix incorrect webhook URLs for Uptime Kuma, Zabbix, and Tencent Cloud

---

hertzbeat-manager/src/main/resources/application.yml

#3435 
When running HertzBeat locally, OpenTelemetry SDK by default attempts to send traces, metrics, and logs to `http://localhost:4318`
This behavior is caused by the auto-configuration of OpenTelemetry exporters when no explicit exporter is set.
The following properties are added to explicitly disable all OpenTelemetry exporters when `warehouse.greptime.enabled = false`:
```yaml
otel:
traces:
exporter: none
metrics:
exporter: none
logs:
exporter: none
```

[improvement] disable default OpenTelemetry exporters to prevent connection errors

---

web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html

Please refer to: [#3464](https://github.com/apache/hertzbeat/issues/3464)
The Monitors page is missing `nzPageSize`, which results in an error in calculating the number of pages.
- [ x ]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [ x ]  I have written the necessary doc or comment.
- [ x ]  I have added the necessary unit tests and all cases have passed.
1、Before repair
2、After repair

[fix] Fix `Monitors` paging display.

---

hertzbeat-alerter/src/main/java/org/apache/hertzbeat/alert/expr/AlertExpressionEvalVisitor.java
hertzbeat-alerter/src/test/java/org/apache/hertzbeat/alert/expr/AlertExpressionEvalVisitorTest.java
hertzbeat-alerter/src/test/java/org/apache/hertzbeat/alert/service/DataSourceServiceTest.java

Please refer to: [#3480](https://github.com/apache/hertzbeat/issues/3480)
Main issue:
1. Only the first non-empty item of `leftOperand` and `rightOperand` was processed, merging once instead of intersecting all non-empty items, resulting in an incorrect outcome.
2. The tags are not aligned, and no matching is done for the tag sets; they are merged directly, which causes tag confusion and results in errors. This is because the semantics of `and` are based on the intersection of tag sets, and the result only retains the tags and values from the left side.
Modification details:
1. Fixed the semantic issue with `and`. For details, see: [Logical/set binary operators](https://prometheus.io/docs/prometheus/latest/querying/operators/#logicalset-binary-operators)
2. Optimize parsing and union …

[fix] antlr4 `vectors and` parse semantic fixes and optimizations

---

hertzbeat-alerter/src/main/java/org/apache/hertzbeat/alert/expr/AlertExpressionEvalVisitor.java
hertzbeat-alerter/src/test/java/org/apache/hertzbeat/alert/expr/AlertExpressionEvalVisitorTest.java
hertzbeat-alerter/src/test/java/org/apache/hertzbeat/alert/service/DataSourceServiceTest.java

Please refer to: [#3482](https://github.com/apache/hertzbeat/pull/3482)
Reference: PR[#3482]
Modification details:
1. Fixed the semantic issue with `unless` /  `or`. For details, see: [Logical/set binary operators](https://prometheus.io/docs/prometheus/latest/querying/operators/#logicalset-binary-operators)
2. Add/fix test cases and pass historical cases successfully .
The effect after the fix is as follows：
UNLESS：
OR：

[fix] Fix antlr4 parsing of `or` and `unless` logical and set binary operators

---

hertzbeat-manager/src/main/resources/define/app-hertzbeat_token.yml
web-app/src/app/routes/alert/alert-setting/alert-setting.component.ts

#3494 
This PR resolves a critical parsing error within the alert settings component. The error occurred when editing an existing threshold rule with `contains(__labels__,"xxx")`, causing the expression to be displayed incorrectly and making the rule uneditable.
The underlying issue was that the logic for extracting the user-facing expression (`user_expr`) from the full, raw expression (`raw_expr`) did not properly filter out internal clauses like `contains(__label__,"xxx")`. This resulted in a failed visualization of the metric expression.
test:
https://github.com/user-attachments/assets/3fdfd5fe-da59-43b4-b728-1c43c800d07e

[bugfix] Fix incorrect expression parsing in alert setting component

---

.asf.yaml

relates to #3000 
see https://github.com/apache/infrastructure-asfyaml/blob/main/README.md#depend_alerts

enable GitHub Dependabot to create PRs for security alerts but not for every dependency update

---

hertzbeat-manager/src/main/resources/define/app-kingbase.yml

Related issue: #3630 
- This template only contains the `size` keyword, and use `Size` to replace the keyword `size`
> Kingbase version: `V8R6(KingbaseES V008R006C005B0013)`
- Template saved successfully.
- Run unit test `YamlCheckScript#checkYaml()` method successful.
- Prepare test data.
Execute the following SQL to generate some temporary files.
```sql
select * from generate_series(1,10000000000) order by 1; 
```
- Verify that the indicator data is normal, that threshold alarms are normal, and that the test cases pass.

[bugfix] fixed jexl keyword issue in kingbase monitoring template

---

web-app/src/app/routes/monitor/monitor-detail/monitor-detail.component.html
web-app/src/app/routes/monitor/monitor-detail/monitor-detail.component.ts

Optimize loading performance for `Monitor Real-Time Detail` and `Monitor Historical Chart Detail` to resolve indicator stuttering issues.

[improve] Improve performance issues when loading large numbers of metric cards in Monitors

---

web-app/src/app/shared/components/form-field/form-field.component.html

Previously, the "Intervals" input field for scrape-based monitors used a step of 60 seconds,This change modifies the nzStep property of the nz-input-number component, reducing the interval step from 60 to 10. 
**close #3720**

[Improve] changed scroll of intervals in New Monitor page 

---

web-app/src/assets/i18n/en-US.json

- improve / fix capitalization error from "Dispatch ALl" to "Dispatch All"

[improve] nitpicking  "Dispatch ALl" on en-US.json

---

hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/prometheus/parser/OnlineParser.java
hertzbeat-collector/hertzbeat-collector-basic/src/test/java/org/apache/hertzbeat/collector/collect/prometheus/parser/OnlineParserSingleTest.java

Incorrect UTF-8 validation logic: The validation in OnlineParser.java: lines 419-421 incorrectly identifies valid Chinese strings as invalid.
Byte stream processing issue: The original parser reads the InputStream byte by byte and cannot correctly handle UTF-8 multi-byte characters (Chinese characters occupy 3 bytes).
Close #3791
Change the byte-by-byte parsing based on InputStream to UTF-8 string parsing
add test for this change

fix: use UTF-8 to solve Chineses bug
