collector/src/main/java/com/usthe/collector/dispatch/timer/WheelTimerTask.java, common/src/main/java/com/usthe/common/util/IpDomainUtil.java, manager/src/main/java/com/usthe/manager/service/impl/MonitorServiceImpl.java, web-app/src/app/routes/monitor/monitor-edit/monitor-edit.component.ts, web-app/src/app/routes/monitor/monitor-new/monitor-new.component.ts
=> [manager,webapp]bugfix website monitor path Illegal character in path

collector/pom.xml, collector/src/main/java/com/usthe/collector/collect/database/JdbcCommonCollect.java, collector/src/main/java/com/usthe/collector/util/CollectorConstants.java, manager/src/main/resources/define/app/postgresql.yml, manager/src/main/resources/define/param/postgresql.yml
支持postgresql数据库的监控 #15 
metrics see http://www.postgres.cn/docs/12/monitoring-stats.html#PG-STAT-DATABASE-VIEW
=> [collector,manager]feature 支持postgresql数据库的监控

collector/src/main/java/com/usthe/collector/collect/http/HttpCollectImpl.java
=> feat: 模拟浏览器设置为chrome浏览器 #Issues 14

.github/FUNDING.yml, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/custom.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/codeql-analysis.yml, .github/workflows/issues-translator.yml, .github/workflows/maven-build.yml
add github action, issue template
=> [docs]add github action

collector/src/main/java/com/usthe/collector/collect/common/cache/CacheIdentifier.java, collector/src/main/java/com/usthe/collector/collect/common/cache/CommonCache.java, collector/src/main/java/com/usthe/collector/collect/database/JdbcCommonCollect.java
=> [collector]fix 由于链接复用不佳造成创建过多链接监控异常

collector/src/main/java/com/usthe/collector/collect/common/cache/CommonCache.java, manager/src/main/java/com/usthe/manager/controller/MonitorsController.java, web-app/src/app/layout/basic/widgets/search.component.ts
=> [manager,webapp]fix 页面全局监控搜索结果异常

manager/src/main/java/com/usthe/manager/controller/MonitorsController.java, web-app/src/app/layout/basic/widgets/search.component.ts, web-app/src/app/routes/alert/alert-center/alert-center.component.html, web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html, web-app/src/app/routes/monitor/monitor-list/monitor-list.component.ts, web-app/src/app/service/monitor.service.ts
=> [manager,webapp]feature 监控列表支持过滤搜索

collector/src/main/java/com/usthe/collector/collect/database/JdbcCommonCollect.java, common/src/main/java/com/usthe/common/entity/job/protocol/JdbcProtocol.java, manager/src/main/resources/define/app/mysql.yml, manager/src/main/resources/define/param/mysql.yml
=> feat: 标签扩展：新增mysql查询超时设置 #18

collector/src/main/java/com/usthe/collector/collect/database/JdbcCommonCollect.java, common/src/main/java/com/usthe/common/entity/job/protocol/JdbcProtocol.java, manager/src/main/resources/define/app/mariadb.yml, manager/src/main/resources/define/app/mysql.yml, manager/src/main/resources/define/app/postgresql.yml, manager/src/main/resources/define/param/mariadb.yml, manager/src/main/resources/define/param/mysql.yml, manager/src/main/resources/define/param/postgresql.yml
fix jdbc解析timeout格式异常 ref #34 
mariadb支持timeout 
postgresql 支持timeout
=> [manager,collector]mariadb,postgresql支持timeout,fix jdbc解析异常

collector/pom.xml, collector/src/main/java/com/usthe/collector/collect/database/JdbcCommonCollect.java, collector/src/main/java/com/usthe/collector/dispatch/MetricsCollect.java, manager/src/main/resources/define/app/sqlserver.yml, manager/src/main/resources/define/param/mariadb.yml, manager/src/main/resources/define/param/sqlserver.yml, warehouse/src/main/java/com/usthe/warehouse/store/TdEngineDataStorage.java
支持microsoft sqlserver数据库监控类型
数据库基本信息 性能计数器信息 连接数信息。
=> [collector,manager]feature 支持microsoft sqlserver数据库监控类型

collector/src/main/java/com/usthe/collector/collect/database/JdbcSpiLoader.java, collector/src/main/resources/META-INF/spring.factories
解决各个数据库JDBC驱动并发注册加载时，由于spi机制造成的死锁
=> [collector]fix jdbc spi并发加载死锁

collector/src/main/java/com/usthe/collector/collect/common/ssh/CommonSshClient.java, collector/src/main/java/com/usthe/collector/collect/ssh/SshCollectImpl.java, collector/src/main/java/com/usthe/collector/util/KeyPairUtil.java, common/src/main/java/com/usthe/common/entity/job/protocol/SshProtocol.java, common/src/main/java/com/usthe/common/entity/manager/Param.java, manager/src/main/resources/define/app/linux.yml, manager/src/main/resources/define/param/linux.yml, script/docker-compose/conf/sql/schema.sql, script/docker-compose/conf/sureness.yml, script/sql/schema.sql
linux监控支持设置超时时间，默认6000毫秒
对Linux链接进行保活心跳，尽可能复用有效链接
=> [manager,collector]feature linux监控支持设置超时时间

collector/src/main/java/com/usthe/collector/collect/common/http/CommonHttpClient.java, collector/src/main/java/com/usthe/collector/util/KeyPairUtil.java
=> feature 检测网站SSL证书是否过期

manager/src/main/resources/define/app/api.yml, manager/src/main/resources/define/param/A-example.yml, manager/src/main/resources/define/param/api.yml, web-app/src/app/shared/components/key-value-input/key-value-input.component.less
feature:api monitor support http headers config
we can config http headers in [api monitor] now!
=> [manager,webapp]feature:api monitor support http headers

collector/src/main/java/com/usthe/collector/dispatch/timer/WheelTimerTask.java, manager/src/main/resources/define/app/api.yml, manager/src/main/resources/define/param/api.yml
feature:api monitor support query params
like this.
=> [monitor]feature:api monitor support query params

manager/src/main/resources/define/app/api.yml, manager/src/main/resources/define/app/website.yml, manager/src/main/resources/define/param/api.yml, manager/src/main/resources/define/param/website.yml
[api monitor,website monitor ] support basic auth, digest auth.   
like this.
=> [monitor]feature:[api,website] support basic,digest auth

web-app/src/app/routes/monitor/monitor-edit/monitor-edit.component.html, web-app/src/app/routes/monitor/monitor-edit/monitor-edit.component.ts, web-app/src/app/routes/monitor/monitor-new/monitor-new.component.html, web-app/src/app/routes/monitor/monitor-new/monitor-new.component.ts
http port follows ssl change
- ssl enable: port 443  
- ssl disable: port 80
=> [webapp]feature:http port follows ssl change

warehouse/src/main/java/com/usthe/warehouse/store/TdEngineDataStorage.java
Before, the Tdengine database was a required dependency service. 
Hertzbeat need tdengine to store metrics history，hertzbeat can not up when tdengine down. 
Now we make tdengine optional, not required, when tdengine is down, the only metrics history is down.
the log will show like this:   
```
2022-04-04 11:42:07 [main] ERROR com.usthe.warehouse.store.TdEngineDataStorage - 
------------------WARN WARN WARN------------------
---------------Init TdEngine Failed---------------
---------------Init TdEngine Failed---------------
--------------Please Config Tdengine--------------
----------Can Not Use Metric History Now----------
----------Can Not Use Metric History Now----------
----------Can Not Use Metric History Now----------
```
the metrics history ui will can not show data:
=> [warehouse]feature:make tdengine optional, not required

alerter/src/main/java/com/usthe/alert/calculate/CalculateAlarm.java, collector/src/main/java/com/usthe/collector/dispatch/CommonDispatcher.java, collector/src/main/java/com/usthe/collector/dispatch/MetricsCollect.java
fix linux, database monitors always timeout alert #66
=> [collector,alerter]bugfix:monitors always timeout alert

collector/src/main/java/com/usthe/collector/collect/common/http/CommonHttpClient.java
feature:enable auto redirect when 301 302 http status code
=> [collector]feature:enable auto redirect when 301 302 http code

collector/src/main/java/com/usthe/collector/collect/http/HttpCollectImpl.java, collector/src/main/java/com/usthe/collector/util/CollectUtil.java, collector/src/main/java/com/usthe/collector/util/CollectorConstants.java, common/src/main/java/com/usthe/common/entity/job/protocol/HttpProtocol.java, manager/src/main/resources/define/app/api.yml, manager/src/main/resources/define/app/website.yml, manager/src/main/resources/define/param/api.yml, manager/src/main/resources/define/param/website.yml
[website api] monitor support keyword match counts
like this.
=> [manager]feature:[website api]monitor support keyword match

collector/src/main/java/com/usthe/collector/dispatch/MetricsCollect.java, common/src/main/java/com/usthe/common/util/CommonUtil.java, common/src/test/java/com/usthe/common/util/CommonUtilTest.java, manager/src/main/resources/define/app/linux.yml
feature:support linux cpu usage,memory usage,disk free 
like this:
=> [monitor]feature:support linux cpu usage,memory usage,disk free

collector/src/main/java/com/usthe/collector/dispatch/entrance/internal/CollectJobService.java, collector/src/main/java/com/usthe/collector/dispatch/timer/TimerDispatch.java, common/src/main/java/com/usthe/common/entity/manager/Monitor.java, common/src/main/java/com/usthe/common/util/SnowFlakeIdGenerator.java, manager/src/main/java/com/usthe/manager/controller/MonitorsController.java, manager/src/main/java/com/usthe/manager/controller/NoticeConfigController.java, manager/src/main/java/com/usthe/manager/dao/MonitorDao.java, manager/src/main/java/com/usthe/manager/service/MonitorService.java, manager/src/main/java/com/usthe/manager/service/NoticeConfigService.java, manager/src/main/java/com/usthe/manager/service/impl/MonitorServiceImpl.java, manager/src/main/java/com/usthe/manager/service/impl/NoticeConfigServiceImpl.java
Delete notification operation compatibility query is empty
When the delete query is empty, you will be prompted to check the corresponding parameters
=> [manager]feature: zh and en annotations for code, delete notification when edit query is empty

web-app/src/app/layout/basic/widgets/notify.component.ts, web-app/src/app/routes/alert/alert-center/alert-center.component.html, web-app/src/app/routes/alert/alert-center/alert-center.component.ts, web-app/src/app/routes/dashboard/dashboard.component.ts, web-app/src/app/service/alert.service.ts
bugfix: filter is missing when alert-center pageSize change
=> [web-app]bugfix: filter is missing when alert-center pageSize change

home/docs/start/docker-deploy.md, home/docs/start/package-deploy.md, home/i18n/en/docusaurus-plugin-content-blog/options.json, manager/src/main/resources/sureness.yml, script/docker-compose/conf/sureness.yml, script/sureness.yml, web-app/src/app/core/interceptor/default.interceptor.ts
support roles permission, admin-user-guest
default account admin has [admin] role, can add , edit, view ,delete
default account tom has [user] role, can add, edit, view
default account guest has [guest] role, only can view
=> [monitor]feature: support roles permission, admin-user-guest

common/src/main/java/com/usthe/common/entity/manager/ParamDefine.java, manager/src/main/java/com/usthe/manager/controller/AccountController.java, manager/src/main/java/com/usthe/manager/controller/AppController.java, manager/src/main/java/com/usthe/manager/dao/ParamDefineDao.java, manager/src/main/java/com/usthe/manager/pojo/dto/Hierarchy.java, manager/src/main/java/com/usthe/manager/pojo/dto/LoginDto.java, manager/src/main/java/com/usthe/manager/service/AppService.java
add: App/Account Controller compatible with Chinese and English
=> feat: [manager]feature:App/Account Controller compatible with Chinese and English

web-app/src/app/layout/basic/basic.component.ts, web-app/src/app/routes/alert/alert-center/alert-center.component.html, web-app/src/app/routes/alert/alert-notice/alert-notice.component.html, web-app/src/app/routes/alert/alert-setting/alert-setting.component.html, web-app/src/app/routes/dashboard/dashboard.component.html, web-app/src/app/routes/dashboard/dashboard.component.ts, web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html, web-app/src/app/routes/routes-routing.module.ts, web-app/src/app/routes/routes.module.ts
recently alerts in dashboard load error when go back 
fix #100
=> [web-app]bugfix: recently alerts in dashboard load error when go back

collector/src/main/java/com/usthe/collector/collect/AbstractCollect.java, collector/src/main/java/com/usthe/collector/dispatch/CollectDataDispatch.java, collector/src/main/java/com/usthe/collector/dispatch/CommonDispatcher.java, collector/src/main/java/com/usthe/collector/dispatch/DispatchConstants.java, collector/src/main/java/com/usthe/collector/dispatch/DispatchProperties.java, collector/src/main/java/com/usthe/collector/dispatch/MetricsCollect.java, collector/src/main/java/com/usthe/collector/dispatch/MetricsCollectorQueue.java, collector/src/main/java/com/usthe/collector/dispatch/MetricsTaskDispatch.java, collector/src/main/java/com/usthe/collector/dispatch/WorkerPool.java, manager/src/main/java/com/usthe/manager/config/AngularErrorViewResolver.java, manager/src/main/java/com/usthe/manager/config/HeaderRequestInterceptor.java, manager/src/main/java/com/usthe/manager/controller/I18nController.java, manager/src/main/java/com/usthe/manager/service/impl/AppServiceImpl.java
=> feat: [collector,manager]feature:I18N Support  #wqh

manager/src/main/resources/define/app/elasticsearch.yml, manager/src/main/resources/define/param/elasticsearch.yml
Add preliminary monitoring indicators of elasticsearch cluster
=> feat: [manager]feature: ElasticSearch cluster support

collector/src/main/java/com/usthe/collector/dispatch/MetricsCollect.java
bugfix: expression evaluation error when value with spaces
=> [collector]bugfix: expression evaluation error when value with spaces

collector/src/main/java/com/usthe/collector/collect/ssh/SshCollectImpl.java, manager/src/main/resources/define/app/elasticsearch.yml, manager/src/main/resources/define/app/zookeeper.yml, manager/src/main/resources/define/param/elasticsearch.yml, manager/src/main/resources/define/param/zookeeper.yml, web-app/src/assets/app-data.json
Added zookeeper and middleware page support
=> feature: Added zookeeper and middleware page support

CONTRIBUTING.md, manager/src/main/java/com/usthe/manager/service/impl/MonitorServiceImpl.java, web-app/src/app/routes/monitor/monitor-edit/monitor-edit.component.ts, web-app/src/app/routes/monitor/monitor-new/monitor-new.component.ts
bugfix: fix error when tags duplicate in monitor
=> [manager,webapp]bugfix: error when tags duplicate in monitor

manager/src/main/resources/define/app/centos.yml, manager/src/main/resources/define/app/ubuntu.yml, manager/src/main/resources/define/param/centos.yml, manager/src/main/resources/define/param/ubuntu.yml
feature: support ubuntu linux and centos linux monitoring
- ubuntu monitor
- centos monitor
=> [manager]feature: support ubuntu linux and centos linux monitoring

alerter/src/main/java/com/usthe/alert/AlerterProperties.java, alerter/src/main/java/com/usthe/alert/calculate/CalculateAlarm.java, common/src/main/java/com/usthe/common/entity/alerter/Alert.java, manager/src/main/java/com/usthe/manager/component/alerter/impl/DingTalkRobotAlertNotifyHandlerImpl.java, manager/src/main/java/com/usthe/manager/component/alerter/impl/FlyBookAlertNotifyHandlerImpl.java, manager/src/main/java/com/usthe/manager/component/alerter/impl/WeWorkRobotAlertNotifyHandlerImpl.java, manager/src/main/java/com/usthe/manager/service/impl/MailServiceImpl.java, manager/src/main/java/com/usthe/manager/service/impl/NoticeConfigServiceImpl.java, manager/src/main/resources/templates/mailAlarm.html, script/sql/schema.sql, web-app/src/app/core/interceptor/default.interceptor.ts, web-app/src/app/layout/basic/widgets/notify.component.ts, web-app/src/app/pojo/Alert.ts, web-app/src/app/routes/alert/alert-center/alert-center.component.html, web-app/src/app/routes/alert/alert-center/alert-center.component.ts, web-app/src/app/routes/dashboard/dashboard.component.html
support alert nextEvalInterval. Ignore alert when happen again in eval interval.
support alert triggerTime, send triggerTime attribute when alert notify.
=> [monitor]feature: support alert nextEvalInterval, triggerTime. Ignore alert when happen again in eval interval.

manager/src/main/java/com/usthe/manager/controller/AppController.java, web-app/src/app/routes/alert/alert-setting/alert-setting.component.ts, web-app/src/app/service/app-define.service.ts
support alert define appHierarchy i18n
=> [manager,webapp]feature: support alert define appHierarchy i18n

alerter/src/main/java/com/usthe/alert/calculate/CalculateAlarm.java, common/src/main/java/com/usthe/common/util/ResourceBundleUtil.java, home/blog/2022-05-17-hertzbeat-v1.0-beta.8.md, home/docs/start/docker-deploy.md
fix load resource bundle error when local is en.HK
=> [monitor]bugfix: fix load resource bundle error when local en.HK

alerter/src/main/java/com/usthe/alert/calculate/CalculateAlarm.java, home/docs/help/zookeeper.md
Feature add zookeeper help Doc
=> Feature add zookeeper help Doc

collector/src/main/java/com/usthe/collector/dispatch/export/MetricsDataExporter.java
bugfix: fix warehouse data queue consume error
fix link issue #152 https://github.com/dromara/hertzbeat/issues/119
=> [collector]bugfix: fix warehouse data queue consume error

web-app/src/app/layout/basic/basic.component.ts, web-app/src/app/layout/passport/passport.component.html, web-app/src/app/layout/passport/passport.component.ts, web-app/src/app/routes/alert/alert-center/alert-center.component.ts, web-app/src/app/routes/monitor/monitor-data-chart/monitor-data-chart.component.spec.ts, web-app/src/app/routes/monitor/monitor-new/monitor-new.component.ts, web-app/src/app/routes/setting/setting.module.ts, web-app/src/app/routes/setting/tags/tags.component.spec.ts, web-app/src/app/routes/setting/tags/tags.component.ts, web-app/src/app/shared/components/key-value-input/key-value-input.component.spec.ts, web-app/src/app/shared/consts.ts, web-app/src/polyfills.ts, web-app/src/styles/theme.less
fix input blocking when input error in dark theme 
issue https://github.com/dromara/hertzbeat/issues/133
=> [web-app]bugfix:fix input blocking when input error in dark theme

collector/src/main/java/com/usthe/collector/collect/common/cache/CacheIdentifier.java, collector/src/main/java/com/usthe/collector/collect/common/cache/CommonCache.java
handle sensitive information such as account and password in log
=> [collector]handle sensitive info such as account and password in log

manager/src/main/resources/define/app/oracle.yml
fix oracle config yml percentage error
=> [manager]fix oracle config yml percentage error

common/src/main/java/com/usthe/common/entity/manager/ParamDefine.java, home/blog/2022-06-01-hertzbeat-v1.0.md, manager/src/main/java/com/usthe/manager/service/impl/AppServiceImpl.java, manager/src/main/resources/define/param/A-example.yml, manager/src/main/resources/define/param/api.yml, manager/src/main/resources/define/param/centos.yml, manager/src/main/resources/define/param/elasticsearch.yml, manager/src/main/resources/define/param/fullsite.yml, manager/src/main/resources/define/param/linux.yml, manager/src/main/resources/define/param/mariadb.yml, manager/src/main/resources/define/param/mysql.yml, manager/src/main/resources/define/param/oracle.yml, manager/src/main/resources/define/param/ping.yml, manager/src/main/resources/define/param/port.yml, manager/src/main/resources/define/param/postgresql.yml, manager/src/main/resources/define/param/redis.yml, manager/src/main/resources/define/param/sqlserver.yml, manager/src/main/resources/define/param/ubuntu.yml, manager/src/main/resources/define/param/website.yml, manager/src/main/resources/define/param/zookeeper.yml, web-app/src/app/routes/monitor/monitor-edit/monitor-edit.component.ts, web-app/src/app/routes/monitor/monitor-new/monitor-new.component.ts
support monitor params name i18n
=> [manager]support monitor params name i18n

script/docker/server/Dockerfile, script/docker/server/README.md
build multi cpu arch hertzbeat docker version
support amd64 arm64
=> [script]build multi cpu arch hertzbeat docker version

common/src/main/java/com/usthe/common/entity/alerter/Alert.java, common/src/main/java/com/usthe/common/entity/alerter/AlertDefine.java, common/src/main/java/com/usthe/common/entity/alerter/AlertDefineMonitorBind.java, common/src/main/java/com/usthe/common/entity/manager/Monitor.java, common/src/main/java/com/usthe/common/entity/manager/NoticeReceiver.java, common/src/main/java/com/usthe/common/entity/manager/NoticeRule.java, common/src/main/java/com/usthe/common/entity/manager/Param.java, common/src/main/java/com/usthe/common/entity/manager/ParamDefine.java, common/src/main/java/com/usthe/common/entity/manager/Tag.java, common/src/main/java/com/usthe/common/entity/manager/TagMonitorBind.java
database tables append prefix hzb_ 
#165
=> [monitor]database tables append prefix hzb_

manager/src/main/java/com/usthe/manager/component/alerter/impl/DingTalkRobotAlertNotifyHandlerImpl.java, manager/src/main/java/com/usthe/manager/component/alerter/impl/EmailAlertNotifyHandlerImpl.java, manager/src/main/java/com/usthe/manager/component/alerter/impl/FlyBookAlertNotifyHandlerImpl.java, manager/src/main/java/com/usthe/manager/component/alerter/impl/WeWorkRobotAlertNotifyHandlerImpl.java, manager/src/main/resources/templates/mailAlarm.html
change notify brand tancloud to hertzbeat
=> [manager]change notify brand tancloud to hertzbeat

collector/src/main/java/com/usthe/collector/dispatch/CommonDispatcher.java, collector/src/main/java/com/usthe/collector/dispatch/timer/WheelTimerTask.java, collector/src/main/java/com/usthe/collector/util/CollectUtil.java, common/pom.xml, common/src/main/java/com/usthe/common/config/CommonConfig.java, common/src/main/java/com/usthe/common/config/CommonProperties.java, common/src/main/java/com/usthe/common/util/AesUtil.java, common/src/main/resources/META-INF/spring.factories, manager/src/main/java/com/usthe/manager/controller/I18nController.java, manager/src/main/java/com/usthe/manager/pojo/dto/LoginDto.java, manager/src/main/resources/application.yml, manager/src/main/resources/define/app/A-example2.yml, manager/src/main/resources/define/param/A-example2.yml, warehouse/src/main/java/com/usthe/warehouse/controller/MetricsDataController.java, warehouse/src/main/java/com/usthe/warehouse/store/TdEngineDataStorage.java
[monitor] feature support use pre collect metrics data to replace next metrics config params
[monitor] feature support stream collect example type, custom aes secretKey
=> [monitor] support use pre collect metrics data to replace next metrics config params

alerter/src/main/java/com/usthe/alert/service/impl/AlertServiceImpl.java
=> fix time zone todo issue

alerter/src/main/java/com/usthe/alert/calculate/CalculateAlarm.java, collector/src/main/java/com/usthe/collector/dispatch/MetricsCollect.java, common/src/main/java/com/usthe/common/util/CommonUtil.java, warehouse/src/main/java/com/usthe/warehouse/WarehouseProperties.java, warehouse/src/main/java/com/usthe/warehouse/controller/MetricsDataController.java, warehouse/src/main/java/com/usthe/warehouse/store/TdEngineDataStorage.java
[warehouse] support custom tdengine tableStrColumnDefineMaxLength
[monitor] feature update numeric metrics all contain decimal points
=> [monitor] feature update numeric metrics all contain decimal points

web-app/src/app/routes/alert/alert-center/alert-center.component.html, web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html
feature:toggle [enable and cancel] button
#209
=> [web-app]feature:toggle [enable and cancel] button

home/docs/start/mysql-init.md
=> [home] update mysql-init spring.datasource.url

collector/src/main/java/com/usthe/collector/collect/AbstractCollect.java, collector/src/main/java/com/usthe/collector/collect/common/cache/JmxConnect.java, collector/src/main/java/com/usthe/collector/collect/jmx/JmxCollectImpl.java, collector/src/main/java/com/usthe/collector/dispatch/DispatchConstants.java, collector/src/main/java/com/usthe/collector/dispatch/MetricsCollect.java, common/src/main/java/com/usthe/common/entity/job/Metrics.java, common/src/main/java/com/usthe/common/entity/job/protocol/JmxProtocol.java, manager/src/main/resources/define/app/tomcat.yml, manager/src/main/resources/define/param/tomcat.yml
=> Feature support jmx

collector/src/main/java/com/usthe/collector/dispatch/timer/TimerDispatcher.java
[collector] bugfix: Solve imprecise cyclicJob execution interval problem.
1.wheelTimer tickDuration from 10s changed to 1s,ticksPerWheel remain unchanged.
2.now support second level job interval.
=> [collector] bugfix: Solve imprecise cyclicJob execution interval problem.

home/docs/advanced/extend-http-jsonpath.md
=> [docs] fix extend-http-jsonpath.md parseScript error

home/src/pages/index.js
=> [webapp] auto redirect url when detect browser language 

common/pom.xml, common/src/main/java/com/usthe/common/util/IpDomainUtil.java
[common]feature:use "apache.http.conn.util" replace "sun.net.util" for upgrading java version
=> [common]feature:use "apache.http.conn.util" replace "sun.net.util" for upgrading java version

alerter/pom.xml, alerter/src/main/java/com/usthe/alert/calculate/CalculateAlarm.java, collector/pom.xml, common/pom.xml, manager/pom.xml, pom.xml, warehouse/pom.xml
=> Feature change main pom artifactId 

alerter/src/main/java/com/usthe/alert/AlerterProperties.java, alerter/src/main/java/com/usthe/alert/AlerterWorkerPool.java, alerter/src/main/java/com/usthe/alert/calculate/CalculateAlarm.java, alerter/src/main/java/com/usthe/alert/controller/AlertDefineController.java, alerter/src/main/java/com/usthe/alert/controller/AlertDefinesController.java, alerter/src/main/java/com/usthe/alert/controller/AlertsController.java, alerter/src/main/java/com/usthe/alert/dao/AlertDao.java, alerter/src/main/java/com/usthe/alert/dao/AlertDefineDao.java, alerter/src/main/java/com/usthe/alert/dao/AlertMonitorDao.java, alerter/src/main/java/com/usthe/alert/service/AlertDefineService.java, alerter/src/main/java/com/usthe/alert/service/AlertService.java, alerter/src/main/java/com/usthe/alert/service/impl/AlertDefineServiceImpl.java, alerter/src/main/java/com/usthe/alert/service/impl/AlertServiceImpl.java, alerter/src/main/java/com/usthe/alert/util/AlertTemplateUtil.java
=> [alerter] added code comments in English

alerter/src/main/java/com/usthe/alert/AlerterProperties.java, alerter/src/main/java/com/usthe/alert/AlerterWorkerPool.java, alerter/src/main/java/com/usthe/alert/calculate/CalculateAlarm.java, alerter/src/main/java/com/usthe/alert/controller/AlertDefineController.java, alerter/src/main/java/com/usthe/alert/controller/AlertDefinesController.java, alerter/src/main/java/com/usthe/alert/controller/AlertsController.java, alerter/src/main/java/com/usthe/alert/dao/AlertDao.java, alerter/src/main/java/com/usthe/alert/dao/AlertDefineDao.java, alerter/src/main/java/com/usthe/alert/dao/AlertMonitorDao.java, alerter/src/main/java/com/usthe/alert/service/AlertDefineService.java, alerter/src/main/java/com/usthe/alert/service/AlertService.java, alerter/src/main/java/com/usthe/alert/service/impl/AlertDefineServiceImpl.java, alerter/src/main/java/com/usthe/alert/service/impl/AlertServiceImpl.java, alerter/src/main/java/com/usthe/alert/util/AlertTemplateUtil.java, manager/src/test/java/com/usthe/manager/controller/AppControllerTest.java
AppControllerTest Test class writing and pass the test
=> Test class writing

manager/src/test/java/com/usthe/manager/dao/NoticeRuleDaoTest.java, manager/src/test/java/com/usthe/manager/dao/ParamDaoTest.java, manager/src/test/java/com/usthe/manager/dao/ParamDefineDaoTest.java, manager/src/test/java/com/usthe/manager/dao/TagDaoTest.java
impl unit test case #359 #360 #361 #362
=> [manger] add mockito unit test

manager/src/test/java/com/usthe/manager/controller/I18nControllerTest.java, manager/src/test/java/com/usthe/manager/controller/MonitorControllerTest.java
I18nControllerTest and MonitorControllerTest Unit tests are written
=> [manager] I18nControllerTest and MonitorControllerTest Unit tests are written

manager/src/test/java/com/usthe/manager/controller/MonitorsControllerTest.java
The test class has been written and passed the test
=> MonitorsControllerTest Test class is written

manager/src/main/resources/application.yml, warehouse/src/main/java/com/usthe/warehouse/WarehouseProperties.java, warehouse/src/main/java/com/usthe/warehouse/store/HistoryIotDbDataStorage.java
IoTDB保存的数据设置过期时间，已在0.13.2、012.6和0.11版本进行测试
=> add IoTDB save data expire time config

manager/src/test/java/com/usthe/manager/controller/SummaryControllerTest.java
The test class is written and the test is completed
=> SummaryControllerTest Test class  writing completed

manager/pom.xml, manager/src/main/resources/application.yml
1. fix bypassing api auth bug. 
2. upgrade sureness v1.0.8 
3. fix https://github.com/dromara/hertzbeat/issues/288
=> [manager] upgrade sureness v1.0.8 to fix bypassing api auth bug

manager/src/test/java/com/usthe/manager/controller/TagControllerTest.java
The test class is written and passed the test
=> TagControllerTest Test class writing completed

collector/src/main/java/com/usthe/collector/dispatch/MetricsCollect.java, home/src/constants.js
=> update commit user.name and user.email

warehouse/src/main/java/com/usthe/warehouse/store/HistoryIotDbDataStorage.java
=> end The query closed the dataSet

warehouse/src/test/java/com/usthe/warehouse/controller/MetricsDataControllerTest.java
Add unit test MetricsDataControllerTest.java
fixes #406
=> [#406][warehose] Add unit test MetricsDataControllerTest.java

manager/src/test/java/com/usthe/manager/service/NoticeConfigServiceTest.java
Add unit test manager/service/NoticeConfigServiceTest.java
fix #358
=> [#358][manager] Add unit test manager/service/NoticeConfigServiceTest.java

manager/src/test/java/com/usthe/manager/service/MailServiceTest.java, manager/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
=> [#356][manager] unit test case of manager/service/MailServiceTest.java

manager/src/main/java/com/usthe/manager/service/impl/MonitorServiceImpl.java, manager/src/main/resources/application-test.yml
bugfix the gmtUpdate time not change when update monitor params
=> [manager] bugfix the gmtUpdate not change when update monitor param

home/i18n/en/docusaurus-plugin-content-docs/current/start/package-deploy.md
fix up:update the environment  of hertzbeat to Java version 11.
=> [doc] fix up:update the environment of hertzbeat to Java version 11

home/docs/help/kubernetes.md
=> [docs] update kubernetes.md

manager/src/main/resources/define/app/app-ubuntu.yml
修复了在ubuntu20.04系统下，cpu使用率显示不准确的问题。
=> [manager] bugfix linux cpu usage collect incorrect sometime

collector/src/main/java/com/usthe/collector/dispatch/CommonDispatcher.java
limit trigger sub task max num 50
=> [collector] limit trigger sub task max num

alerter/src/main/java/com/usthe/alert/controller/AlertsController.java
fix: Remove Alert Unused Monitoring IDs  #wqh
=> fix: Remove Alert Unused Monitoring IDs 

collector/src/main/java/com/usthe/collector/collect/mongodb/MongodbSingleCollectImpl.java, manager/src/main/resources/define/app/app-mongodb.yml
重构 MongodbSingleCollectImpl, 添加了 mongodb Diagnostic Commands 的通用支持
=> Mongodb feature extended

manager/src/test/java/com/usthe/manager/service/MonitorServiceTest.java
=> [manager] add monitor service UT (#357)

home/docs/help/dynamic_tp.md
=> add dynamic-tp metrics desc

home/docs/help/zookeeper.md
=> [docs] update zookeeper port desc doc

manager/src/main/resources/define/app/app-clickhouse.yml, manager/src/main/resources/define/app/app-mysql.yml, manager/src/main/resources/define/param/param-clickhouse.yml
@orangeyts hi jerry, i update clickhouse base your pr #179 . - add ping metrics and rename metrics name(due it's can not has `.`, it will cause history chart does not has data). Please review and approve this. thanks!
=> [manager] add ping_available in clickhouse monitoring, add instance

home/docs/start/mysql-change.md
按文档操作，hertzbeat库编码不是utf8mb4，插入SQL包含中文GenericJDBCException异常问题
=> [docs] fix insert SQL contains Chinese throw GenericJDBCException;

collector/src/main/java/com/usthe/collector/collect/common/cache/MongodbConnect.java, collector/src/main/java/com/usthe/collector/collect/database/JdbcCommonCollect.java, collector/src/main/java/com/usthe/collector/collect/mongodb/MongodbSingleCollectImpl.java, common/src/main/java/com/usthe/common/entity/job/protocol/MongodbProtocol.java, manager/pom.xml, manager/src/main/resources/define/app/app-mongodb.yml, manager/src/main/resources/logback-spring.xml, web-app/src/app/routes/monitor/monitor-detail/monitor-detail.component.html
- reuse connect MongoClient when collect mongodb metrics data
- rename metrics name to fix historical chart no data. Due metrics name can not contain `.`
=> [collector,manager] reuse connect in mongodb collect, fix historical chart no data

alerter/src/test/java/com/usthe/alert/controller/AlertDefinesControllerTest.java
=> alerter模块下的AlertDefinesController控制器的测试类

collector/src/test/java/com/usthe/collector/util/KeyPairUtilTest.java
=> [unit test] Add unit test cases for KeyPairUtil

alerter/src/test/java/com/usthe/alert/service/AlertDefineServiceTest.java
[Task] <Unit Test Case> com/usthe/alert/service/AlertDefineService.java #625
=> [test]feature:add AlertDefineService test

alerter/src/test/java/com/usthe/alert/util/AlertTemplateUtilTest.java
=> [unit test] Add unit test cases for AlertTemplateUtil

alerter/src/test/java/com/usthe/alert/AlerterWorkerPoolTest.java, warehouse/src/test/java/com/usthe/warehouse/WarehouseWorkerPoolTest.java
This PR provide a refactoring of the class `AlerterWorkerPoolTest.java`
=> Refactoring of the class test AlerterWorkerPoolTest

pom.xml
- Add spring boot version into properties section in the `pom.xml` file
- Reorder the list of properties alphabetically
Issue: https://github.com/dromara/hertzbeat/issues/651
=> The version of Spring Boot should be put in properties

home/src/constants.js
新增中微子代理(dromara/neutrino-proxy)外链
=> 新增中微子代理(dromara/neutrino-proxy)外链

collector/src/main/java/com/usthe/collector/collect/redis/RedisClusterCollectImpl.java, collector/src/main/java/com/usthe/collector/collect/redis/RedisSingleCollectImpl.java, manager/src/main/resources/define/app/app-redis.yml, manager/src/main/resources/define/app/app-redis_cluster.yml
1、Optimize the redis info command to obtain the corresponding info information according to the metrics name
2、Add redis command statistics
=> [task]feature:Optimize Redis info [section] and Add Redis command statistics

collector/src/main/java/com/usthe/collector/dispatch/entrance/internal/CollectJobService.java, collector/src/main/java/com/usthe/collector/dispatch/timer/TimerDispatcher.java, manager/src/main/java/com/usthe/manager/service/impl/MonitorServiceImpl.java, manager/src/test/java/com/usthe/manager/service/MonitorServiceTest.java
- bugfix repetitive collect tasks. 
- reduce init mem size
=> bugfix repetitive collect tasks, reduce init mem size

home/docs/help/redis.md, home/sidebars.json
=> [document]add redis help document

collector/src/main/java/com/usthe/collector/dispatch/MetricsCollect.java
=> [task]Filter empty fields

collector/src/main/java/com/usthe/collector/dispatch/MetricsCollect.java
=> [collector] bugfix metrics has a lot of repetition fields

alerter/pom.xml, common/pom.xml, manager/pom.xml, warehouse/pom.xml
Convert version into properties in the **pom.xml** files and reorder it alphabetically
Associated issue is: https://github.com/dromara/hertzbeat/issues/667
=> Convert version into properties

web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html
=> [webapp] fix applist delete button display

manager/src/main/resources/application.yml, warehouse/pom.xml, warehouse/src/main/java/com/usthe/warehouse/config/IotDbVersion.java, warehouse/src/main/java/com/usthe/warehouse/config/WarehouseProperties.java, warehouse/src/main/java/com/usthe/warehouse/store/HistoryIotDbDataStorage.java
deprecated 0.12.* iotdb, support 1.0.* iotdb
=> support v1.0.+ iotdb

manager/src/main/resources/define/app-windows.yml
windows  cpu metrics no such objects
=> [bugfix]delete window cpu metrics

web-app/src/app/pojo/Monitor.ts, web-app/src/app/routes/alert/alert-setting/alert-setting.component.html
=> [webapp] change default monitor intervals 120s to 60s

home/i18n/en/docusaurus-plugin-content-docs/current/help/kubernetes.md
Update kubernetes.md to add "method two".
=> [home,i18n] Update kubernetes.md

collector/src/main/java/com/usthe/collector/collect/http/HttpCollectImpl.java, common/src/main/java/com/usthe/common/queue/impl/InMemoryCommonDataQueue.java, manager/src/main/java/com/usthe/manager/controller/MetricsController.java, manager/src/main/resources/application.yml, manager/src/main/resources/define/app-hertzbeat.yml, manager/src/main/resources/define/app-hertzbeat_token.yml, manager/src/main/resources/define/app-springboot2.yml, manager/src/main/resources/sureness.yml, script/application.yml, script/docker-compose/hertzbeat-mysql-iotdb/conf/application.yml, script/docker-compose/hertzbeat-mysql-tdengine/conf/application.yml
- support inner metrics data api 
- expose metrics actuator api
=> support and expose inner metrics data

manager/src/main/resources/define/app-mysql.yml
add: app-mysql.yml internationalization notes #769
=> pref: app-mysql.yml internationalization notes

manager/src/main/resources/define/app-nacos.yml
=> <Monitoring define yml comment translation> (Issue #769)

manager/src/main/resources/define/app-springboot2.yml, manager/src/main/resources/define/app-springboot3.yml
add springboot2,springboot3 define yml comment translation
=> add springboot2,springboot3 define yml comment translation

manager/src/main/resources/define/app-hertzbeat.yml
I just finish translating define yml about hertzbeat.Please review the code and give me some advice.
=> Translate define yml about hertzbeat by moshu which issue about #769

manager/src/main/resources/define/app-jetty.yml
=> update app-jetty.yml comment

manager/src/main/resources/define/app-clickhouse.yml
=> update app-clickhouse.yml comment

manager/src/main/resources/define/app-redis.yml
=> [task#769]add app-redis.yml translate

warehouse/pom.xml, warehouse/src/main/java/com/usthe/warehouse/store/HistoryGrepTimeDbDataStorage.java
[code]feature: add GrepTimeDb `getHistoryMetricData`
=> [code]feature: add GrepTimeDb `getHistoryMetricData`

warehouse/src/main/java/com/usthe/warehouse/store/HistoryGrepTimeDbDataStorage.java
1.add GrepTimeDb `createDatabase`
2.Check if the database exists; if it does not exist, create the database.
=> [warehouse]feature

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/codeql-analysis.yml, alerter/src/main/java/com/usthe/alert/service/impl/AlertServiceImpl.java
- update github CodeQL workflow
- add pr template
- fix query alertSummary's total field is 0 always
=> [script] update github workflow, add pr template

manager/src/main/resources/application.yml, manager/src/main/resources/define/app-a_example.yml, manager/src/main/resources/define/app-api.yml, manager/src/main/resources/define/app-api_code.yml, manager/src/main/resources/define/app-centos.yml, manager/src/main/resources/define/app-cisco_switch.yml, manager/src/main/resources/define/app-clickhouse.yml, manager/src/main/resources/define/app-dm.yml, manager/src/main/resources/define/app-dynamic_tp.yml, manager/src/main/resources/define/app-elasticsearch.yml, manager/src/main/resources/define/app-ftp.yml, manager/src/main/resources/define/app-hertzbeat_token.yml, manager/src/main/resources/define/app-hpe_switch.yml, manager/src/main/resources/define/app-huawei_switch.yml, manager/src/main/resources/define/app-jetty.yml, manager/src/main/resources/define/app-linux.yml, manager/src/main/resources/define/app-mariadb.yml, manager/src/main/resources/define/app-mysql.yml, manager/src/main/resources/define/app-oracle.yml, manager/src/main/resources/define/app-springboot2.yml, manager/src/main/resources/define/app-springboot3.yml, manager/src/main/resources/define/app-sqlserver.yml, manager/src/main/resources/define/app-tomcat.yml, manager/src/main/resources/define/app-tplink_switch.yml, manager/src/main/resources/define/app-ubuntu.yml, manager/src/main/resources/define/app-website.yml, script/application.yml, script/docker-compose/hertzbeat-mysql-iotdb/conf/application.yml, script/docker-compose/hertzbeat-mysql-tdengine/conf/application.yml
update monitoring app define yml
=> [script] update monitoring app define yml

home/docs/start/postgresql-change.md, script/docker-compose/README.md, script/docker-compose/hertzbeat-postgresql-iotdb/README.md, script/docker-compose/hertzbeat-postgresql-iotdb/README_CN.md, script/docker-compose/hertzbeat-postgresql-iotdb/conf/application.yml, script/docker-compose/hertzbeat-postgresql-iotdb/conf/sql/schema.sql, script/docker-compose/hertzbeat-postgresql-iotdb/conf/sureness.yml, script/docker-compose/hertzbeat-postgresql-iotdb/docker-compose.yaml
support postgresql store meta data instead of h2 database #760 
add docker-compose file for postgresql
add related docs
- [y]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [y]  I have written the necessary doc or comment.
- [y]  I have added the necessary unit tests and all cases have passed.
=> support postgresql store meta data instead of h2 database

warehouse/src/main/java/com/usthe/warehouse/store/HistoryGrepTimeDbDataStorage.java
add GrepTimeDb `getHistoryIntervalMetricData`
=> [warehouse]feature:add GrepTimeDb `getHistoryIntervalMetricData`

warehouse/src/main/java/org/dromara/hertzbeat/warehouse/store/HistoryGrepTimeDbDataStorage.java
=> [warehouse]Add support for greptimedb.

manager/src/main/resources/define/app-redis_cluster.yml
app-redis_cluster.yml translate
=> [manage]add app-redis_cluster.yml translate

manager/src/main/resources/define/app-redis_cluster.yml, manager/src/main/resources/define/app-redis_sentinel.yml
add app-redis_cluster.yml translate
=> add app-redis_cluster.yml translate

manager/src/main/resources/define/app-jvm.yml
=> add app-jvm.yml translate

alerter/src/main/java/org/dromara/hertzbeat/alert/controller/AlertsController.java
[alerter]bugfix: fix the error according to the monitorid query.
=> [alerter]bugfix: fix the error according to the monitorid query.

warehouse/src/main/java/org/dromara/hertzbeat/warehouse/store/HistoryIotDbDataStorage.java
=> [warehouse] bugfix inttIotDB collectCheck Bug

README.md, README_CN.md, collector/src/main/java/org/dromara/hertzbeat/collector/collect/snmp/SnmpCollectImpl.java, home/docs/others/huaweicloud.md, home/docusaurus.config.js, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/others/huaweicloud.md
[collector] bugfix npe when snmp walk special fields
add ArgusDBM link
=> [collector] bugfix npe when snmp walk special fields

collector/pom.xml, manager/pom.xml, manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/AbstractImExportServiceImpl.java, manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/ExcelImExportServiceImpl.java, manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/JsonImExportServiceImpl.java, manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/MonitorServiceImpl.java, web-app/_mock/README.md
[manager]import and export by excel via ExcelImExportServiceImpl.java
tips:. The request parameter needs to use type:=Excel.
todo:The front-end doesn't have an Excel version, and I hope someone can make it.
=> [manager]import and export by excel

manager/src/main/resources/define/app-h3c_switch.yml
=> support monitoring network h3c switch

manager/src/main/resources/define/app-activemq.yml, manager/src/main/resources/define/app-api.yml, manager/src/main/resources/define/app-dm.yml, manager/src/main/resources/define/app-docker.yml, manager/src/main/resources/define/app-euleros.yml, manager/src/main/resources/define/app-flink.yml, manager/src/main/resources/define/app-ftp.yml, manager/src/main/resources/define/app-fullsite.yml, manager/src/main/resources/define/app-h3c_switch.yml, manager/src/main/resources/define/app-hertzbeat_token.yml, manager/src/main/resources/define/app-iotdb.yml, manager/src/main/resources/define/app-jetty.yml, manager/src/main/resources/define/app-jvm.yml, manager/src/main/resources/define/app-kafka.yml, manager/src/main/resources/define/app-kubernetes.yml, manager/src/main/resources/define/app-mariadb.yml, manager/src/main/resources/define/app-mysql.yml, manager/src/main/resources/define/app-oracle.yml, manager/src/main/resources/define/app-postgresql.yml
support EulerOS metrics monitoring
=> support EulerOS metrics monitoring

collector/src/main/java/org/dromara/hertzbeat/collector/collect/common/cache/CommonCache.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/common/cache/JdbcConnect.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/common/cache/JmxConnect.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/common/cache/MongodbConnect.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/common/cache/RedisConnect.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/common/cache/SshConnect.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/common/ssh/CommonSshClient.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/ssh/SshCollectImpl.java, collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/CommonDispatcher.java, collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/timer/WheelTimerTask.java, manager/src/main/resources/define/app-centos.yml, manager/src/main/resources/define/app-dm.yml, manager/src/main/resources/define/app-euleros.yml, manager/src/main/resources/define/app-linux.yml, manager/src/main/resources/define/app-mariadb.yml, manager/src/main/resources/define/app-mysql.yml, manager/src/main/resources/define/app-opengauss.yml, manager/src/main/resources/define/app-oracle.yml, manager/src/main/resources/define/app-postgresql.yml, manager/src/main/resources/define/app-sqlserver.yml, manager/src/main/resources/define/app-ubuntu.yml
bugfix sshd error no more sessions sometime
=> [collector] bugfix sshd error no more sessions sometime

manager/src/main/java/org/dromara/hertzbeat/manager/config/YamlMapperConfig.java
问题图片：<img width="1398" alt="image" src="https://user-images.githubusercontent.com/36863277/233823367-9f2d0117-e1c2-477d-a3b0-b3cc616c30a3.png">
导致详情无法查看，
修复之后正常
=> 修复LocalDateTime返回前端接受为数组问题。

warehouse/src/main/java/org/dromara/hertzbeat/warehouse/store/HistoryTdEngineDataStorage.java
解决方法：使用``飘号包裹查询字段。
将查询历史纪录时，将关键字使用飘号包裹。``
将查询历史纪录时，将关键字使用飘号包裹。``
修改issue：897bug。
- [yes ]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [yes ]  I have written the necessary doc or comment.
- [ yes]  I have added the necessary unit tests and all cases have passed.
ps:项目刚刚入手，只修改了一些小bug，如若以后有SQL拼接、处理相关问题可以找我。希望可以一起建设hertzbeat。
=> [warehouse] issue:897 修改TDengine查询历史记录时关键字查询bug。

manager/src/main/java/org/dromara/hertzbeat/manager/controller/AccountController.java, manager/src/main/java/org/dromara/hertzbeat/manager/controller/AppController.java, manager/src/main/java/org/dromara/hertzbeat/manager/pojo/dto/LoginDto.java
Maximum length control for password increase
=> [bug#877]Maximum length control for password increase

manager/src/main/resources/logback-spring.xml
logback-spring.xml  Scroll to delete expired logs
=> [feature]logback-spring.xml  Scroll to delete expired logs

CONTRIBUTING.md, home/docs/help/guide.md, home/docs/others/contributing.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/others/contributing.md, warehouse/src/main/java/org/dromara/hertzbeat/warehouse/dao/HistoryDao.java, warehouse/src/main/java/org/dromara/hertzbeat/warehouse/store/HistoryJpaDatabaseDataStorage.java
reduce the amount of metrics stored by jpa
=> [warehouse] reduce the amount of metrics stored by jpa

manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/DingTalkRobotAlertNotifyHandlerImpl.java, web-app/src/app/routes/alert/alert-silence/alert-silence.component.html
bugfix http header content-type error when send dingtalk message
=> bugfix http header content-type error when send dingtalk message

collector/src/main/java/org/dromara/hertzbeat/collector/collect/redis/RedisCommonCollectImpl.java
=> bugfix redis collections out of bounds

alerter/src/main/java/org/dromara/hertzbeat/alert/calculate/CalculateAlarm.java, alerter/src/main/java/org/dromara/hertzbeat/alert/dao/AlertMonitorDao.java, alerter/src/main/java/org/dromara/hertzbeat/alert/service/impl/AlertServiceImpl.java, common/src/main/java/org/dromara/hertzbeat/common/constants/CommonConstants.java, manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/DbAlertStoreHandlerImpl.java, manager/src/main/java/org/dromara/hertzbeat/manager/pojo/dto/AppCount.java, manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/MonitorServiceImpl.java, web-app/src/app/pojo/AppCount.ts, web-app/src/app/routes/dashboard/dashboard.component.html, web-app/src/app/routes/dashboard/dashboard.component.ts
- bugfix monitor status can not auto update
- remove monitor status UN_REACHABLE
=> bugfix monitor status can not auto update, remove status UN_REACHABLE

manager/src/main/resources/define/app-freebsd.yml
support monitoring freebsd unix metrics
=> support monitoring freebsd unix metrics

collector/src/main/java/org/dromara/hertzbeat/collector/collect/telnet/TelnetCollectImpl.java, common/src/main/java/org/dromara/hertzbeat/common/entity/job/protocol/TelnetProtocol.java, manager/src/main/resources/define/app-zookeeper.yml
extending the telnet protocol, users can send specified commands to the server after successful connection。
optimize zk collector, based telnet send cmd.
=> [collector]feature: optimize zookeeper collector, based telnet

home/src/css/custom.css
Changed the entire orientation of the footer. 
- added a bg that suits the site, added custom css classes and much more. 
[Screencast from 21-05-23 01:38:51 AM IST.webm](https://github.com/dromara/hertzbeat/assets/100678386/f0bae729-3899-4b90-bc0e-f8097599c792)
=> Fixed Footer Overflow issue on the homepage

manager/src/main/resources/define/app-opensuse.yml
support monitoring opensuse os metrics
=> support monitoring opensuse os metrics

manager/src/main/resources/define/app-ssl_cert.yml
=> 新增ssl模版监控变量days_remaining 显示ssl证书到期天数比如10.0

script/docker-compose/hertzbeat-postgresql-iotdb/docker-compose.yaml
=> fix depend on postgres error

home/docs/help/hadoop.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/hadoop.md, manager/src/main/resources/define/app-hadoop.yml
1、Add hadoop.yml: used for adapting hadoop monitoring.
2、Add Chinese and English documentation for monitoring hadoop.
=> Hadoop integration/adaptation has been completed.

warehouse/src/main/java/org/dromara/hertzbeat/warehouse/store/HistoryTdEngineDataStorage.java
添加TDengine SQL查询条件的单引号
修复SQL查询单引号问题
- [√ ]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [√ ]  I have written the necessary doc or comment.
- [ √]  I have added the necessary unit tests and all cases have passed.
=> bugfix HistoryTdEngineDataStorage sql

manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/WeChatAppAlertNotifyHandlerImpl.java, web-app/src/app/routes/alert/alert-notice/alert-notice.component.html
[Fix BUG : use Enterprise WeChat APP alarm notification,log print "invalid access token" ]
- [√]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [√]  I have written the necessary doc or comment.
- [√]  I have added the necessary unit tests and all cases have passed.
=> [Fix BUG : use Enterprise WeChat APP alarm notification,log print "invalid access token" ]

collector/src/main/java/org/dromara/hertzbeat/collector/collect/http/HttpCollectImpl.java, common/src/main/java/org/dromara/hertzbeat/common/constants/CollectorConstants.java, common/src/main/java/org/dromara/hertzbeat/common/util/IpDomainUtil.java
modify the httpRequest format for ipv6 host
=> 1018 task host support ipv6 address

warehouse/pom.xml
=> upgrade greptime dependency, ignore  proto 

manager/src/main/resources/define/app-oracle.yml
=> update monitoring oracle percentage metrics sql script

alerter/src/main/java/org/dromara/hertzbeat/alert/calculate/CalculateAlarm.java, alerter/src/main/java/org/dromara/hertzbeat/alert/reduce/AlarmConvergeReduce.java, web-app/src/assets/i18n/en-US.json, web-app/src/assets/i18n/zh-CN.json, web-app/src/assets/i18n/zh-TW.json
bugfix some alarm message can not be triggered normally
=> bugfix some alarm message can not be triggered normally

alerter/src/main/java/org/dromara/hertzbeat/alert/AlerterProperties.java, common/src/main/java/org/dromara/hertzbeat/common/entity/manager/NoticeReceiver.java, manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/ServerChanAlertNotifyHandlerImpl.java, manager/src/main/resources/templates/alertNotifyServerChan.txt, web-app/src/app/pojo/NoticeReceiver.ts, web-app/src/app/routes/alert/alert-notice/alert-notice.component.html, web-app/src/app/routes/alert/alert-notice/alert-notice.component.ts, web-app/src/assets/i18n/en-US.json, web-app/src/assets/i18n/zh-CN.json, web-app/src/assets/i18n/zh-TW.json
Support sending alert to ServerChan
=> Feature#serverchan

manager/src/main/resources/define/app-dm.yml
修改 app-dm.yml 解决达梦数据库数监控新建网络通信异常
=> bugfix dm database monitoring connect error 

web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html
bugfix: Remove unreachable status
=> Remove unreachable status

manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/DbAlertStoreHandlerImpl.java
bugfix extern alert do not have labels mapping inner monitor
=> bugfix extern alert do not have labels mapping inner monitor

alerter/src/main/java/org/dromara/hertzbeat/alert/controller/AlertReportController.java, alerter/src/main/java/org/dromara/hertzbeat/alert/controller/AlertsController.java, alerter/src/main/java/org/dromara/hertzbeat/alert/dto/TenCloudAlertReport.java, alerter/src/main/java/org/dromara/hertzbeat/alert/service/AlertConvertService.java, alerter/src/main/java/org/dromara/hertzbeat/alert/service/impl/AlertConvertTenCloudServiceImpl.java, alerter/src/main/java/org/dromara/hertzbeat/alert/service/impl/AlertServiceImpl.java, alerter/src/test/java/org/dromara/hertzbeat/alert/controller/AlertReportControllerTest.java, alerter/src/test/java/org/dromara/hertzbeat/alert/controller/AlertsControllerTest.java, manager/src/main/resources/sureness.yml
[Feature]Add third report of TenCloud (#1113)
=> [Feature]Add third report of TenCloud (#1113)

web-app/src/app/routes/alert/alert-setting/alert-setting.component.html
bugfix the notification template environment variable display error
https://github.com/dromara/hertzbeat/issues/1115
=> bugfix the notification template environment variable display error

README.md
- Rephrased introduction section
- Added features section under the introduction section
- Fixed some grammar mistakes
=> docs: enhance README

web-app/src/app/core/i18n/i18n.service.ts, web-app/src/app/core/startup/startup.service.ts
bugfix return old cache json file when upgrade version
#1125
=> bugfix return old cache json file when upgrade version

manager/src/main/java/org/dromara/hertzbeat/manager/controller/AppController.java, manager/src/main/java/org/dromara/hertzbeat/manager/service/AppService.java, manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/AppServiceImpl.java, web-app/src/app/routes/setting/define/define.component.ts, web-app/src/app/service/app-define.service.ts
bugfix monitoring template app name already exists
=> bugfix monitoring template app name already exists

manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/AppServiceImpl.java, web-app/src/app/routes/setting/define/define.component.ts
bugfix npe when get undefined name monitor template yml
happen in windows env
=> bugfix npe when get undefined name monitor template yml

alerter/src/main/java/org/dromara/hertzbeat/alert/calculate/CalculateAlarm.java, common/src/main/java/org/dromara/hertzbeat/common/config/AviatorConfiguration.java, common/src/test/java/org/dromara/hertzbeat/common/config/AviatorConfigurationTest.java, warehouse/src/main/java/org/dromara/hertzbeat/warehouse/controller/MetricsDataController.java, web-app/src/app/routes/alert/alert-setting/alert-setting.component.html, web-app/src/app/routes/alert/alert-setting/alert-setting.component.ts, web-app/src/app/routes/monitor/monitor-data-table/monitor-data-table.component.html, web-app/src/assets/i18n/en-US.json, web-app/src/assets/i18n/zh-CN.json, web-app/src/assets/i18n/zh-TW.json
- support alert threshold rule config system value row count
- support metrics value exists !exists in alert threshold expression
- bugfix monitor detail table ui show null value metrics data
=> support alert threshold rule config system value row count

common/src/main/java/org/dromara/hertzbeat/common/entity/job/Job.java, manager/src/main/java/org/dromara/hertzbeat/manager/service/AppService.java, manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/AppServiceImpl.java, manager/src/main/resources/define/app-a_example.yml
dev: build the back-end of help massage component
- [ √ ]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [ √ ]  I have written the necessary doc or comment.
- [ √ ]  I have added the necessary unit tests and all cases have passed.
=> the back-end of help component has been built

web-app/src/app/routes/dashboard/dashboard.component.html
=> Delete <a> tag of the dashboard's homepage on the top four pages

manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/MonitorServiceImpl.java, manager/src/test/java/org/dromara/hertzbeat/manager/service/MonitorServiceTest.java
=> refactor MonitorServiceImpl

manager/src/main/resources/define/app-tidb.yml
manager-monitors]（新增）tidb监控 添加tidb monitor
=> [manager] support tidb database monitoring 

alerter/src/main/java/org/dromara/hertzbeat/alert/util/AlertTemplateUtil.java, manager/src/main/java/org/dromara/hertzbeat/manager/controller/AccountController.java, manager/src/main/java/org/dromara/hertzbeat/manager/pojo/dto/RefreshTokenResponse.java, manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/MonitorServiceImpl.java
=> refactor fix potential npe

web-app/src/index.html, web-app/src/styles/theme.less
Use google analytics to help us know which users are using, which functions are the most popular, and help us improve our products.
=> support google analytics

collector/pom.xml, collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/export/NettyDataQueue.java, common/src/main/java/org/dromara/hertzbeat/common/queue/impl/InMemoryCommonDataQueue.java, script/application.yml, script/docker-compose/hertzbeat-mysql-iotdb/conf/application.yml, script/docker-compose/hertzbeat-mysql-iotdb/docker-compose-1.0.yaml, script/docker-compose/hertzbeat-mysql-iotdb/docker-compose.yaml, script/docker-compose/hertzbeat-mysql-tdengine/conf/application.yml, script/docker-compose/hertzbeat-mysql-tdengine/docker-compose.yaml, script/docker-compose/hertzbeat-postgresql-iotdb/conf/application.yml, script/docker-compose/hertzbeat-postgresql-iotdb/docker-compose.yaml
=> bugfix fix found 2 dataQueue bean when not config common.queue param

manager/src/main/java/org/dromara/hertzbeat/manager/component/alerter/impl/WeChatAppAlertNotifyHandlerImpl.java
=> bugfix WeChatAppAlertNotifyHandlerImpl

manager/src/main/java/org/dromara/hertzbeat/manager/Manager.java, manager/src/test/java/org/dromara/hertzbeat/manager/ManagerTest.java
=> fix jmx jndi inject vulnerability

web-app/src/app/routes/monitor/monitor-new/monitor-new.component.html, web-app/src/app/routes/monitor/monitor-new/monitor-new.component.ts
=> bugfix monitoring param number limit range

web-app/src/app/routes/alert/alert-setting/alert-setting.component.html, web-app/src/app/routes/alert/alert-setting/alert-setting.component.ts
=> bugfix threshold setting template variables has repeated parameters

alerter/src/main/java/org/dromara/hertzbeat/alert/service/impl/AlertServiceImpl.java, common/src/main/java/org/dromara/hertzbeat/common/entity/dto/AlertReport.java, common/src/main/java/org/dromara/hertzbeat/common/util/JsonUtil.java
bugfix jackson deserialize localDatetime error
=> bugfix jackson deserialize localDatetime error

web-app/src/app/routes/alert/alert-notice/alert-notice.component.html, web-app/src/app/routes/alert/alert-notice/alert-notice.component.ts
auto split webhook token when user input hook url
=> auto split webhook token when user input hook url

manager/src/main/java/org/dromara/hertzbeat/manager/scheduler/CollectorAndJobScheduler.java
=> bugfix counting wrong tasks num of collector

manager/src/main/resources/define/app-push.yml, push/pom.xml, web-app/src/app/routes/monitor/monitor-detail/monitor-detail.component.html
=> support edit monitor in monitor detail page

manager/src/main/resources/define/app-windows.yml, web-app/src/app/routes/alert/alert-setting/alert-setting.component.ts
fix https://github.com/dromara/hertzbeat/issues/1284 https://github.com/dromara/hertzbeat/issues/1283
=> bugfix threshold availability automatically carries threshold parameters

collector/src/main/java/org/dromara/hertzbeat/collector/collect/push/PushCollectImpl.java, common/src/main/java/org/dromara/hertzbeat/common/entity/push/PushMetricsDto.java, push/src/main/java/org/dromara/hertzbeat/push/service/impl/PushServiceImpl.java
support push style for multiple messages
=> support push style for multiple messages

home/docusaurus.config.js, manager/src/main/resources/define/app-almalinux.yml, manager/src/main/resources/define/app-centos.yml, manager/src/main/resources/define/app-coreos.yml, manager/src/main/resources/define/app-debian.yml, manager/src/main/resources/define/app-euleros.yml, manager/src/main/resources/define/app-freebsd.yml, manager/src/main/resources/define/app-linux.yml, manager/src/main/resources/define/app-opensuse.yml, manager/src/main/resources/define/app-redhat.yml, manager/src/main/resources/define/app-rockylinux.yml, manager/src/main/resources/define/app-ubuntu.yml, web-app/src/app/routes/monitor/monitor-data-table/monitor-data-table.component.html, web-app/src/assets/i18n/en-US.json
set ssh param connect reused default false
=> set ssh param connect reused default false

manager/src/main/resources/define/app-mysql.yml
=> feature: app-mysql.yml

manager/src/main/resources/application.yml, script/application.yml, script/helm/hertzbeat/templates/manager/configmap.yaml, script/helm/hertzbeat/values.yaml
=> modify default IoTDB version config to V_1_0

alerter/src/main/java/org/dromara/hertzbeat/alert/util/AlertTemplateUtil.java, common/src/main/java/org/dromara/hertzbeat/common/entity/manager/NoticeTemplate.java, script/assembly/collector/assembly.xml, script/assembly/server/assembly.xml, script/helm/hertzbeat/Chart.yaml, script/sql/schema.sql, script/sureness.yml, web-app/src/app/shared/constants.ts
[hertzbeat] release hertzbeat version v1.4.2
=> [hertzbeat] release hertzbeat version v1.4.2

README.md, README_CN.md, home/docs/start/package-deploy.md, home/docs/start/quickstart.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/start/package-deploy.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/start/quickstart.md, script/assembly/collector/assembly-windows-64.xml, web-app/src/assets/i18n/en-US.json, web-app/src/assets/i18n/zh-CN.json, web-app/src/assets/i18n/zh-TW.json
=> update package deploy doc

manager/src/main/resources/define/app-mysql.yml
Adjust slow query translation
更正MYSQL监控模板中文
zh-CN: 满查询 信息
zh-CN: 慢查询 信息
=> app-mysql.yml: Adjust slow query translation

README.md, README_CN.md
=> [doc]add star history

alerter/src/main/java/org/dromara/hertzbeat/alert/calculate/CalculateAlarm.java
bugfix CalculateAlarm execAlertExpression NPE
=> bugfix CalculateAlarm execAlertExpression NPE

collector/src/main/java/org/dromara/hertzbeat/collector/collect/ntp/NtpCollectImpl.java, collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/DispatchConstants.java, collector/src/main/resources/META-INF/services/org.dromara.hertzbeat.collector.collect.AbstractCollect, common/src/main/java/org/dromara/hertzbeat/common/entity/job/Metrics.java, common/src/main/java/org/dromara/hertzbeat/common/entity/job/protocol/NtpProtocol.java, manager/src/main/resources/define/app-ntp.yml
add ntp protocol and support ntp monitoring
=> add ntp protocol and support ntp monitoring

web-app/src/app/routes/monitor/monitor-data-chart/monitor-data-chart.component.ts
support legend pageable in history data charts
=> support legend pageable in history data charts

CODE_OF_CONDUCT.md
https://www.contributor-covenant.org/version/2/0/code_of_conduct/
=> [doc] add code of conduct

collector/src/main/java/org/dromara/hertzbeat/collector/Collector.java, collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/CommonDispatcher.java, collector/src/main/java/org/dromara/hertzbeat/collector/util/CollectUtil.java, common/src/main/java/org/dromara/hertzbeat/common/config/AviatorConfiguration.java, common/src/main/java/org/dromara/hertzbeat/common/entity/job/Job.java, manager/src/main/resources/application.yml, manager/src/main/resources/define/app-hertzbeat.yml, manager/src/main/resources/define/app-hertzbeat_token.yml, manager/src/main/resources/sureness.yml, script/application.yml, script/docker-compose/hertzbeat-mysql-iotdb/conf/application.yml, script/docker-compose/hertzbeat-mysql-iotdb/conf/sureness.yml, script/docker-compose/hertzbeat-mysql-tdengine/conf/application.yml, script/docker-compose/hertzbeat-mysql-tdengine/conf/sureness.yml, script/docker-compose/hertzbeat-mysql-victoria-metrics/conf/application.yml, script/docker-compose/hertzbeat-mysql-victoria-metrics/conf/sureness.yml, script/docker-compose/hertzbeat-postgresql-iotdb/conf/application.yml, script/docker-compose/hertzbeat-postgresql-iotdb/conf/sureness.yml, script/sureness.yml
- bugfix ^o^ token error
- protect metrics api auth
=> bugfix ^o^ token error, protect metrics api auth

collector/src/main/java/org/dromara/hertzbeat/collector/collect/nebulagraph/NebulaGraphCollectImpl.java, collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/DispatchConstants.java, collector/src/main/resources/META-INF/services/org.dromara.hertzbeat.collector.collect.AbstractCollect, common/src/main/java/org/dromara/hertzbeat/common/entity/job/Metrics.java, common/src/main/java/org/dromara/hertzbeat/common/entity/job/protocol/NebulaGraphProtocol.java, home/docs/help/nebulagraph.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/nebulagraph.md, manager/src/main/resources/define/app-nebulaGraph.yml
=> support monitoring NebulaGraph metrics and add help doc

manager/src/main/resources/define/app-springboot3.yml
add metrics i18n for app-springboot3.yml
=> feature: add metrics i18n for app-springboot3.yml

README.md, README_CN.md, collector/src/main/java/org/dromara/hertzbeat/collector/collect/common/cache/ConnectionCommonCache.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/common/cache/JdbcConnect.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/common/cache/JmxConnect.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/common/cache/MongodbConnect.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/common/cache/RedisConnect.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/common/cache/SshConnect.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/common/http/CommonHttpClient.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/database/JdbcCommonCollect.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/jmx/JmxCollectImpl.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/mongodb/MongodbSingleCollectImpl.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/redis/RedisCommonCollectImpl.java, collector/src/main/java/org/dromara/hertzbeat/collector/collect/ssh/SshCollectImpl.java, collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/CommonDispatcher.java, collector/src/main/java/org/dromara/hertzbeat/collector/dispatch/MetricsCollectorQueue.java, collector/src/test/java/org/dromara/hertzbeat/collector/collect/common/cache/CommonCacheTest.java
=> remove sleep, probably busy-waiting

manager/src/main/resources/define/app-docker.yml
=> [Task] Monitoring Template Yml Metrics I18n | 监控模版指标国际化任务认领 #1212

manager/src/main/resources/define/app-springboot3.yml
bugfix springboot3 translation
=> bugfix springboot3 translation

README.md, home/blog/2023-12-11-hertzbeat-v1.4.3.md, home/docs/introduce.md, manager/src/main/resources/define/app-activemq.yml, manager/src/main/resources/define/app-centos.yml, manager/src/main/resources/define/app-cisco_switch.yml, manager/src/main/resources/define/app-fullsite.yml, manager/src/main/resources/define/app-h3c_switch.yml, manager/src/main/resources/define/app-hadoop.yml, manager/src/main/resources/define/app-hpe_switch.yml, manager/src/main/resources/define/app-huawei_switch.yml, manager/src/main/resources/define/app-jetty.yml, manager/src/main/resources/define/app-jvm.yml, manager/src/main/resources/define/app-kafka.yml, manager/src/main/resources/define/app-mariadb.yml, manager/src/main/resources/define/app-memcached.yml, manager/src/main/resources/define/app-mysql.yml, manager/src/main/resources/define/app-nacos.yml, manager/src/main/resources/define/app-nginx.yml, manager/src/main/resources/define/app-ntp.yml, manager/src/main/resources/define/app-pop3.yml, manager/src/main/resources/define/app-smtp.yml, manager/src/main/resources/define/app-spark.yml, manager/src/main/resources/define/app-tomcat.yml, manager/src/main/resources/define/app-tplink_switch.yml, manager/src/main/resources/define/app-websocket.yml
=> update switch monitoring metrics i18n

home/docs/introduce.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/introduce.md
=> update introduce doc

common/src/main/java/org/dromara/hertzbeat/common/entity/manager/Tag.java, script/sql/schema.sql, web-app/src/app/pojo/Tag.ts, web-app/src/app/routes/setting/tags/tags.component.html, web-app/src/app/routes/setting/tags/tags.component.ts, web-app/src/assets/i18n/en-US.json, web-app/src/assets/i18n/zh-CN.json, web-app/src/assets/i18n/zh-TW.json
…d , edit tag description in webui
add new field description in hertzbeat tag detail and can add,edit tag description in webui
=> feature: add new field description in hertzbeat tag detail 

web-app/package.json
webapp add build package script
=> webapp add build package script

alerter/src/main/java/org/dromara/hertzbeat/alert/controller/AlertDefinesController.java, script/docker-compose/hertzbeat-mysql-iotdb/conf/sureness.yml, script/docker-compose/hertzbeat-mysql-tdengine/conf/sureness.yml, script/docker-compose/hertzbeat-mysql-victoria-metrics/conf/sureness.yml, script/docker-compose/hertzbeat-postgresql-iotdb/conf/sureness.yml
=> notify success when import alarm define success

manager/pom.xml, manager/src/main/java/org/dromara/hertzbeat/manager/config/RestTemplateConfig.java, pom.xml
use okhttp instead of HttpURLConnection in rest template
=> use okhttp instead of HttpURLConnection in rest template

manager/pom.xml, script/assembly/server/assembly-docker-compose.xml
=> auto build docker-compose script zip

manager/src/main/java/org/dromara/hertzbeat/manager/Manager.java, manager/src/main/java/org/dromara/hertzbeat/manager/controller/AccountController.java, manager/src/main/java/org/dromara/hertzbeat/manager/support/GlobalExceptionHandler.java, web-app/src/app/core/interceptor/default.interceptor.ts
=> bugfix undefined endsWith error

web-app/src/app/routes/status-public/status-public.component.html
=> [bugfix]Fix incorrect logo size

pom.xml
[fix]update aviator version to avoid expression injection
=> [fix]update aviator version to avoid expression injection

home/i18n/zh-cn/docusaurus-plugin-content-blog/2023-08-28-new-committer.md
=> [doc]Translate doc to English

manager/src/main/resources/define/app-flink.yml
support monitor metrics name i18n: flink
=> support monitor metrics name i18n: flink

manager/src/main/resources/define/app-zookeeper.yml
=> support monitor metrics name i18n: zookeeper

alerter/src/main/java/org/dromara/hertzbeat/alert/controller/AlertReportController.java, alerter/src/main/java/org/dromara/hertzbeat/alert/dto/CloudAlertReportAbstract.java, alerter/src/main/java/org/dromara/hertzbeat/alert/dto/GeneralCloudAlertReport.java, alerter/src/main/java/org/dromara/hertzbeat/alert/dto/TenCloudAlertReport.java, alerter/src/main/java/org/dromara/hertzbeat/alert/enums/CloudServiceAlarmInformationEnum.java, alerter/src/main/java/org/dromara/hertzbeat/alert/reduce/AlarmCommonReduce.java, alerter/src/main/java/org/dromara/hertzbeat/alert/reduce/AlarmConvergeReduce.java, alerter/src/main/java/org/dromara/hertzbeat/alert/reduce/AlarmSilenceReduce.java, alerter/src/main/java/org/dromara/hertzbeat/alert/service/AlertConvergeService.java, alerter/src/main/java/org/dromara/hertzbeat/alert/service/AlertDefineImExportService.java, alerter/src/main/java/org/dromara/hertzbeat/alert/service/AlertSilenceService.java, alerter/src/main/java/org/dromara/hertzbeat/alert/service/impl/AlertConvergeServiceImpl.java, alerter/src/main/java/org/dromara/hertzbeat/alert/service/impl/AlertDefineAbstractImExportServiceImpl.java, alerter/src/main/java/org/dromara/hertzbeat/alert/service/impl/AlertDefineExcelImExportServiceImpl.java, alerter/src/main/java/org/dromara/hertzbeat/alert/service/impl/AlertDefineJsonImExportServiceImpl.java, alerter/src/main/java/org/dromara/hertzbeat/alert/service/impl/AlertDefineYamlImExportServiceImpl.java, alerter/src/main/java/org/dromara/hertzbeat/alert/service/impl/AlertSilenceServiceImpl.java, alerter/src/main/java/org/dromara/hertzbeat/alert/util/DateUtil.java, alerter/src/test/java/org/dromara/hertzbeat/alert/AlerterWorkerPoolTest.java, alerter/src/test/java/org/dromara/hertzbeat/alert/controller/AlertDefineControllerTest.java, alerter/src/test/java/org/dromara/hertzbeat/alert/controller/AlertDefinesControllerTest.java, alerter/src/test/java/org/dromara/hertzbeat/alert/controller/AlertReportControllerTest.java, alerter/src/test/java/org/dromara/hertzbeat/alert/controller/AlertsControllerTest.java, alerter/src/test/java/org/dromara/hertzbeat/alert/service/AlertDefineServiceTest.java, alerter/src/test/java/org/dromara/hertzbeat/alert/service/AlertServiceTest.java, alerter/src/test/java/org/dromara/hertzbeat/alert/util/AlertTemplateUtilTest.java
add apache license for alert module
=> Alert apache license

README.md, README_CN.md
[fix]Fix CNCF link
before
after:
=> [fix]Fix CNCF link

script/helm/hertzbeat/README.md, script/helm/hertzbeat/templates/NOTES.txt, script/helm/hertzbeat/templates/manager/ingress.yaml, script/helm/hertzbeat/templates/manager/service-expose.yaml, script/helm/hertzbeat/values.yaml
Improve ingress support for helm charts
=> Feature# Improve ingress support for helm charts

manager/src/main/java/org/dromara/hertzbeat/manager/component/status/CalculateStatus.java, manager/src/main/java/org/dromara/hertzbeat/manager/service/impl/StatusPageServiceImpl.java
bugfix status page calculate component status error
=> bugfix status page calculate component status error

collector/src/main/java/org/dromara/hertzbeat/collector/collect/database/JdbcCommonCollect.java
=> bugfix custom jdbc url run local script vulnerability

script/helm/hertzbeat/templates/manager/configmap.yaml
Synchronize sureness.yml to solve the status page authentication problem
=> [fix]: Synchronize latest sureness.yml

home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/springboot2.md
=> 补充springboot2监控的帮助手册

home/docs/help/springboot2.md
Supplement the help document for Springboot 2 monitoring
=> Supplement the help document for Springboot 2 monitoring

warehouse/src/main/java/org/dromara/hertzbeat/warehouse/store/HistoryVictoriaMetricsDataStorage.java, web-app/src/app/routes/monitor/monitor-data-chart/monitor-data-chart.component.ts
bugfix long range history chart render error
=> bugfix long range history chart render error

alerter/pom.xml, common/pom.xml, manager/pom.xml, pom.xml, push/pom.xml, warehouse/pom.xml
=> bugfix swagger-ui not work in springboot3

manager/src/main/resources/define/app-clickhouse.yml
support monitor metrics name i18n:ClickHouse
=> support monitor metrics name i18n: ClickHouse

home/blog/2022-02-28-hertzbeat-v1.0-beta.4.md
translate blog 20220228 to English
=> translate blog 20220228 to English

home/blog/2022-03-10-hertzbeat-v1.0-beta.5.md
translate blog 20220310 to English
=> translate blog 20220310 to English

home/blog/2022-09-04-hertzbeat-v1.1.3.md
translate blog 20220904 to English
=> translate blog 20220904 to English

home/blog/2022-02-17-hertzbeat.md
=> feature:Translate 2022-02-17-hertzbeat Document

pom.xml
bugfix monitoring mongodb not work in springboot3
=> bugfix monitoring mongodb not work in springboot3

README.md, README_CN.md, home/docs/introduce.md, home/versioned_docs/version-v1.4.x/introduce.md, web-app/src/app/layout/basic/basic.component.ts, web-app/src/app/routes/routes-routing.module.ts, web-app/src/app/routes/setting/collector/collector.component.html, web-app/src/app/routes/setting/define/define.component.html, web-app/src/app/routes/setting/setting-routing.module.ts, web-app/src/app/routes/setting/status/status.component.html, web-app/src/app/routes/setting/tags/tags.component.html, web-app/src/app/routes/status-public/status-public.component.ts, web-app/src/assets/app-data.json, web-app/src/assets/i18n/en-US.json, web-app/src/assets/i18n/zh-CN.json, web-app/src/assets/i18n/zh-TW.json
=> update webapp menu layout and doc

common/src/main/java/org/dromara/hertzbeat/common/util/AesUtil.java
=> bugfix old data decode error when use new common-secret

.asf.yaml
=> update asf branch protected check

README.md, README_CN.md
=> [doc]Update star chart

common/src/main/java/org/apache/hertzbeat/common/entity/manager/JsonLongListAttributeConverter.java, common/src/main/java/org/apache/hertzbeat/common/entity/manager/JsonStringListAttributeConverter.java
=> [improvement]Add lisence.

.asf.yaml, .github/PULL_REQUEST_TEMPLATE.md, .github/labeler.yml, .github/workflows/license-checker.yml, .github/workflows/pull-request-robot.yml
- auto label when pr, add labeler action
- update asf config, enable `required_status_checks` `strict` true
=> [improve] auto label when pr, update asf config

.asf.yaml, .licenserc.yaml, DISCLAIMER
create disclaimer file, add incubating in describe
=> [improve] create disclaimer file, add incubating in describe 

collector/src/test/java/org/apache/hertzbeat/collector/collect/redis/RedisSingleCollectImplTest.java
Add RedisSingleCollectImplTest
=> [test] Add RedisSingleCollectImplTest

warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/HistoryInfluxdbDataStorage.java
=> [refactor] add override annotation

warehouse/src/main/java/org/apache/hertzbeat/warehouse/config/WarehouseProperties.java, warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/HistoryGrepTimeDbDataStorage.java, warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/HistoryInfluxdbDataStorage.java, warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/HistoryIotDbDataStorage.java, warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/HistoryJpaDatabaseDataStorage.java, warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/HistoryTdEngineDataStorage.java, warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/HistoryVictoriaMetricsDataStorage.java, warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/RealTimeMemoryDataStorage.java, warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/RealTimeRedisDataStorage.java
database-related properties class, type changed to record  https://github.com/apache/hertzbeat/issues/1785
=> [refactor] database-related properties class, type changed to record

manager/src/main/resources/define/app-cisco_switch.yml, manager/src/main/resources/define/app-h3c_switch.yml, manager/src/main/resources/define/app-hpe_switch.yml, manager/src/main/resources/define/app-huawei_switch.yml, manager/src/main/resources/define/app-tplink_switch.yml
:Fix snmp template unit conversion problem
=> Fix snmp template unit conversion problem

home/docs/help/clickhouse.md, home/docs/help/guide.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/clickhouse.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/guide.md, home/sidebars.json
Add help documentation for clickhouse database monitoring
=> [doc] Add help documentation for clickhouse monitoring

collector/src/main/java/org/apache/hertzbeat/collector/collect/pop3/Pop3CollectImpl.java
Changed Pop3Protocol usage from before Null check to after Null check.
=> [improve] preventing NPE

alerter/src/main/java/org/apache/hertzbeat/alert/service/impl/AlertDefineExcelImExportServiceImpl.java, alerter/src/main/java/org/apache/hertzbeat/alert/service/impl/AlertServiceImpl.java, collector/src/main/java/org/apache/hertzbeat/collector/collect/common/cache/ConnectionCommonCache.java, collector/src/main/java/org/apache/hertzbeat/collector/collect/database/JdbcCommonCollect.java, collector/src/main/java/org/apache/hertzbeat/collector/collect/dns/DnsCollectImpl.java, collector/src/main/java/org/apache/hertzbeat/collector/collect/http/HttpCollectImpl.java, collector/src/main/java/org/apache/hertzbeat/collector/collect/http/promethus/PrometheusMatrixParser.java, collector/src/main/java/org/apache/hertzbeat/collector/collect/http/promethus/PrometheusVectorParser.java, collector/src/main/java/org/apache/hertzbeat/collector/collect/http/promethus/exporter/ExporterParser.java, collector/src/main/java/org/apache/hertzbeat/collector/collect/jmx/JmxCollectImpl.java, collector/src/main/java/org/apache/hertzbeat/collector/collect/prometheus/parser/TextParser.java, collector/src/main/java/org/apache/hertzbeat/collector/collect/snmp/SnmpCollectImpl.java, collector/src/main/java/org/apache/hertzbeat/collector/collect/ssh/SshCollectImpl.java, collector/src/main/java/org/apache/hertzbeat/collector/dispatch/timer/WheelTimerTask.java, common/src/main/java/org/apache/hertzbeat/common/support/SpringContextHolder.java, manager/src/main/java/org/apache/hertzbeat/manager/controller/MetricsController.java, manager/src/main/java/org/apache/hertzbeat/manager/service/impl/AppServiceImpl.java, manager/src/main/java/org/apache/hertzbeat/manager/service/impl/ExcelImExportServiceImpl.java, manager/src/main/java/org/apache/hertzbeat/manager/service/impl/MonitorServiceImpl.java, manager/src/main/java/org/apache/hertzbeat/manager/service/impl/ObjectStoreConfigServiceImpl.java, manager/src/main/java/org/apache/hertzbeat/manager/support/GlobalExceptionHandler.java, warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/HistoryJpaDatabaseDataStorage.java
=> Refactor: upgrade syntax to jdk17(instanceof & switch)

manager/src/main/resources/application.yml
Remove optional comments.
Update default mail port.
=> [Remove][Improve]Mail config

home/docs/help/influxdb.md, home/docs/help/rocketmq.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/rocketmq.md, home/sidebars.json
1. add help document for rocketmq
2. fix error in influxdb.md
=> [doc] add help document for rocketmq

collector/src/main/java/org/apache/hertzbeat/collector/collect/http/SslCertificateCollectImpl.java, common/src/main/java/org/apache/hertzbeat/common/util/JexlCommonFunction.java, common/src/main/java/org/apache/hertzbeat/common/util/JexlExpressionRunner.java, common/src/test/java/org/apache/hertzbeat/common/util/JexlTest.java, manager/src/main/resources/define/app-ssl_cert.yml
fix ssl-cert days_remaining and npe
```
Cannot invoke "String.startsWith(String)" because "url" is null
```
=> [bugfix] fix ssl-cert days_remaining and npe

collector/src/main/java/org/apache/hertzbeat/collector/collect/nebulagraph/NebulaTemplate.java, collector/src/main/java/org/apache/hertzbeat/collector/collect/nebulagraph/NgqlCollectImpl.java, collector/src/test/java/org/apache/hertzbeat/collector/collect/nebulagraph/NgqlCollectImplTest.java
1. add unit test for NgqlCollectImpl
2. optimize the error message of nebulaGraph connection
=> [test] add test for NgqlCollectImpl

home/docs/help/guide.md, home/docs/help/redis.md, home/i18n/en/docusaurus-plugin-content-docs/current.json, home/i18n/zh-cn/docusaurus-plugin-content-docs/current.json, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/guide.md, home/sidebars.json, manager/src/main/resources/define/app-openai.yml, manager/src/main/resources/define/app-redfish.yml, web-app/src/assets/app-data.json, web-app/src/assets/i18n/en-US.json, web-app/src/assets/i18n/zh-CN.json, web-app/src/assets/i18n/zh-TW.json
add llm, server menu and update doc
=> [improve] add llm, server menu and update doc

README_CN.md
=> [doc]: update readme-cn docs

.gitignore
When editing code in idea, icon.png in .idea folder may be ignored, this update will keep icon.png in git add to avoid deleting icon.png.
=> [chore] update .gitignore to save .idea/icon.png

common/src/main/java/org/apache/hertzbeat/common/util/AesUtil.java, common/src/main/java/org/apache/hertzbeat/common/util/Base64Util.java, common/src/test/java/org/apache/hertzbeat/common/util/AesUtilTest.java, common/src/test/java/org/apache/hertzbeat/common/util/Base64UtilTest.java, common/src/test/java/org/apache/hertzbeat/common/util/JsonUtilTest.java
=> [improve] add common util test

alerter/src/main/java/org/apache/hertzbeat/alert/calculate/CalculateAlarm.java, common/src/main/java/org/apache/hertzbeat/common/constants/CommonConstants.java, common/src/main/java/org/apache/hertzbeat/common/entity/manager/Monitor.java, manager/src/main/java/org/apache/hertzbeat/manager/component/alerter/impl/DbAlertStoreHandlerImpl.java, manager/src/main/java/org/apache/hertzbeat/manager/component/status/CalculateStatus.java, manager/src/main/java/org/apache/hertzbeat/manager/scheduler/CollectorJobScheduler.java, manager/src/main/java/org/apache/hertzbeat/manager/service/impl/MonitorServiceImpl.java, manager/src/test/java/org/apache/hertzbeat/manager/service/MonitorServiceTest.java, web-app/src/app/pojo/Monitor.ts, web-app/src/app/routes/alert/alert-setting/alert-setting.component.html, web-app/src/app/routes/dashboard/dashboard.component.html, web-app/src/app/routes/monitor/monitor-detail/monitor-detail.component.html, web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html, web-app/src/assets/i18n/en-US.json, web-app/src/assets/i18n/zh-CN.json, web-app/src/assets/i18n/zh-TW.json
- update monitor state desc
- update monitor list button
=> [improve] update monitor state desc

manager/src/main/resources/sureness.yml, script/docker-compose/hertzbeat-mysql-iotdb/conf/sureness.yml, script/docker-compose/hertzbeat-mysql-tdengine/conf/sureness.yml, script/docker-compose/hertzbeat-mysql-victoria-metrics/conf/sureness.yml, script/docker-compose/hertzbeat-postgresql-iotdb/conf/sureness.yml, script/helm/hertzbeat/templates/manager/configmap.yaml, script/sureness.yml, web-app/src/app/core/startup/startup.service.ts, web-app/src/app/routes/passport/login/login.component.html, web-app/src/app/routes/passport/login/login.component.ts, web-app/src/assets/i18n/en-US.json, web-app/src/assets/i18n/zh-CN.json, web-app/src/assets/i18n/zh-TW.json
tips need update initial default password
=> [improve] tips need update initial default password

home/sidebars.json
There are duplicate indices in Navigation bar
=> [imprve] Remove duplicate indices

home/docs/introduce.md, home/docs/start/upgrade.md, home/versioned_docs/version-v1.4.x/introduce.md, home/versioned_docs/version-v1.4.x/start/upgrade.md
Fix: #2046 
fix several typos in docs
=> [docs]: fix several typos in docs

manager/src/main/resources/db/migration/mysql/V160__update_column.sql
=> [bugfix] notice rules api access 409 error when upgrade 1.6.0

README.md, README_CN.md
=> [doc] Add codecov badge 

web-app/src/app/layout/basic/widgets/user.component.ts
before:
after:
**Fixed the issue of the link at the bottom right corner of the dialog not being horizontally centered.**
=> Fixed a style issue within the dialog on the about-page.

web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html
Fixed the bug of the status filter in the monitoring center. #2123
=> bugfix the status filter in the monitoring center

web-app/src/app/routes/alert/alert-center/alert-center.component.html
Fixed the issues similar to #2127 on the alert center page.
=> Fixed the issues similar to #2127 on the alert center page.

home/docs/community/new_committer_process.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/community/new_committer_process.md, home/src/pages/team/member.json
=> [doc] add new committer shenghang

web-app/src/app/routes/dashboard/dashboard.component.html, web-app/src/app/routes/passport/lock/lock.component.html, web-app/src/app/routes/passport/login/login.component.html, web-app/src/app/routes/setting/collector/collector.component.html, web-app/src/app/routes/setting/tags/tags.component.html, web-app/src/app/routes/status-public/status-public.component.html, web-app/src/app/routes/status-public/status-public.component.less, web-app/src/app/shared/components/help-massage-show/help-massage-show.component.html, web-app/src/app/shared/components/help-massage-show/help-massage-show.component.less, web-app/src/styles/theme.less
Continuously supplement and improve the goals set in #2140
=> Continuously supplement and improve the goals set in #2140

web-app/src/app/routes/alert/alert-center/alert-center.component.html, web-app/src/app/routes/alert/alert-converge/alert-converge.component.html, web-app/src/app/routes/alert/alert-notice/alert-notice.component.html, web-app/src/app/routes/alert/alert-setting/alert-setting.component.html, web-app/src/app/routes/alert/alert-silence/alert-silence.component.html, web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html, web-app/src/app/routes/setting/collector/collector.component.html, web-app/src/app/routes/setting/status/status.component.html, web-app/src/app/routes/setting/tags/tags.component.html, web-app/src/app/shared/components/toolbar/toolbar.component.html, web-app/src/app/shared/components/toolbar/toolbar.component.less, web-app/src/app/shared/components/toolbar/toolbar.component.spec.ts, web-app/src/app/shared/components/toolbar/toolbar.component.ts, web-app/src/app/shared/shared.module.ts
before:
after:
Optimize the styles of the toolbar at the top of the list page; Add a new common toolbar component.
=> Add a new common toolbar component.

web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html, web-app/src/styles/theme.less
before:
after:
Fixed the issue that the [first loading] does not appear in the [new-monitor modal]
=> Fixed the issue that the [first loading] does not appear

web-app/src/app/routes/setting/define/define.component.html, web-app/src/app/routes/setting/define/define.component.less, web-app/src/app/routes/setting/define/define.component.ts
=> Add a search to the /setting/define page.

web-app/src/app/shared/components/monitor-select-menu/monitor-select-menu.component.html, web-app/src/app/shared/components/multi-func-input/multi-func-input.component.html
=> Add support for `search` type to the `multi-func-input` component.

web-app/src/app/routes/dashboard/dashboard.component.html, web-app/src/app/routes/dashboard/dashboard.component.less, web-app/src/app/routes/dashboard/dashboard.component.ts
before:
after:
* A unified loading animation has been added.
* Change the overall scrolling of the card to content scrolling.
=> Optimize the dashboard.

web-app/src/app/routes/alert/alert-notice/alert-notice.component.html, web-app/src/assets/i18n/en-US.json, web-app/src/assets/i18n/zh-CN.json, web-app/src/assets/i18n/zh-TW.json
Add a missing multi-language translation.
=> Add a missing multi-language translation.

web-app/src/app/routes/monitor/monitor-data-table/monitor-data-table.component.html, web-app/src/app/routes/monitor/monitor-detail/monitor-detail.component.html, web-app/src/app/routes/monitor/monitor-detail/monitor-detail.component.ts
* When the content is still loading, the title will display as "undefined"
* Before the content is loaded, the countdown for "Page Auto-Refresh" has already started
=> Optimize the detail-page of monitor.

web-app/src/app/routes/monitor/monitor-form/monitor-form.component.html
=> Hide the area when there are no advanced settings

web-app/src/app/routes/monitor/monitor-data-chart/monitor-data-chart.component.html, web-app/src/app/routes/monitor/monitor-detail/monitor-detail.component.html, web-app/src/app/routes/monitor/monitor-detail/monitor-detail.component.less
Fixed style issue of chart in detail-page
=> Fixed style issue of chart in detail-page

manager/src/main/resources/application-test.yml, manager/src/main/resources/application.yml
remove chinese in application.yml
=> [refactor] remove chinese in application.yml

common/src/test/java/org/apache/hertzbeat/common/util/LruHashMapTest.java, common/src/test/java/org/apache/hertzbeat/common/util/MapCapUtilTest.java
- Add MapCap & LruMap unit test.
=> [Improve] add MapCap & LruMap unit test

e2e/testsuite.yaml
All test cases have passed locally.
=> [e2e] complete e2e test case

common/src/main/java/org/apache/hertzbeat/common/util/TimePeriodUtil.java, common/src/test/java/org/apache/hertzbeat/common/util/ResourceBundleUtilTest.java, common/src/test/java/org/apache/hertzbeat/common/util/TimePeriodUtilTest.java
- Add common/TimePeriodUtil & common/ResourceBundleUtil unit test
=> [Improve] add TimePeriodUtil & ResourceBundleUtil unit test

web-app/src/app/routes/monitor/monitor-edit/monitor-edit.component.html, web-app/src/app/shared/components/help-message-show/help-message-show.component.html, web-app/src/app/shared/components/help-message-show/help-message-show.component.ts
=> Optimize the monitor-edit page

web-app/src/app/routes/monitor/monitor-form/monitor-form.component.html, web-app/src/app/routes/monitor/monitor-form/monitor-form.component.ts
Further enhance and refine the optimizations implemented in #2215.
=> Further enhance and refine the optimizations implemented in #2215.

web-app/src/app/routes/setting/plugins/plugin.component.html, web-app/src/app/routes/setting/plugins/plugin.component.ts
=> Fixed issue of plugin-upload form

common/src/test/java/org/apache/hertzbeat/common/support/SpringContextHolderTest.java
- Add springContextHolder unit test
=> [Improve] add springContextHolder unit test

manager/src/test/java/org/apache/hertzbeat/manager/controller/MonitorsControllerTest.java, manager/src/test/java/org/apache/hertzbeat/manager/controller/NoticeConfigControllerTest.java
add NoticeConfigControllerTest and MonitorsControllerTest test
=> [test] : add NoticeConfigControllerTest and MonitorsControllerTest test

common/src/test/java/org/apache/hertzbeat/common/queue/impl/InMemoryCommonDataQueueTest.java, common/src/test/java/org/apache/hertzbeat/common/queue/impl/KafkaCommonDataQueueTest.java
=> [Improve] add common/memory unit test

manager/src/main/resources/define/app-mysql.yml
fix mysql `connections` field explanation. issue https://github.com/apache/hertzbeat/issues/2289
=> [doc] fix mysql connections field explanation

.all-contributorsrc, README.md, README_CN.md, home/src/pages/team/index.jsx, home/src/pages/team/member.json
update committer and contributor
=> [doc] update committer and contributor 

manager/src/main/java/org/apache/hertzbeat/manager/service/impl/MailServiceImpl.java
A small code specification change.
=> A small code specification change.

warehouse/src/main/java/org/apache/hertzbeat/warehouse/listener/WareHouseApplicationReadyListener.java, warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/DataStorageDispatch.java, warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/history/iotdb/IotDbDataStorage.java, warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/history/tdengine/TdEngineDataStorage.java, warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/realtime/redis/RedisDataStorage.java
=> [refactor] remove chinese and change code style in Warehouse

common/src/test/java/org/apache/hertzbeat/common/support/CommonThreadPoolTest.java
- add commonThreadPoll unit test
=> [Improve] add commonThreadPoll unit test

common/src/main/java/org/apache/hertzbeat/common/support/valid/HostParamValidator.java, common/src/test/java/org/apache/hertzbeat/common/support/vaild/EmailParamValidatorTest.java, common/src/test/java/org/apache/hertzbeat/common/support/vaild/HostParamValidatorTest.java, common/src/test/java/org/apache/hertzbeat/common/support/vaild/PhoneNumParamValidatorTest.java
- Add vaild util test 
- For #2325
=> [Improve] add unit test & fix some bugs

web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html
=> Remove the empty footer of "AppSwitchModal"

collector/src/test/java/org/apache/hertzbeat/collector/dispatch/entrance/internal/CollectJobServiceTest.java
- add collectJonService unit test
=> [Improve] add collectJonService unit test

web-app/src/app/routes/setting/collector/collector.component.html
before:
after:
Effectively utilize the built-in footer section of the modal module.
=> Optimize the layout of the "Deploy Collector" modal

warehouse/src/test/java/org/apache/hertzbeat/warehouse/store/RedisDataStorageTest.java
=> [improve] add redis data storage test case

common/src/main/java/org/apache/hertzbeat/common/util/CommonUtil.java, manager/src/main/java/org/apache/hertzbeat/manager/service/impl/AppServiceImpl.java
=> [imporve] add template i18n map verify

common/src/test/java/org/apache/hertzbeat/common/util/prometheus/PrometheusUtilTest.java
- Add prometheusUtil unit test
=> [Improve] add prometheusUtil unit test

manager/src/main/java/org/apache/hertzbeat/manager/component/alerter/impl/EmailAlertNotifyHandlerImpl.java, manager/src/main/java/org/apache/hertzbeat/manager/pojo/dto/EmailNoticeSender.java, manager/src/main/resources/application.yml, web-app/src/app/pojo/EmailNoticeSender.ts, web-app/src/app/routes/setting/settings/message-server/message-server.component.html, web-app/src/assets/i18n/en-US.json, web-app/src/assets/i18n/zh-CN.json, web-app/src/assets/i18n/zh-TW.json
=> [bufix] fix email send error

web-app/src/app/routes/alert/alert-setting/alert-setting.component.html, web-app/src/app/routes/alert/alert-setting/alert-setting.component.less, web-app/src/app/routes/alert/alert-setting/alert-setting.component.ts
=> Fixed the issue of missing form validation for the "Rule(Expr)" item in the "Threshold" form

home/i18n/zh-cn/docusaurus-plugin-content-blog/2022-07-10-hertzbeat-v1.1.1.md
=> [bugfix] fix mistake md content

web-app/README.md
[WIP] menu navigation and search
https://github.com/apache/hertzbeat/issues/1432
=> chore: update web-app readme

alerter/src/main/java/org/apache/hertzbeat/alert/controller/AlertDefinesController.java, alerter/src/main/java/org/apache/hertzbeat/alert/service/AlertDefineService.java, alerter/src/main/java/org/apache/hertzbeat/alert/service/impl/AlertDefineServiceImpl.java, alerter/src/test/java/org/apache/hertzbeat/alert/controller/AlertDefinesControllerTest.java, alerter/src/test/java/org/apache/hertzbeat/alert/service/AlertDefineServiceTest.java
=> [refactor] move code from AlertDefinesController to AlertDefineService

manager/src/main/resources/define/app-greenplum.yml, manager/src/main/resources/define/app-kingbase.yml, manager/src/main/resources/define/app-postgresql.yml
i missed some field`s i18n in last pr #2448, that was a mistake
=> [improve] add missed field i18n

collector/src/main/java/org/apache/hertzbeat/collector/dispatch/MetricsCollectorQueue.java, collector/src/test/java/org/apache/hertzbeat/collector/collect/redis/RedisClusterCollectImplTest.java, collector/src/test/java/org/apache/hertzbeat/collector/collect/redis/RedisSingleCollectImplTest.java, collector/src/test/java/org/apache/hertzbeat/collector/dispatch/MetricsCollectorQueueTest.java
optimize collect thread prevent cpu idling
refer https://github.com/apache/hertzbeat/pull/2466
=> [improve] optimize collect thread prevent cpu idling

manager/src/main/resources/define/app-iceberg.yml
=> [type:improve] add iceberg template

manager/src/main/resources/define/app-hive.yml, manager/src/main/resources/define/app-iceberg.yml, manager/src/test/java/org/apache/hertzbeat/manager/service/AccountServiceTest.java
=> [type:improve] add hive i18n

manager/src/main/resources/define/app-dynamic_tp.yml, manager/src/main/resources/define/app-emqx.yml, manager/src/main/resources/define/app-euleros.yml, manager/src/main/resources/define/app-hertzbeat.yml, manager/src/main/resources/define/app-hertzbeat_token.yml
=> [type:improve] add hertzbeat i18n

manager/src/main/resources/define/app-activemq.yml, manager/src/main/resources/define/app-airflow.yml, manager/src/main/resources/define/app-almalinux.yml, manager/src/main/resources/define/app-doris_be.yml, manager/src/main/resources/define/app-doris_fe.yml
=> [improve] add more i18n

manager/src/main/resources/define/app-influxdb_promql.yml, manager/src/main/resources/define/app-jetty.yml, manager/src/main/resources/define/app-kafka.yml, manager/src/main/resources/define/app-kafka_promql.yml
=> [type:improve] add kafka\influxdb\jetty i18n

manager/src/main/resources/define/app-oracle.yml
=> [type:improve] add oracle i18n

manager/src/main/resources/define/app-pulsar.yml, manager/src/main/resources/define/app-push.yml, manager/src/main/resources/define/app-rabbitmq.yml
=> [type:improve] add pulsar\push\rabbitm1 i18n

manager/src/main/resources/define/app-redis_cluster.yml, manager/src/main/resources/define/app-redis_sentinel.yml
=> [type:improve] add redis cluster i18n

manager/src/main/resources/define/app-springboot2.yml, manager/src/main/resources/define/app-tidb.yml
=> [type:improve] add spring\tidb i18n

.github/workflows/backend-build-test.yml, .github/workflows/nightly-build.yml, e2e/docker-compose.yml, script/docker/collector/Dockerfile, script/docker/collector/build.sh, script/docker/server/Dockerfile, script/docker/server/build.sh
fix github action build docker image error
support push hertzbeat hertzbeat-collector docker images nightly
=> [bugfix] fix github action build docker image error

web-app/src/app/routes/monitor/monitor-new/monitor-new.component.ts, web-app/src/app/shared/utils/common-util.ts
=> [improve] auto generate readable random monitor name

README.md, README_CN.md
Add Contributors' chart.
Add Contributors' chart.
=> Add Contributors' chart

manager/src/main/resources/define/app-valkey.yml
=> [type:feature] add valkey template

manager/src/main/resources/define/app-greptime.yml
=> [type:feature] add greptimedb template

web-app/src/app/routes/setting/plugins/plugin.component.html, web-app/src/app/routes/setting/plugins/plugin.component.ts, web-app/src/app/service/plugin.service.ts, web-app/src/assets/i18n/en-US.json, web-app/src/assets/i18n/zh-CN.json, web-app/src/assets/i18n/zh-TW.json
As the frontend portion of PR #2605
=> Complete task #2600

manager/src/main/resources/define/app-centos.yml
=> [improve]Centos network card information monitoring optimization

home/docs/help/pop3.md
translate pop3 help md to English
=> [improve] translate pop3 help md

script/assembly/server/bin/entrypoint.sh, script/docker/collector/Dockerfile
support master custom java opts for docker 
see https://github.com/apache/hertzbeat/discussions/2567
=> [improve] support master custom java opts

.markdownlint-cli2.jsonc, home/blog/2022-09-04-hertzbeat-v1.1.3.md, home/docs/help/memcached.md, home/docs/help/nebulagraph.md, home/i18n/zh-cn/docusaurus-plugin-content-blog/2022-09-04-hertzbeat-v1.1.3.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/nebulagraph.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/version-v1.5.x/help/nebulagraph.md, home/versioned_docs/version-v1.5.x/help/memcached.md, home/versioned_docs/version-v1.5.x/help/nebulagraph.md
=> [improve] improve markdown format for MD003

manager/src/main/java/org/apache/hertzbeat/manager/service/impl/TagServiceImpl.java
fix byte type npe in **TagServiceImpl**.  
@tomsun28 Related to PR # 2635
=> [fix] fix byte type npe.

.markdownlint-cli2.jsonc, home/docs/community/code-style-and-quality-guide.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/community/code-style-and-quality-guide.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/version-v1.5.x/community/code-style-and-quality-guide.md, home/versioned_docs/version-v1.5.x/community/code-style-and-quality-guide.md
=> [improve] improve markdown format for MD033

web-app/src/app/routes/bulletin/bulletin.component.html
link https://github.com/apache/hertzbeat/issues/2665
=> [task] customize dashboard jump to monitor detail

manager/src/main/java/org/apache/hertzbeat/manager/controller/BulletinController.java, manager/src/main/java/org/apache/hertzbeat/manager/dao/BulletinDao.java, manager/src/main/java/org/apache/hertzbeat/manager/service/impl/BulletinServiceImpl.java
add bulletin name check, fix this:
=> [bugfix] fix bulletin name check

web-app/src/app/routes/bulletin/bulletin.component.ts
clear filters when ok\cancel. 
if we don`t do this, last selected fields will be added to new dashboard
=> [bugfix] clear filters when ok\cancel

web-app/src/app/routes/monitor/monitor-form/monitor-form.component.html
=> [bugfix] fix monitor edit error

.all-contributorsrc, README.md, README_CN.md, home/src/pages/team/index.jsx, home/src/pages/team/member.json
=> [doc] add new contributor and committer

home/blog/2024-01-11-new-committer.md, home/i18n/zh-cn/docusaurus-plugin-content-blog/2024-01-11-new-committer.md, home/src/pages/team/member.json
=> remove personal info

home/blog/2024-09-10-new-committer.md, home/i18n/zh-cn/docusaurus-plugin-content-blog/2024-09-10-new-committer.md
=> [doc] Add new committer blog

manager/src/main/java/org/apache/hertzbeat/manager/config/ConfigInitializer.java
1. Increase the priority of configuration initialization ,prevent e2e failure caused by secret initialization
=> [improve] Increase the priority of configuration initialization

web-app/src/app/shared/components/tags-select/tags-select.component.ts
fix tag select component display and select error in monitor edit or threshold rule edit
=> [bugfix] fix tag select component display and select error

script/assembly/collector/assembly-linux-amd64.xml, script/assembly/collector/assembly-linux-arm64.xml, script/assembly/collector/assembly-macos-amd64.xml, script/assembly/collector/assembly-macos-arm64.xml, script/assembly/collector/assembly-windows-64.xml, script/assembly/collector/assembly.xml, script/assembly/collector/bin/entrypoint.sh, script/assembly/collector/bin/restart.sh, script/assembly/collector/bin/shutdown.bat, script/assembly/collector/bin/shutdown.sh, script/assembly/collector/bin/startup.bat, script/assembly/collector/bin/startup.sh, script/assembly/server/assembly-linux-amd64.xml, script/assembly/server/assembly-linux-arm64.xml, script/assembly/server/assembly-macos-amd64.xml, script/assembly/server/assembly-macos-arm64.xml, script/assembly/server/assembly-windows-64.xml, script/assembly/server/assembly.xml, script/assembly/server/bin/entrypoint.sh, script/assembly/server/bin/restart.sh, script/assembly/server/bin/shutdown.bat, script/assembly/server/bin/shutdown.sh, script/assembly/server/bin/startup.bat, script/assembly/server/bin/startup.sh
modify startup\ shutdown bin shells, to avoid modifications when build everytime
=> [improve] modify bin shells

script/assembly/collector/assembly-linux-amd64.xml, script/assembly/collector/assembly-linux-arm64.xml, script/assembly/collector/assembly-macos-amd64.xml, script/assembly/collector/assembly-macos-arm64.xml, script/assembly/collector/assembly-windows-64.xml, script/assembly/collector/assembly.xml, script/assembly/collector/bin/entrypoint.sh, script/assembly/collector/bin/restart.sh, script/assembly/collector/bin/shutdown.bat, script/assembly/collector/bin/shutdown.sh, script/assembly/collector/bin/startup.bat, script/assembly/collector/bin/startup.sh, script/assembly/server/assembly-linux-amd64.xml, script/assembly/server/assembly-linux-arm64.xml, script/assembly/server/assembly-macos-amd64.xml, script/assembly/server/assembly-macos-arm64.xml, script/assembly/server/assembly-windows-64.xml, script/assembly/server/assembly.xml, script/assembly/server/bin/entrypoint.sh, script/assembly/server/bin/restart.sh, script/assembly/server/bin/shutdown.bat, script/assembly/server/bin/shutdown.sh, script/assembly/server/bin/startup.bat, script/assembly/server/bin/startup.sh
=> [improve] revert modify bin shells

collector/collector-rocketmq/src/main/java/org/apache/hertzbeat/collector/collect/rocketmq/RocketmqSingleCollectImpl.java
=> [bugfix] fix code describe

material/licenses/LICENSE, material/licenses/frontend/LICENSE, material/licenses/frontend/LICENSE-ngx-query-builder.txt, web-app/yarn.lock
=> [license] add ngx query builder license and update

collector/collector/src/main/resources/application.yml
=> [release] update collector version 1.6.1

manager/src/main/resources/define/app-kafka_client.yml
Modify Kafka monitoring execution priority and optimize test connection speed
=> [Improve] Modify Kafka monitoring execution priority 

web-app/src/app/routes/bulletin/bulletin.component.html, web-app/src/app/routes/bulletin/bulletin.component.ts
=> [improve] support kanban tablename i18n

web-app/src/app/layout/basic/basic.component.ts
remove side nav user avatar, which is unnecessary
=> [improve] remove side nav user avatar

manager/src/main/resources/define/app-cisco_switch.yml, manager/src/main/resources/define/app-h3c_switch.yml, manager/src/main/resources/define/app-hpe_switch.yml, manager/src/main/resources/define/app-huawei_switch.yml, manager/src/main/resources/define/app-tplink_switch.yml, script/assembly/server/assembly-docker-compose.xml, script/docker-compose/LICENSE, script/docker-compose/hertzbeat-mysql-iotdb/conf/application.yml, script/docker-compose/hertzbeat-mysql-iotdb/conf/sureness.yml, script/docker-compose/hertzbeat-mysql-tdengine/conf/application.yml, script/docker-compose/hertzbeat-mysql-tdengine/conf/sureness.yml, script/docker-compose/hertzbeat-mysql-victoria-metrics/conf/application.yml, script/docker-compose/hertzbeat-mysql-victoria-metrics/conf/sureness.yml, script/docker-compose/hertzbeat-postgresql-victoria-metrics/conf/application.yml, script/docker-compose/hertzbeat-postgresql-victoria-metrics/conf/sureness.yml
- update docker-compose license 
- fix compose config yml
- update template yml
=> [improve] update docker-compose license and fix compose config yml

collector/collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/http/promethus/exporter/ExporterParser.java, collector/collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/prometheus/parser/TextParser.java, collector/collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/snmp/SnmpCollectImpl.java, collector/collector-common/src/main/java/org/apache/hertzbeat/collector/collect/common/cache/SshConnect.java, common/src/main/java/org/apache/hertzbeat/common/queue/impl/RedisCommonDataQueue.java, manager/src/main/java/org/apache/hertzbeat/manager/component/alerter/impl/EmailAlertNotifyHandlerImpl.java, warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/history/AbstractHistoryDataStorage.java
improve code according to code specifications
=> [improve] code according to code specifications(#2784)

pom.xml
…OM file
Remove the duplicate declaration of commons-net defined in the POM file
- [√]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
=> [fix]Remove the duplicate declaration of commons-net

.all-contributorsrc, README.md, README_CN.md, home/src/pages/team/index.jsx
=> [doc] update new contributors

hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/snmp/SnmpCollectImpl.java
修复windows系统监控中文乱码，支持GB2312格式的编码
https://github.com/apache/hertzbeat/issues/1493
=> [fix]fix windows chinese encoding

hertzbeat-common/src/main/java/org/apache/hertzbeat/common/entity/message/ClusterMsg.java, hertzbeat-common/src/main/message/cluster_msg.proto, hertzbeat-manager/src/main/java/org/apache/hertzbeat/manager/pojo/dto/MonitorDto.java, hertzbeat-manager/src/main/java/org/apache/hertzbeat/manager/service/impl/AbstractImExportServiceImpl.java, hertzbeat-manager/src/main/java/org/apache/hertzbeat/manager/service/impl/ExcelImExportServiceImpl.java, hertzbeat-manager/src/test/java/org/apache/hertzbeat/manager/controller/MonitorControllerTest.java, web-app/src/app/routes/monitor/monitor-edit/monitor-edit.component.ts, web-app/src/app/routes/monitor/monitor-new/monitor-new.component.ts
=> [fix] auto generated by protocol buffer

hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/database/JdbcCommonCollect.java
=> modified:add a small change.

hertzbeat-common/src/main/java/org/apache/hertzbeat/common/entity/job/Job.java
This PR simply deletes the redundant else.
=> [chore] Delete the redundant else

hertzbeat-manager/src/main/resources/define/app-process.yml
1.  Remap memory and IO related metrics
**Before**
**After**
=> [improve]improve linux process

hertzbeat-collector/hertzbeat-collector-kafka/src/main/java/org/apache/hertzbeat/collector/collect/kafka/KafkaConnect.java
bug：https://github.com/apache/hertzbeat/issues/2886
see diff and below
- [ ✅]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
=> [collector]bugfix:fix the issue of reusing the `adminClient` in the Kafka client.

CONTRIBUTING.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/community/contribution.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/community/development.md
=> [Doc] update doc

hertzbeat-common/src/main/java/org/apache/hertzbeat/common/entity/message/CollectRep.java
=> [improve] fix import of CollectRep

hertzbeat-warehouse/src/main/java/org/apache/hertzbeat/warehouse/service/impl/MetricsDataServiceImpl.java
- Replace "{}" key with empty string in instanceValuesMap
- Ensure compatibility with Grafana for empty tag values
=> [improve](warehouse): replace empty json object key with empty string

hertzbeat-common/pom.xml, hertzbeat-warehouse/pom.xml, pom.xml
fix dependencies vulnerabilites, link: https://github.com/apache/hertzbeat/issues/2797
=> [type:improve] fix dependencies vulnerabilites

web-app/src/index.html
=> [type:fix] remove matomo ip

hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/http/HttpCollectImpl.java, hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/push/PushCollectImpl.java, hertzbeat-collector/hertzbeat-collector-nebulagraph/src/main/java/org/apache/hertzbeat/collector/collect/nebulagraph/NebulaGraphCollectImpl.java
These are the last instances that don't get closed.
Also removes an unused param from a private method.
=> [MINOR UPDATE] fix more instances of unclosed Http Responses

web-app/src/app/routes/alert/alert-setting/alert-setting.component.html, web-app/src/app/routes/alert/alert-setting/alert-setting.component.less, web-app/src/app/routes/alert/alert-setting/alert-setting.component.ts, web-app/src/styles/theme.less
- Replace dropdown menu with draggable tags for environment variables and metrics
- Add drag-and-drop support for textarea to insert variables
- Update styles to accommodate new draggable elements
- Improve user experience by providing visual feedback during drag operations
=> [feature](alert): implement drag-and-drop functionality for alert templates

web-app/src/app/routes/alert/alert-group/alert-group-converge.component.html, web-app/src/app/routes/alert/alert-inhibit/alert-inhibit.component.html, web-app/src/app/routes/alert/alert-notice/alert-notice-receiver/alert-notice-receiver.component.html, web-app/src/app/routes/alert/alert-notice/alert-notice-rule/alert-notice-rule.component.html, web-app/src/app/routes/alert/alert-notice/alert-notice-template/alert-notice-template.component.html, web-app/src/app/routes/alert/alert-setting/alert-setting.component.html, web-app/src/app/routes/alert/alert-silence/alert-silence.component.html, web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html, web-app/src/app/routes/setting/collector/collector.component.html
[Issue](https://github.com/apache/hertzbeat/issues/3006)
Freeze the 'Operate' column on the right side of the list.
=> [improve] Freeze the 'Operate' column on the right side of the list.

hertzbeat-common/src/main/java/org/apache/hertzbeat/common/constants/AiTypeEnum.java, hertzbeat-common/src/main/java/org/apache/hertzbeat/common/entity/job/protocol/RocketmqProtocol.java, hertzbeat-manager/src/main/java/org/apache/hertzbeat/manager/scheduler/AssignJobs.java, template-marketplace/hertzbeat-template-hub/src/main/java/org/apache/hertzbeat/templatehub/controller/AccountController.java, template-marketplace/hertzbeat-template-hub/src/main/java/org/apache/hertzbeat/templatehub/sureness/SurenessFilterExample.java, template-marketplace/hertzbeat-template-hub/src/main/java/org/apache/hertzbeat/templatehub/sureness/provider/DatabasePathTreeProvider.java
=> [Improve] update english doc

hertzbeat-e2e/hertzbeat-collector-basic-e2e/src/test/java/org/apache/hertzbeat/collector/collect/basic/http/HttpMonitorE2eTest.java
=> [Feature] Add API e2e code

web-app/src/app/routes/monitor/monitor-data-table/monitor-data-table.component.html
Replaced the hardcoded "No Metrics Data" with the internationalized string `'monitor.detail.chart.no-data' | i18n`.
=> [improve] Replaced hardcoded text with internationalized string.

hertzbeat-manager/src/main/java/org/apache/hertzbeat/manager/service/impl/CollectorServiceImpl.java, hertzbeat-manager/src/main/java/org/apache/hertzbeat/manager/service/impl/MonitorServiceImpl.java, hertzbeat-manager/src/main/java/org/apache/hertzbeat/manager/service/impl/TagServiceImpl.java
Added case-insensitive search functionality to several search boxes, making them consistent with other pages without requiring case-specific input.
=> [improve] Search ignores case sensitivity.

hertzbeat-alerter/src/main/java/org/apache/hertzbeat/alert/reduce/AlarmGroupReduce.java, hertzbeat-manager/src/main/java/org/apache/hertzbeat/manager/service/impl/MonitorServiceImpl.java, hertzbeat-manager/src/main/resources/sureness.yml, script/docker-compose/hertzbeat-mysql-iotdb/conf/sureness.yml, script/docker-compose/hertzbeat-mysql-tdengine/conf/sureness.yml, script/docker-compose/hertzbeat-mysql-victoria-metrics/conf/sureness.yml, script/docker-compose/hertzbeat-postgresql-victoria-metrics/conf/sureness.yml, script/sureness.yml
=> [bugfix] fix singleton not support remove, search id error, audio fetch 401

hertzbeat-alerter/src/main/java/org/apache/hertzbeat/alert/controller/AlertInhibitController.java, hertzbeat-alerter/src/main/java/org/apache/hertzbeat/alert/controller/AlertInhibitsController.java
=> [API DOC] Change Swagger description

web-app/src/app/routes/alert/alert-center/alert-center.component.less, web-app/src/app/routes/alert/alert-integration/alert-integration.component.less, web-app/src/app/routes/dashboard/dashboard.component.html, web-app/src/app/routes/dashboard/dashboard.component.less, web-app/src/app/routes/dashboard/dashboard.component.ts, web-app/src/app/routes/setting/define/define.component.html, web-app/src/app/routes/setting/define/define.component.ts, web-app/src/app/routes/setting/tags/tags.component.less, web-app/src/app/service/theme.service.ts, web-app/src/styles/theme.less
=> [webapp] update ui theme

pom.xml, web-app/src/app/routes/monitor/monitor-data-chart/monitor-data-chart.component.ts
- Remove dataZoom feature from monitor chart
- Disable zoom and move interactions in chart
- Update GreptimeDB version from 0.9.1 to 0.11.0
- Update Springboot version to 3.4.2（due to cve）
=> [improve](web-app): update monitor chart configuration and springboot GreptimeDB version

home/docs/start/custom-config.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/start/custom-config.md
Update the SMS configuration document.
=> [doc] Update the SMS configuration document.

web-app/src/app/routes/alert/alert-group/alert-group-converge.component.html, web-app/src/app/routes/alert/alert-inhibit/alert-inhibit.component.html, web-app/src/app/routes/alert/alert-notice/alert-notice-receiver/alert-notice-receiver.component.html, web-app/src/app/routes/alert/alert-notice/alert-notice-rule/alert-notice-rule.component.html, web-app/src/app/routes/alert/alert-notice/alert-notice-template/alert-notice-template.component.html, web-app/src/app/routes/alert/alert-setting/alert-setting.component.html, web-app/src/app/routes/alert/alert-silence/alert-silence.component.html, web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html, web-app/src/app/routes/monitor/monitor-list/monitor-list.component.ts, web-app/src/app/routes/setting/collector/collector.component.html, web-app/src/app/routes/setting/plugins/plugin.component.html, web-app/src/app/routes/setting/tags/tags.component.html
Issue #3081
1. Unified the search trigger conditions to be triggered by pressing Enter or clicking the search button.  
2. Automatically refresh when clicking the ❌ button to clear the search box.
=> [improve] Improve and unify the search.

hertzbeat-collector/hertzbeat-collector-kafka/src/main/java/org/apache/hertzbeat/collector/collect/kafka/KafkaCollectImpl.java, hertzbeat-collector/hertzbeat-collector-kafka/src/test/java/org/apache/hertzbeat/collector/collect/kafka/KafkaCollectTest.java
=> [improve] optimize kafka collect test

home/docs/community/new_committer_process.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/community/new_committer_process.md
correct home's new_committer_process for it's Work list has false.
- [✅]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
=> correct home's new_committer_process

hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/snmp/SnmpCollectImpl.java
about #3090 , add support to parse the DateAndTime type in SnmpCollect, fixed display garbled characters
=> [type: fix] #3090 garbled characters

script/ci/exclude_files.txt
twitter link 400 ，Now it cannot be accessed directly and login is required.
=> [doc]fix link

pom.xml
…tion. (#3127)
Fixed #3127 opening swagger exception with error code 409, Failed to load API definition
=> [bugfix] Fix swagger opening exception that Failed to load API definition. (#3127)

hertzbeat-manager/src/main/java/org/apache/hertzbeat/manager/service/impl/PluginServiceImpl.java, hertzbeat-manager/src/test/java/org/apache/hertzbeat/manager/service/PluginServiceTest.java
=> [improve] improve plugin upload 

.gitpod.Dockerfile, .gitpod.yml
Optimize the Gitpod configuration, making the development environment independent of the Gitpod file, which facilitates later customization and maintenance.
=> Configuring gitpod with java

web-app/src/app/routes/bulletin/bulletin.component.html
=> Fix the issue of the empty dropdown menu on the Kanban board page.

.github/workflows/codeql-analysis.yml, .github/workflows/doc-build-test.yml, .github/workflows/doc-pdf-builder.yml, .github/workflows/frontend-build-test.yml, .github/workflows/license-checker.yml, .github/workflows/nightly-build.yml
=> [bugfix] fix nightly docker build github action

hertzbeat-manager/src/main/java/org/apache/hertzbeat/manager/service/impl/AppServiceImpl.java
#3158 Minor modification: fix incomplete class documentation in `AppServiceImpl`.
=> [bugfix]: fix incomplete class documentation in AppServiceImpl

.gitattributes
=> [improve] update git archive export ignore

NOTICE, home/docs/community/how-to-release.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/community/how-to-release.md, material/licenses/NOTICE, material/licenses/collector/NOTICE
- update notice copyright years
- update release steps help doc
=> [improve] update notice copyright years

home/i18n/zh-cn/docusaurus-plugin-content-docs/current.json, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/guide.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/version-v1.5.x/help/guide.md, web-app/src/assets/i18n/zh-CN.json, web-app/src/assets/i18n/zh-TW.json
=> fix: Ai is a typo

home/docs/community/development.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/community/development.md
Modify the error records in the document.，collector to hertzbeat-collector
=> [Doc]  Modify the error records in the document

hertzbeat-alerter/src/main/java/org/apache/hertzbeat/alert/service/impl/TencentSmsClientImpl.java
fix the [#3179 ](https://github.com/apache/hertzbeat/issues/3179)
=> [bug]bugfix:fix bug for package import error

hertzbeat-collector/hertzbeat-collector-basic/src/test/java/org/apache/hertzbeat/collector/collect/http/HttpCollectImplTest.java
- Add test case for parsing XML response using XPath expressions
- Verify correct extraction of data from XML structure
- Test multiple nodes selection with XPath
- Check proper handling of floating-point and integer values
=> [test](hertzbeat-collector): add unit test for XML response parsing

script/ci/exclude_files.txt
exclude dead link
```
FILE: ./home/i18n/zh-cn/docusaurus-plugin-content-blog/2024-06-15-hertzbeat-v1.6.0.md
[✖] https://github.com/apache/hertzbeat/pull/1957
[✖] https://github.com/apache/hertzbeat/pull/1994
258 links checked.
ERROR: 2 dead links found!
[✖] https://github.com/apache/hertzbeat/pull/1957 → Status: 502
[✖] https://github.com/apache/hertzbeat/pull/1994 → Status: 502
Error: Process completed with exit code 1.
```
=> [Doc] Fix dead link

home/docs/help/springboot2.md, home/docs/help/springboot3.md
[doc] Modify the YML configuration parameters for Spring Boot 2.0/3.0 monitoring (#3230)
=> [Doc] Modify the YML configuration parameters for Spring Boot 2.0/3.0 monitoring

home/i18n/zh-cn/docusaurus-plugin-content-docs/current/community/code-style-and-quality-guide.md
=> [doc] add code-style-check zh-ch.

.all-contributorsrc, README.md, README_CN.md, home/src/pages/team/index.jsx
add new contributors to wall, welcome!
=> [doc] add new contributors to wall

hertzbeat-warehouse/src/main/java/org/apache/hertzbeat/warehouse/db/PromqlQueryExecutor.java
fix UriComponentsBuilder in PromqlQueryExecutor
=> fix UriComponentsBuilder in PromqlQueryExecutor

hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/database/JdbcCommonCollect.java
fix a remote command execution.
=> [bugfix] fix a remote command execution.

.all-contributorsrc, README.md, README_CN.md, home/src/pages/team/index.jsx
=> [doc] add new contributor in wall

hertzbeat-manager/src/main/resources/templates/2-WebhookTemplate.txt
Fix wrong webhook alert template #3256
=> [bugfix]  Wrong webhook alert template

web-app/src/app/routes/monitor/monitor-list/monitor-list.component.html, web-app/src/styles/theme.less
=> [webapp] update header logo style

hertzbeat-mcp/src/main/java/org/apache/hertzbeat/mcp/server/service/LogService.java
=> [Improve] optimize prompt

hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/prometheus/parser/OnlineParser.java, hertzbeat-collector/hertzbeat-collector-basic/src/test/java/org/apache/hertzbeat/collector/collect/prometheus/parser/OnlineParserTest.java
=> [bugfix] fix the prometheus metric response data parsing is abnormal

README.md, README_JP.md, web-app/src/assets/i18n/ja-JP.json
=> [doc] japanese readme

hertzbeat-manager/src/main/resources/define/app-activemq.yml, web-app/src/assets/i18n/ja-JP.json
=> [doc] japanese activemq

README_JP.md, hertzbeat-manager/src/main/resources/define/app-activemq.yml, hertzbeat-manager/src/main/resources/define/app-almalinux.yml
=> [doc] japanese almalinux

.gitignore, .mvn/wrapper/maven-wrapper.properties
=> [build] Update .gitignore and add Maven wrapper properties

README.md, README_CN.md, README_JP.md, home/docs/community/contact.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/community/contact.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/version-v1.6.x/community/contact.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/version-v1.6.x/introduce.md, home/src/pages/team/member.json, home/versioned_docs/version-v1.6.x/community/contact.md, home/versioned_docs/version-v1.6.x/introduce.md
=> [doc] new ppmc liutianyou and update qq num

hertzbeat-alerter/src/main/java/org/apache/hertzbeat/alert/notice/impl/WeComRobotAlertNotifyHandlerImpl.java, hertzbeat-alerter/src/test/java/org/apache/hertzbeat/alert/notice/impl/WeComRobotAlertNotifyHandlerImplTest.java
[improve] improve url validation for WeComRobotAlertNotifyHandlerImpl
=> [improve] improve url validation for WeComRobotAlertNotifyHandlerImpl

hertzbeat-alerter/src/main/java/org/apache/hertzbeat/alert/notice/impl/TelegramBotAlertNotifyHandlerImpl.java, hertzbeat-alerter/src/test/java/org/apache/hertzbeat/alert/notice/impl/TelegramBotAlertNotifyHandlerImplTest.java
[improve] improve url validation for TelegramBotAlertNotifyHandlerImpl
=> [improve] improve url validation for TelegramBotAlertNotifyHandlerImpl

hertzbeat-alerter/src/main/java/org/apache/hertzbeat/alert/notice/impl/SlackAlertNotifyHandlerImpl.java, hertzbeat-alerter/src/test/java/org/apache/hertzbeat/alert/notice/impl/SlackAlertNotifyHandlerImplTest.java
improve url validation for SlackAlertNotifyHandlerImpl
=> [improve] improve url validation for SlackAlertNotifyHandlerImpl

hertzbeat-alerter/src/main/java/org/apache/hertzbeat/alert/notice/impl/ServerChanAlertNotifyHandlerImpl.java, hertzbeat-alerter/src/test/java/org/apache/hertzbeat/alert/notice/impl/ServerChanAlertNotifyHandlerImplTest.java
[improve] improve url validation for serverChan
=> [improve] improve url validation for serverChan

hertzbeat-collector/hertzbeat-collector-basic/src/test/java/org/apache/hertzbeat/collector/collect/sd/HttpSdCollectImplTest.java
Add unit tests for HttpSdCollectImpl
=> [test] Add unit tests for HttpSdCollectImpl

hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/prometheus/PrometheusAutoCollectImpl.java, hertzbeat-warehouse/src/main/java/org/apache/hertzbeat/warehouse/store/history/greptime/GreptimeDbDataStorage.java
- Update table name generation to use monitor ID instead of app name
- Prefix table names with "hzb" to avoid potential conflicts
- Fix history data querying by using correct table name
- Improve error handling in history data querying
- Update Prometheus collector to change field name from "value" to "metric_value"
=> [fix](warehouse): improve GreptimeDB data storage and querying

hertzbeat-manager/src/main/resources/define/app-consul_sd.yml
=> [doc] japanese consul sd

hertzbeat-manager/src/main/resources/define/app-coreos.yml
=> [doc] japanese coreos

hertzbeat-manager/src/main/resources/define/app-dahua.yml
=> [doc] japanese dahua

hertzbeat-manager/src/main/resources/define/app-almalinux.yml, hertzbeat-manager/src/main/resources/define/app-centos.yml, hertzbeat-manager/src/main/resources/define/app-coreos.yml, hertzbeat-manager/src/main/resources/define/app-debian.yml
=> [doc] japanese Debian

hertzbeat-manager/src/main/resources/define/app-deepseek.yml, hertzbeat-manager/src/main/resources/define/app-dm.yml
=> [doc] japanese deepseek & dm

hertzbeat-manager/src/main/resources/define/app-dns_sd.yml
=> [doc] japanese dns sd

hertzbeat-manager/src/main/resources/define/app-docker.yml
=> [doc] japanese docker

.github/ISSUE_TEMPLATE/feature-request.yml
refer: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#attributes
```markdown
- type: markdown
attributes:
value: "Thanks for completing our form!"
```
=> [infra]: Update issue tmpl

hertzbeat-manager/src/main/resources/define/app-eureka_sd.yml, hertzbeat-manager/src/main/resources/define/app-flink.yml
=> [doc] japanese flink

hertzbeat-manager/src/main/resources/define/app-freebsd.yml
=> [doc] japanese freebsd

hertzbeat-manager/src/main/resources/define/app-ftp.yml, hertzbeat-manager/src/main/resources/define/app-greenplum.yml
=> [doc] japanese greenplum

hertzbeat-manager/src/main/resources/define/app-fullsite.yml, hertzbeat-manager/src/main/resources/define/app-greptime.yml
=> [doc] japanese greptime

hertzbeat-manager/src/main/resources/define/app-h3c_switch.yml
=> [doc] japanese h3c switch

hertzbeat-manager/src/main/resources/define/app-hdfs_datanode.yml
=> [doc] japanese hdfs datanode

.github/workflows/backend-build-test.yml, script/ci/github-actions/setup-deps/action.yml
- Add installation and verification steps for mvnd in setup-deps action
- Update backend build step to use mvnd instead of mvn
=> [ci]: add mvnd support and update backend build

hertzbeat-manager/src/main/resources/define/app-activemq.yml, hertzbeat-manager/src/main/resources/define/app-almalinux.yml, hertzbeat-manager/src/main/resources/define/app-centos.yml, hertzbeat-manager/src/main/resources/define/app-coreos.yml, hertzbeat-manager/src/main/resources/define/app-darwin.yml, hertzbeat-manager/src/main/resources/define/app-debian.yml, hertzbeat-manager/src/main/resources/define/app-docker.yml, hertzbeat-manager/src/main/resources/define/app-dynamic_tp.yml, hertzbeat-manager/src/main/resources/define/app-euleros.yml, hertzbeat-manager/src/main/resources/define/app-flink.yml, hertzbeat-manager/src/main/resources/define/app-freebsd.yml, hertzbeat-manager/src/main/resources/define/app-hadoop.yml, hertzbeat-manager/src/main/resources/define/app-hdfs_namenode.yml
=> [doc] japanese hdfs namenode

hertzbeat-manager/src/main/resources/define/app-hertzbeat_token.yml
=> [doc] japanese hertzbeat token

hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/database/JdbcCommonCollect.java, hertzbeat-mcp/pom.xml
=> add:a small jdbc modified.

hertzbeat-manager/src/main/resources/define/app-hpe_switch.yml, hertzbeat-manager/src/main/resources/define/app-http_sd.yml
=> [doc] japanese hpe switch

hertzbeat-manager/src/main/resources/define/app-huawei_switch.yml
=> [doc] japanese huawei switch

hertzbeat-e2e/hertzbeat-collector-kafka-e2e/src/test/java/org/apache/hertzbeat/collector/collect/kafka/KafkaCollectE2eTest.java
=> [Improve] Improve kafka e2e

hertzbeat-manager/src/main/resources/define/app-activemq.yml, hertzbeat-manager/src/main/resources/define/app-api.yml, hertzbeat-manager/src/main/resources/define/app-cisco_switch.yml, hertzbeat-manager/src/main/resources/define/app-h3c_switch.yml, hertzbeat-manager/src/main/resources/define/app-hadoop.yml, hertzbeat-manager/src/main/resources/define/app-hbase_master.yml, hertzbeat-manager/src/main/resources/define/app-hbase_regionserver.yml, hertzbeat-manager/src/main/resources/define/app-hdfs_datanode.yml, hertzbeat-manager/src/main/resources/define/app-hdfs_namenode.yml, hertzbeat-manager/src/main/resources/define/app-hpe_switch.yml, hertzbeat-manager/src/main/resources/define/app-huawei_switch.yml, hertzbeat-manager/src/main/resources/define/app-hugegraph.yml, hertzbeat-manager/src/main/resources/define/app-influxdb.yml
=> [doc] japanese influxdb

hertzbeat-manager/src/main/resources/define/app-iotdb.yml
=> [doc] japanese iotdb

hertzbeat-manager/src/main/resources/define/app-ipmi.yml
=> [doc] japanese ipmi

home/src/pages/team/member.json
=> [doc] add new committer

hertzbeat-manager/src/main/resources/define/app-kubernetes.yml
=> [doc] japanese kubernetes

home/blog/2025-07-11-new-committer.md, home/i18n/zh-cn/docusaurus-plugin-content-blog/2025-07-11-new-committer.md
=> [docs] Add new committer blog

hertzbeat-manager/src/main/resources/define/app-kvrocks.yml
=> [doc] japanese kvrocks

hertzbeat-manager/src/main/resources/define/app-linux.yml
=> [doc] japanese linux

hertzbeat-collector/hertzbeat-collector-basic/src/main/java/org/apache/hertzbeat/collector/collect/http/HttpCollectImpl.java
- Fix a problem where the inputstream was closed prematurely when parsing Prometheus
=> [fix]: Fix a problem where the inputstream was closed prematurely when parsing Prometheus

hertzbeat-manager/src/main/resources/define/app-nginx.yml
Please refer to: [#3591](https://github.com/apache/hertzbeat/issues/3591)
=> [doc] add japanese i18n in app-nginx.yml

home/src/css/custom.css
allow wrap on medium size
close: https://github.com/apache/hertzbeat/issues/2670
=> [doc] Optimize the home website navbar layout UI for medium-sized screens

hertzbeat-manager/src/main/resources/define/app-opensuse.yml
=> [doc] add japanese i18n in app-opensuse.yml

hertzbeat-common/src/main/java/org/apache/hertzbeat/common/constants/CommonConstants.java, hertzbeat-common/src/main/java/org/apache/hertzbeat/common/util/JexlExpressionRunner.java, hertzbeat-common/src/test/java/org/apache/hertzbeat/common/util/JexlExpressionRunnerTest.java
Please refer to: [#3644](https://github.com/apache/hertzbeat/issues/3644)
Added JEXL custom function that support nested JSON parsing.
For details:
1. Added JEXL custom json function
2. Add test cases and pass historical test cases.
```yaml
metrics:
- name: channel_item_info
i18n:
en-US: channel item info
priority: 2
fields:
- field: type
i18n:
en-US: type
type: 1
label: true
- field: current
i18n:
en-US: current
type: 0
- field: instanceCode
i18n:
en-US: instanceCode
type: 1
- field: timeMillis
i18n:
en-US: timeMillis
type: 1
aliasFields:
- type
- $.info
calculates:
- type=type
- current=json:apply($.info).current
- instanceCode=json:apply($.info).instanceCode
- timeMillis=json:apply($.info).timeMillis
protocol: http
http:
host: ^_^host^_^
port: ^_^port^_^
url: …
```
=> [feat] Monitoring templates support JSON nested parsing.

hertzbeat-collector/hertzbeat-collector-common/src/main/java/org/apache/hertzbeat/collector/dispatch/entrance/processor/GoOnlineProcessor.java, hertzbeat-common/src/main/java/org/apache/hertzbeat/common/entity/dto/ServerInfo.java, hertzbeat-common/src/main/java/org/apache/hertzbeat/common/util/AesUtil.java, hertzbeat-common/src/test/java/org/apache/hertzbeat/common/util/AesUtilTest.java, hertzbeat-manager/src/main/java/org/apache/hertzbeat/manager/config/ConfigInitializer.java, hertzbeat-manager/src/main/java/org/apache/hertzbeat/manager/scheduler/CollectorJobScheduler.java, hertzbeat-manager/src/main/java/org/apache/hertzbeat/manager/scheduler/netty/process/CollectorOnlineProcessor.java, hertzbeat-remoting/src/main/java/org/apache/hertzbeat/remoting/netty/NettyRemotingAbstract.java
=> [bugfix] fix the collector aes decode with secret error

hertzbeat-manager/src/main/resources/define/app-tidb.yml, hertzbeat-manager/src/main/resources/define/app-windows_script.yml
=> [doc] add japanese i18n in app-tidb.yml, app-windows_script.yml

hertzbeat-manager/src/main/resources/define/app-springboot3.yml
Please refer to: https://github.com/apache/hertzbeat/issues/3591
=> [doc] add japanese i18n in app-springboot3.yml

home/docs/help/ubuntu.md, home/docs/start/usecase/linux-os-practice.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/help/ubuntu.md, home/i18n/zh-cn/docusaurus-plugin-content-docs/current/start/usecase/linux-os-practice.md
Closed: #3657
- fixed `MD032`、 `MD031`、 `MD047` issue in document `help/ubuntu.md`
- fixed `MD009` in document `start/usecase/linux-os-practice.md`
> MD032/blanks-around-lists: Lists should be surrounded by blank lines
> MD031/blanks-around-fences: Fenced code blocks should be surrounded by blank lines
> MD047/single-trailing-newline: Files should end with a single newline character
> MD009/no-trailing-spaces: Trailing spaces
The result of running command `yarn md-lint`
```bash
yarn run v1.22.22
$ markdownlint-cli2 --config ../.markdownlint-cli2.jsonc "./**/*.md" "#node_modules"
markdownlint-cli2 v0.13.0 (markdownlint v0.34.0)
Finding: ./**/*.md !node_modules home/**/*.md !**/node_modules/** !**/target/** !**/dist/**
Linting: 843 file(s)
Summary: 0 error(s)
✨  Done in 5.42s.
```
=> [doc] improve documentation formatting and readability

hertzbeat-manager/src/main/resources/define/app-prestodb.yml, hertzbeat-manager/src/main/resources/define/app-spark.yml
=> [doc] add japanese i18n in app-prestodb.yml, app-spark.yml

hertzbeat-manager/src/main/resources/define/app-process.yml
=> [doc] add japanese i18n in app-process.yml

hertzbeat-manager/src/main/resources/define/app-redhat.yml
=> [doc] add japanese i18n in app-redhat.yml

hertzbeat-manager/src/main/resources/define/app-vastbase.yml
=> [doc] add japanese i18n in app-vastbase.yml

.all-contributorsrc
=> [docs] Update contributors

hertzbeat-manager/src/main/resources/db/migration/h2/V180__update_column.sql, hertzbeat-manager/src/main/resources/db/migration/mysql/V180__update_column.sql, hertzbeat-manager/src/main/resources/db/migration/postgresql/V180__update_column.sql
=> [fix] remove v174 and add v180 flway script
